// autogenerated file from bo4.json, do not edit this file

// game template id
constexpr const char* GAME_ID = "bo4";
// dumped module name
constexpr const char* MODULE_NAME = "BlackOps4_dump.exe";
// first asset name
constexpr const char* FIRST_ASSET_NAME = "physpreset";
// end asset name
constexpr const char* END_ASSET_NAME = "assetlist";

/*
 * Dvar
 */

// Register dvar (Dvar)
extern hook::refs::Ref<dvar_t*(XHash* name, const char* desc, dvarType_t type, int flags, DvarValue* value, DvarLimits* domain)> Dvar_Register;
// dvar_loc_language dvar (Dvar)
extern hook::refs::Ref<const dvar_t*> dvar_loc_language;
// hash table index (Dvar)
extern hook::refs::Ref<const dvar_t* [0x400]> s_dvarHashTable;
// dvar pool (Dvar)
extern hook::refs::Ref<const dvar_t[0x1000]> s_dvarPool;

/*
 * Fast Files
 */

// Allocate XFile loading pointer (Fast Files)
extern hook::refs::Ref<void* (int alignment)> DB_AllocStreamPos;
// Alloc the XBlock buffers (Fast Files)
extern hook::refs::Ref<void (size_t *blockSize, const char *filename, const char *filename2, XBlock *blocks, int side, int *loaded)> DB_AllocXBlocks;
// DB_AuthLoad_AnalyzeData (Fast Files)
extern hook::refs::Ref<void> DB_AuthLoad_AnalyzeData;
// DB_AuthLoad_End (Fast Files)
extern hook::refs::Ref<void> DB_AuthLoad_End;
// Convert XFile offset to alias (Fast Files)
extern hook::refs::Ref<void (void** data)> DB_ConvertOffsetToAlias;
// Convert XFile offset to pointer (Fast Files)
extern hook::refs::Ref<void (void** data)> DB_ConvertOffsetToPointer;
// Test if an XAsset exists (Fast Files)
extern hook::refs::Ref<bool(XAssetType type, XHash* name)> DB_DoesXAssetExist;
// DB_ExpandZoneList (Fast Files)
extern hook::refs::Ref<void> DB_ExpandZoneList;
// Does a zone file exists (Fast Files)
extern hook::refs::Ref<bool(const char* file)> DB_FileExists;
// Find a XAsset header (Fast Files)
extern hook::refs::Ref<XAssetHeader(XAssetType type, XHash* name, bool errorIfMissing, int waitTime)> DB_FindXAssetHeader;
// Get XFile offset data (Fast Files)
extern hook::refs::Ref<void* (uint64_t ref)> DB_GetOffsetData;
// Get XAsset name (Fast Files)
extern hook::refs::Ref<XHash*(XHash* hash, const XAsset* asset)> DB_GetXAssetName;
// Move XFile loading stream (Fast Files)
extern hook::refs::Ref<void (size_t size)> DB_IncStreamPos;
// Init the XFile streams with XBlock buffers (Fast Files)
extern hook::refs::Ref<void (XBlock *blocks)> DB_InitStreams;
// Insert file to loading stream (Fast Files)
extern hook::refs::Ref<const void** ()> DB_InsertPointer;
// Are 4k fastfiles loaded (Fast Files)
extern hook::refs::Ref<bool()> DB_Is4KEnabled;
// Link an XAsset entry (Fast Files)
extern hook::refs::Ref<XAssetEntryPoolEntry* (XAsset *newEntry, bool allowOverride)> DB_LinkXAssetEntry;
// DB_LoadXAssets (Fast Files)
extern hook::refs::Ref<void> DB_LoadXAssets;
// DB_LoadXFile (Fast Files)
extern hook::refs::Ref<void> DB_LoadXFile;
// Load data from XFile (Fast Files)
extern hook::refs::Ref<void (byte *pos, int size)> DB_LoadXFileData;
// Pop XFile loading stream block (Fast Files)
extern hook::refs::Ref<void ()> DB_PopStreamPos;
// Push XFile loading stream block (Fast Files)
extern hook::refs::Ref<void (int index)> DB_PushStreamPos;
// DB_ValidateFileHeader (Fast Files)
extern hook::refs::Ref<void> DB_ValidateFileHeader;
// Load a stream of the loaded XFile (Fast Files)
extern hook::refs::Ref<bool (bool atStreamStart, void *ptr, size_t size)> Load_Stream;
// Load an XAsset of the loaded XFile (Fast Files)
extern hook::refs::Ref<void (bool atStreamStart, XAsset *asset)> Load_XAsset;
// Load an XHash (Fast Files)
extern hook::refs::Ref<void (XHash* hash)> Load_XHash;
// Load an XString (Fast Files)
extern hook::refs::Ref<void (const char** str)> Load_XStringCustom;
// Stream_OpenFileInternal (Fast Files)
extern hook::refs::Ref<void> Stream_OpenFileInternal;
// asset pool data (Fast Files)
extern hook::refs::Ref<XAssetPool> s_assetPools;

/*
 * File System
 */

// Close a file (File System)
extern hook::refs::Ref<void(int32_t fileid)> Stream_CloseFile;
// Open a file (File System)
extern hook::refs::Ref<int32_t(const char* file)> Stream_OpenFile49;

/*
 * Script Code
 */

// Convert a ScrVarIndex_t to string (Script Code)
extern hook::refs::Ref<const char*(ScrVarIndex_t index)> ScrStr_ConvertToString;
// New variable by index (Script Code)
extern hook::refs::Ref<ScrVarIndex_t(scriptInstance_t inst, ScrVarIndex_t parentId, ScrVarNameIndex_t index)> ScrVar_NewVariableByIndex;
// Add an array (Script Code)
extern hook::refs::Ref<void(scriptInstance_t inst)> ScrVar_PushArray;
// Set a value (Script Code)
extern hook::refs::Ref<void(scriptInstance_t inst, ScrVarIndex_t id, ScrVarValue_t* value)> ScrVar_SetValue;
// Add an API function (Script Code)
extern hook::refs::Ref<void(scriptInstance_t inst, void* func)> ScrVm_AddAPIFunction;
// Add a boolean (Script Code)
extern hook::refs::Ref<void(scriptInstance_t inst, int value)> ScrVm_AddBool;
// Add a const string (Script Code)
extern hook::refs::Ref<void(scriptInstance_t inst, ScrString_t value)> ScrVm_AddConstString;
// Add an entity num (Script Code)
extern hook::refs::Ref<void(scriptInstance_t inst, EntRefUnion value, ClassNum classNum, LocalClientNum_t num)> ScrVm_AddEntityNum;
// Add a float (Script Code)
extern hook::refs::Ref<void(scriptInstance_t inst, float value)> ScrVm_AddFloat;
// Add a xhash (Script Code)
extern hook::refs::Ref<void(scriptInstance_t inst, XHash* value)> ScrVm_AddHash;
// Add an integer (Script Code)
extern hook::refs::Ref<void(scriptInstance_t inst, int64_t value)> ScrVm_AddInt;
// Add a script function (Script Code)
extern hook::refs::Ref<void(scriptInstance_t inst, byte* codePos)> ScrVm_AddScriptFunction;
// Add a string (Script Code)
extern hook::refs::Ref<void(scriptInstance_t inst, const char *value)> ScrVm_AddString;
// Add a structure (Script Code)
extern hook::refs::Ref<uint32_t(scriptInstance_t inst)> ScrVm_AddStruct;
// Add an element to array (Script Code)
extern hook::refs::Ref<void(scriptInstance_t inst)> ScrVm_AddToArray;
// Add an element to array with key name (Script Code)
extern hook::refs::Ref<void(scriptInstance_t inst, XHash* name)> ScrVm_AddToArrayStringIndexed;
// Add undefined (Script Code)
extern hook::refs::Ref<void(scriptInstance_t inst)> ScrVm_AddUndefined;
// Add a vector (Script Code)
extern hook::refs::Ref<void(scriptInstance_t inst, vec3_t* vec)> ScrVm_AddVector;
// Get a bool param (Script Code)
extern hook::refs::Ref<bool(scriptInstance_t inst, unsigned int index)> ScrVm_GetBool;
// Get a const string param (Script Code)
extern hook::refs::Ref<ScrVarIndex_t(scriptInstance_t inst, unsigned int index)> ScrVm_GetConstString;
// Get an entity ref (Script Code)
extern hook::refs::Ref<scr_entref_t*(scr_entref_t* ent, scriptInstance_t inst, unsigned int index)> ScrVm_GetEntityRef;
// Get a float param (Script Code)
extern hook::refs::Ref<float(scriptInstance_t inst, unsigned int index)> ScrVm_GetFloat;
// Get a xhash param (Script Code)
extern hook::refs::Ref<XHash*(XHash* hash, scriptInstance_t inst, unsigned int index)> ScrVm_GetHash;
// Get a integer param (Script Code)
extern hook::refs::Ref<int64_t(scriptInstance_t inst, unsigned int index)> ScrVm_GetInt;
// Get the params count (Script Code)
extern hook::refs::Ref<uint32_t(scriptInstance_t inst)> ScrVm_GetNumParam;
// Get a pointer param type (Script Code)
extern hook::refs::Ref<ScrVarType_t(scriptInstance_t inst, unsigned int index)> ScrVm_GetPointerType;
// Get a string param (Script Code)
extern hook::refs::Ref<const char*(scriptInstance_t inst, unsigned int index)> ScrVm_GetString;
// Get a param type (Script Code)
extern hook::refs::Ref<ScrVarType_t(scriptInstance_t inst, unsigned int index)> ScrVm_GetType;
// Get a param value (Script Code)
extern hook::refs::Ref<ScrVarValue_t*(scriptInstance_t inst, unsigned int index)> ScrVm_GetValue;
// Get a vector param (Script Code)
extern hook::refs::Ref<void(scriptInstance_t inst, unsigned int index, vec3_t* vector)> ScrVm_GetVector;
// Set a structure field (Script Code)
extern hook::refs::Ref<void(scriptInstance_t inst, uint32_t structId, uint32_t name)> ScrVm_SetStructField;

/*
 * GSC API Functions
 */

// Get an API client function (GSC API Functions)
extern hook::refs::Ref<BuiltinFunction(uint32_t canonId, int* type, int* min_args, int* max_args)> CScr_GetFunction;
// Lookup an API client function (GSC API Functions)
extern hook::refs::Ref<bool(byte* func, uint32_t* name, bool* isFunction)> CScr_GetFunctionReverseLookup;
// Get an API client method (GSC API Functions)
extern hook::refs::Ref<void*(uint32_t canonId, int* type, int* min_args, int* max_args)> CScr_GetMethod;
// Link the script exports (GSC API Functions)
extern hook::refs::Ref<int(scriptInstance_t inst, GSC_OBJ *prime_obj)> GscObjResolve;
// Allocate a string into the MT buffer (GSC API Functions)
extern hook::refs::Ref<ScrString_t(const char* str, unsigned int user, ScrStringType type, bool decrypt)> SL_GetStringOfSize;
// Transfer a string reference to a user (GSC API Functions)
extern hook::refs::Ref<void(ScrString_t stringValue, unsigned int user)> SL_TransferRefToUser;
// Fire an event (GSC API Functions)
extern hook::refs::Ref<void(scriptInstance_t inst, uint32_t stringValue, int entnum, bool is_params)> ScrEvent_FireCallbackEventEnt;
// Add class fields to a class (GSC API Functions)
extern hook::refs::Ref<void(scriptInstance_t inst, ClassNum classnum, uint32_t canonId, int32_t offset)> ScrVar_AddClassFields;
// Init class map (GSC API Functions)
extern hook::refs::Ref<void(scriptInstance_t inst, ClassNum classnum)> ScrVar_InitClassMap;
// Throw a script error (GSC API Functions)
extern hook::refs::Ref<void(uint64_t code, scriptInstance_t inst, char* unused, bool terminal)> ScrVm_Error;
// Construct a message string for network (GSC API Functions)
extern hook::refs::Ref<void(scriptInstance_t inst, MessageString* string, signed int startIndex, int endIndex)> Scr_ConstructMessageString;
// Get an API server function (GSC API Functions)
extern hook::refs::Ref<BuiltinFunction(uint32_t canonId, int* type, int* min_args, int* max_args)> Scr_GetFunction;
// Lookup an API server function (GSC API Functions)
extern hook::refs::Ref<bool(byte* func, uint32_t* name, bool* isFunction)> Scr_GetFunctionReverseLookup;
// Get generic field from data (GSC API Functions)
extern hook::refs::Ref<void(scriptInstance_t inst, const byte* b, fieldtype_t type, int ofs)> Scr_GetGenericField;
// Get the export information of a bytecode position (GSC API Functions)
extern hook::refs::Ref<void(scriptInstance_t inst, byte* codepos, const char** scriptname, int32_t* sloc, int32_t* crc, int32_t* vm)> Scr_GetGscExportInfo;
// Get an API server method (GSC API Functions)
extern hook::refs::Ref<void*(uint32_t canonId, int* type, int* min_args, int* max_args)> Scr_GetMethod;
// Get object field (GSC API Functions)
extern hook::refs::Ref<void(ClassNum classnum, EntRefUnion entRefUnion, uint32_t offset)> Scr_GetObjectField;
// Link a script (GSC API Functions)
extern hook::refs::Ref<void (scriptInstance_t inst, XHash* filename, bool runScript)> Scr_GscLink;
// Reset the script linking information (GSC API Functions)
extern hook::refs::Ref<void(scriptInstance_t inst)> Scr_ResetLinkInfo;
// Set generic field to data (GSC API Functions)
extern hook::refs::Ref<void(scriptInstance_t inst, byte* b, fieldtype_t type, int ofs)> Scr_SetGenericField;
// Set object field (GSC API Functions)
extern hook::refs::Ref<bool(ClassNum classnum, EntRefUnion entRefUnion, uint32_t offset)> Scr_SetObjectField;

/*
 * GSC Stuctures
 */

// linker scripts information (GSC Stuctures)
extern hook::refs::Ref<objFileInfo_t[scriptInstance_t::SI_COUNT][650]> gObjFileInfo;
// linked scripts count (GSC Stuctures)
extern hook::refs::Ref<uint32_t> gObjFileInfoCount;
// script opcodes table (GSC Stuctures)
extern hook::refs::Ref<VM_OP_FUNC> gVmOpJumpTable;
// script error opcodes table (GSC Stuctures)
extern hook::refs::Ref<VM_OP_ERR_FUNC> gVmOpJumpTableError;
// script modtool error opcodes table (GSC Stuctures)
extern hook::refs::Ref<VM_OP_ERR_FUNC> gVmOpJumpTableErrorModTool;
// script modtool opcodes table (GSC Stuctures)
extern hook::refs::Ref<VM_OP_FUNC> gVmOpJumpTableModTool;
// script global variables (GSC Stuctures)
extern hook::refs::Ref<scrVarGlob_t> scrVarGlob;
// script public variables (GSC Stuctures)
extern hook::refs::Ref<BO4_scrVarPub> scrVarPub;
// script VM var type names (GSC Stuctures)
extern hook::refs::Ref<const char*> scrVarTypeNames;
// Invalid gsc functions array (GSC Stuctures)
extern hook::refs::Ref<void*> scrVmInvalidFuncs;
// script vm data (GSC Stuctures)
extern hook::refs::Ref<scrVmPub_t> scrVmPub;

/*
 * Lua
 */

// begin a readonly table (Lua)
extern hook::refs::Ref<void(const char* tname, lua_State* luaVM)> Lua_BeginTableReadOnly;
// load and execute a lua file (Lua)
extern hook::refs::Ref<bool(lua_State* luaVM, const char* file)> Lua_CoD_LoadLuaFile;
// Register the Engine functions (Lua)
extern hook::refs::Ref<void(lua_State* state)> Lua_CoD_RegisterEngineFunctions;
// register a lua function to the current table (Lua)
extern hook::refs::Ref<void(lua_State* luaVM, XHash* name, int (*func)(lua_State* s))> Lua_Cod_RegisterFunction;
// end a readonly table (Lua)
extern hook::refs::Ref<void(lua_State* luaVM)> Lua_EndTableReadOnly;
// HksObject to xhash (Lua)
extern hook::refs::Ref<XHash*(XHash* retval, lua_State* luaVM, int idx)> hks_obj_tolhash;
// HksObject to string (Lua)
extern hook::refs::Ref<const char*(lua_State* luaVM, HksObject* obj, size_t* len)> hks_obj_tolstring;
// HksObject to number (Lua)
extern hook::refs::Ref<float(lua_State* luaVM, const HksObject* obj)> hks_obj_tonumber;
// hks error (Lua)
extern hook::refs::Ref<int(lua_State* s, HksError errorCode)> hksi_hks_error;
// Get information about a closure (Lua)
extern hook::refs::Ref<bool(lua_State* s, HksClosure* closure, lua_Debug* ar, const char* what)> hksi_lua_getclosureinfo;
// push a string (Lua)
extern hook::refs::Ref<void(lua_State* s, const char* str, size_t l)> hksi_lua_pushlstring;
// push a xhash (Lua)
extern hook::refs::Ref<void(lua_State* s, const char* str)> hksi_lua_pushxhash;
// set a field (Lua)
extern hook::refs::Ref<void(lua_State* s, int index, const char* k)> hksi_lua_setfield;
// Load a lua file (Lua)
extern hook::refs::Ref<int(lua_State* state, const char* filename)> hksl_loadfile;

/*
 * System
 */

// Deploy a server command (System)
extern hook::refs::Ref<void(LocalClientNum_t localClientNum)> CG_DeployServerCommand;
// Register an internal function (System)
extern hook::refs::Ref<void(XHash* cmdName, xcommand_t function, cmd_function_t* allocedCmd)> Cmd_AddCommandInternal;
// Common error (System)
extern hook::refs::Ref<void(uint32_t code)> Com_Error;
// Get the language name abbreviation (System)
extern hook::refs::Ref<const char*(int32_t lang)> SEH_GetLanguageNameAbbr;
// Send a server command (System)
extern hook::refs::Ref<void(client_t* cl_0, svscmd_type type, const char* fmt, ...)> SV_SendServerCommand;
// ScopedCriticalSection::ScopedCriticalSection (System)
extern hook::refs::Ref<void(ScopedCriticalSection* sec, int32_t s, ScopedCriticalSectionType type)> ScopedCriticalSectionConstructor;
// ScopedCriticalSection::~ScopedCriticalSection (System)
extern hook::refs::Ref<void(ScopedCriticalSection* sec)> ScopedCriticalSectionDestructor;
// Log a compiler error (System)
extern hook::refs::Ref<void(const char* fmt, ...)> ScrVm_LogCompilerError;
// System error (System)
extern hook::refs::Ref<void(uint32_t code, const char* msg)> Sys_Error;
// Get command params (System)
extern hook::refs::Ref<const char*(int32_t index)> Sys_GetParamSafe;
// Get TLS data (System)
extern hook::refs::Ref<TLSData*()> Sys_GetTLS;

/*
 * UI
 */

// Add draw command (UI)
extern hook::refs::Ref<void(const char* text, int maxChars, Font* font, float x, float y, float xScale, float yScale, float rotation, const vec_t* color, int style, int cursorPos, char cursor, float padding)> AddBaseDrawTextCmd;
// Add begin view command (UI)
extern hook::refs::Ref<void(const void* sceneDef, const void* viewParms)> R_AddCmdBeginView;
// Add clear screen command (UI)
extern hook::refs::Ref<void> R_AddCmdClearScreen;
// Add draw emblem layer command (UI)
extern hook::refs::Ref<void(const void* emblemLayer)> R_AddCmdDrawEmblemLayer;
// Add command (UI)
extern hook::refs::Ref<void(const vec_t* verts, const vec_t* color, Material* material)> R_AddCmdDrawQuadPic;
// Add command (UI)
extern hook::refs::Ref<void> R_AddCmdDrawQuadPicW;
// Add command (UI)
extern hook::refs::Ref<void(float x, float y, float w, float h, float s0, float t0, float s1, float t1, float* color, Material* material)> R_AddCmdDrawStretchPic;
// Add command (UI)
extern hook::refs::Ref<void(const char* text, Font* font, const vec_t* org, const vec_t* xPixelStep, const vec_t* color, const vec_t* yPixelStep)> R_AddCmdDrawTextInSpace;
// Add command (UI)
extern hook::refs::Ref<void> R_AddCmdDrawUIQuads;
// Add command (UI)
extern hook::refs::Ref<void> R_AddCmdDrawUIQuadsReplaceImage;
// Add end of list command (UI)
extern hook::refs::Ref<void()> R_AddCmdEndOfList;
// Add projection set 2d command (UI)
extern hook::refs::Ref<void()> R_AddCmdProjectionSet2D;
// Add projection set 3d command (UI)
extern hook::refs::Ref<void()> R_AddCmdProjectionSet3D;
// Add resolve composite command (UI)
extern hook::refs::Ref<void(GfxImage* image, void* callback)> R_AddCmdResolveComposite;
// Add set image render command (UI)
extern hook::refs::Ref<void(const GfxImage* rt)> R_AddCmdSetImageRenderTarget;
// Add set scissor values command (UI)
extern hook::refs::Ref<void(bool enabled, int x, int y, int width, int height)> R_AddCmdSetScissorValues;
// Add set ui texture sources command (UI)
extern hook::refs::Ref<void(bool forceBlack)> R_AddCmdSetUITextureSources;
// Add set viewport values command (UI)
extern hook::refs::Ref<void(int x, int y, int width, int height)> R_AddCmdSetViewportValues;
// Render a frame (UI)
extern hook::refs::Ref<void()> R_EndFrame;
// Get text height (UI)
extern hook::refs::Ref<uint32_t(Font* font)> R_TextHeight;
// Get text width (UI)
extern hook::refs::Ref<float(const LocalClientNum_t localClientNum, const char* text, int maxChars, Font* font)> R_TextWidth;
// Get screen for a local client (UI)
extern hook::refs::Ref<const ScreenPlacement*(const LocalClientNum_t localClientNum)> ScrPlace_GetView;
// Get scaled text height (UI)
extern hook::refs::Ref<uint32_t(Font* font, float scale)> UI_TextHeight;
// Get text scaled width (UI)
extern hook::refs::Ref<uint32_t(const LocalClientNum_t localClientNum, const char* text, int maxChars, Font* font, float scale)> UI_TextWidth;
// Shared ui data (UI)
extern hook::refs::Ref<sharedUiInfo_t> sharedUiInfo;

/*
 * @return the common fastfile names
 */
std::span<const char*> GetCommonFastFiles();

/*
 * Load the scans for the game
 * @param scan game
 */
void LoadScans(hook::scan_container::ScanContainer& scan);
