// autogenerated file from bo4.json, do not edit this file

// common fastfiles names
std::span<const char*> GetCommonFastFiles() {
    static const char* files[] { 
        "zone/core_common.ff",
        "zone/mp_common.ff",
        "zone/mp_common_all.ff",
        "zone/mp_common_script.ff",
        "zone/wz_common.ff",
        "zone/wz_common_all.ff",
        "zone/wz_common_script.ff",
        "zone/zm_common.ff",
        "zone/zm_common_all.ff",
        "zone/zm_common_script.ff",
    };
    return files;
}

// refs

// Dvar_Register
hook::refs::Ref<dvar_t*(XHash* name, const char* desc, dvarType_t type, int flags, DvarValue* value, DvarLimits* domain)> Dvar_Register{ nullptr };
// dvar_loc_language
hook::refs::Ref<const dvar_t*> dvar_loc_language{ nullptr };
// s_dvarHashTable
hook::refs::Ref<const dvar_t* [0x400]> s_dvarHashTable{ nullptr };
// s_dvarPool
hook::refs::Ref<const dvar_t[0x1000]> s_dvarPool{ nullptr };

// DB_AllocStreamPos
hook::refs::Ref<void* (int alignment)> DB_AllocStreamPos{ nullptr };
// DB_AllocXBlocks
hook::refs::Ref<void (size_t *blockSize, const char *filename, const char *filename2, XBlock *blocks, int side, int *loaded)> DB_AllocXBlocks{ nullptr };
// DB_ConvertOffsetToAlias
hook::refs::Ref<void (void** data)> DB_ConvertOffsetToAlias{ nullptr };
// DB_ConvertOffsetToPointer
hook::refs::Ref<void (void** data)> DB_ConvertOffsetToPointer{ nullptr };
// DB_DoesXAssetExist
hook::refs::Ref<bool(XAssetType type, XHash* name)> DB_DoesXAssetExist{ nullptr };
// DB_FileExists
hook::refs::Ref<bool(const char* file)> DB_FileExists{ nullptr };
// DB_FindXAssetHeader
hook::refs::Ref<XAssetHeader(XAssetType type, XHash* name, bool errorIfMissing, int waitTime)> DB_FindXAssetHeader{ nullptr };
// DB_GetOffsetData
hook::refs::Ref<void* (uint64_t ref)> DB_GetOffsetData{ nullptr };
// DB_GetXAssetName
hook::refs::Ref<XHash*(XHash* hash, const XAsset* asset)> DB_GetXAssetName{ nullptr };
// DB_IncStreamPos
hook::refs::Ref<void (size_t size)> DB_IncStreamPos{ nullptr };
// DB_InitStreams
hook::refs::Ref<void (XBlock *blocks)> DB_InitStreams{ nullptr };
// DB_InsertPointer
hook::refs::Ref<const void** ()> DB_InsertPointer{ nullptr };
// DB_Is4KEnabled
hook::refs::Ref<bool()> DB_Is4KEnabled{ nullptr };
// DB_LinkXAssetEntry
hook::refs::Ref<XAssetEntryPoolEntry* (XAsset *newEntry, bool allowOverride)> DB_LinkXAssetEntry{ nullptr };
// DB_LoadXFileData
hook::refs::Ref<void (byte *pos, int size)> DB_LoadXFileData{ nullptr };
// DB_PopStreamPos
hook::refs::Ref<void ()> DB_PopStreamPos{ nullptr };
// DB_PushStreamPos
hook::refs::Ref<void (int index)> DB_PushStreamPos{ nullptr };
// Load_Stream
hook::refs::Ref<bool (bool atStreamStart, void *ptr, size_t size)> Load_Stream{ nullptr };
// Load_XAsset
hook::refs::Ref<void (bool atStreamStart, XAsset *asset)> Load_XAsset{ nullptr };
// Load_XHash
hook::refs::Ref<void (XHash* hash)> Load_XHash{ nullptr };
// Load_XStringCustom
hook::refs::Ref<void (const char** str)> Load_XStringCustom{ nullptr };
// s_assetPools
hook::refs::Ref<XAssetPool> s_assetPools{ nullptr };

// Stream_CloseFile
hook::refs::Ref<void(int32_t fileid)> Stream_CloseFile{ nullptr };
// Stream_OpenFile49
hook::refs::Ref<int32_t(const char* file)> Stream_OpenFile49{ nullptr };

// ScrStr_ConvertToString
hook::refs::Ref<const char*(ScrVarIndex_t index)> ScrStr_ConvertToString{ nullptr };
// ScrVar_NewVariableByIndex
hook::refs::Ref<ScrVarIndex_t(scriptInstance_t inst, ScrVarIndex_t parentId, ScrVarNameIndex_t index)> ScrVar_NewVariableByIndex{ nullptr };
// ScrVar_PushArray
hook::refs::Ref<void(scriptInstance_t inst)> ScrVar_PushArray{ nullptr };
// ScrVar_SetValue
hook::refs::Ref<void(scriptInstance_t inst, ScrVarIndex_t id, ScrVarValue_t* value)> ScrVar_SetValue{ nullptr };
// ScrVm_AddAPIFunction
hook::refs::Ref<void(scriptInstance_t inst, void* func)> ScrVm_AddAPIFunction{ nullptr };
// ScrVm_AddBool
hook::refs::Ref<void(scriptInstance_t inst, int value)> ScrVm_AddBool{ nullptr };
// ScrVm_AddConstString
hook::refs::Ref<void(scriptInstance_t inst, ScrString_t value)> ScrVm_AddConstString{ nullptr };
// ScrVm_AddEntityNum
hook::refs::Ref<void(scriptInstance_t inst, EntRefUnion value, ClassNum classNum, LocalClientNum_t num)> ScrVm_AddEntityNum{ nullptr };
// ScrVm_AddFloat
hook::refs::Ref<void(scriptInstance_t inst, float value)> ScrVm_AddFloat{ nullptr };
// ScrVm_AddHash
hook::refs::Ref<void(scriptInstance_t inst, XHash* value)> ScrVm_AddHash{ nullptr };
// ScrVm_AddInt
hook::refs::Ref<void(scriptInstance_t inst, int64_t value)> ScrVm_AddInt{ nullptr };
// ScrVm_AddScriptFunction
hook::refs::Ref<void(scriptInstance_t inst, byte* codePos)> ScrVm_AddScriptFunction{ nullptr };
// ScrVm_AddString
hook::refs::Ref<void(scriptInstance_t inst, const char *value)> ScrVm_AddString{ nullptr };
// ScrVm_AddStruct
hook::refs::Ref<uint32_t(scriptInstance_t inst)> ScrVm_AddStruct{ nullptr };
// ScrVm_AddToArray
hook::refs::Ref<void(scriptInstance_t inst)> ScrVm_AddToArray{ nullptr };
// ScrVm_AddToArrayStringIndexed
hook::refs::Ref<void(scriptInstance_t inst, XHash* name)> ScrVm_AddToArrayStringIndexed{ nullptr };
// ScrVm_AddUndefined
hook::refs::Ref<void(scriptInstance_t inst)> ScrVm_AddUndefined{ nullptr };
// ScrVm_AddVector
hook::refs::Ref<void(scriptInstance_t inst, vec3_t* vec)> ScrVm_AddVector{ nullptr };
// ScrVm_GetBool
hook::refs::Ref<bool(scriptInstance_t inst, unsigned int index)> ScrVm_GetBool{ nullptr };
// ScrVm_GetConstString
hook::refs::Ref<ScrVarIndex_t(scriptInstance_t inst, unsigned int index)> ScrVm_GetConstString{ nullptr };
// ScrVm_GetEntityRef
hook::refs::Ref<scr_entref_t*(scr_entref_t* ent, scriptInstance_t inst, unsigned int index)> ScrVm_GetEntityRef{ nullptr };
// ScrVm_GetFloat
hook::refs::Ref<float(scriptInstance_t inst, unsigned int index)> ScrVm_GetFloat{ nullptr };
// ScrVm_GetHash
hook::refs::Ref<XHash*(XHash* hash, scriptInstance_t inst, unsigned int index)> ScrVm_GetHash{ nullptr };
// ScrVm_GetInt
hook::refs::Ref<int64_t(scriptInstance_t inst, unsigned int index)> ScrVm_GetInt{ nullptr };
// ScrVm_GetNumParam
hook::refs::Ref<uint32_t(scriptInstance_t inst)> ScrVm_GetNumParam{ nullptr };
// ScrVm_GetPointerType
hook::refs::Ref<ScrVarType_t(scriptInstance_t inst, unsigned int index)> ScrVm_GetPointerType{ nullptr };
// ScrVm_GetString
hook::refs::Ref<const char*(scriptInstance_t inst, unsigned int index)> ScrVm_GetString{ nullptr };
// ScrVm_GetType
hook::refs::Ref<ScrVarType_t(scriptInstance_t inst, unsigned int index)> ScrVm_GetType{ nullptr };
// ScrVm_GetValue
hook::refs::Ref<ScrVarValue_t*(scriptInstance_t inst, unsigned int index)> ScrVm_GetValue{ nullptr };
// ScrVm_GetVector
hook::refs::Ref<void(scriptInstance_t inst, unsigned int index, vec3_t* vector)> ScrVm_GetVector{ nullptr };
// ScrVm_SetStructField
hook::refs::Ref<void(scriptInstance_t inst, uint32_t structId, uint32_t name)> ScrVm_SetStructField{ nullptr };

// CScr_GetFunction
hook::refs::Ref<BuiltinFunction(uint32_t canonId, int* type, int* min_args, int* max_args)> CScr_GetFunction{ nullptr };
// CScr_GetFunctionReverseLookup
hook::refs::Ref<bool(byte* func, uint32_t* name, bool* isFunction)> CScr_GetFunctionReverseLookup{ nullptr };
// CScr_GetMethod
hook::refs::Ref<void*(uint32_t canonId, int* type, int* min_args, int* max_args)> CScr_GetMethod{ nullptr };
// SL_GetStringOfSize
hook::refs::Ref<ScrString_t(const char* str, unsigned int user, ScrStringType type, bool decrypt)> SL_GetStringOfSize{ nullptr };
// SL_TransferRefToUser
hook::refs::Ref<void(ScrString_t stringValue, unsigned int user)> SL_TransferRefToUser{ nullptr };
// ScrEvent_FireCallbackEventEnt
hook::refs::Ref<void(scriptInstance_t inst, uint32_t stringValue, int entnum, bool is_params)> ScrEvent_FireCallbackEventEnt{ nullptr };
// ScrVar_AddClassFields
hook::refs::Ref<void(scriptInstance_t inst, ClassNum classnum, uint32_t canonId, int32_t offset)> ScrVar_AddClassFields{ nullptr };
// ScrVm_Error
hook::refs::Ref<void(uint64_t code, scriptInstance_t inst, char* unused, bool terminal)> ScrVm_Error{ nullptr };
// Scr_ConstructMessageString
hook::refs::Ref<void(scriptInstance_t inst, MessageString* string, signed int startIndex, int endIndex)> Scr_ConstructMessageString{ nullptr };
// Scr_GetFunction
hook::refs::Ref<BuiltinFunction(uint32_t canonId, int* type, int* min_args, int* max_args)> Scr_GetFunction{ nullptr };
// Scr_GetFunctionReverseLookup
hook::refs::Ref<bool(byte* func, uint32_t* name, bool* isFunction)> Scr_GetFunctionReverseLookup{ nullptr };
// Scr_GetGenericField
hook::refs::Ref<void(scriptInstance_t inst, const byte* b, fieldtype_t type, int ofs)> Scr_GetGenericField{ nullptr };
// Scr_GetGscExportInfo
hook::refs::Ref<void(scriptInstance_t inst, byte* codepos, const char** scriptname, int32_t* sloc, int32_t* crc, int32_t* vm)> Scr_GetGscExportInfo{ nullptr };
// Scr_GetMethod
hook::refs::Ref<void*(uint32_t canonId, int* type, int* min_args, int* max_args)> Scr_GetMethod{ nullptr };
// Scr_SetGenericField
hook::refs::Ref<void(scriptInstance_t inst, byte* b, fieldtype_t type, int ofs)> Scr_SetGenericField{ nullptr };

// gObjFileInfo
hook::refs::Ref<objFileInfo_t[scriptInstance_t::SI_COUNT][650]> gObjFileInfo{ nullptr };
// gObjFileInfoCount
hook::refs::Ref<uint32_t> gObjFileInfoCount{ nullptr };
// gVmOpJumpTable
hook::refs::Ref<VM_OP_FUNC> gVmOpJumpTable{ nullptr };
// gVmOpJumpTableError
hook::refs::Ref<VM_OP_ERR_FUNC> gVmOpJumpTableError{ nullptr };
// gVmOpJumpTableErrorModTool
hook::refs::Ref<VM_OP_ERR_FUNC> gVmOpJumpTableErrorModTool{ nullptr };
// gVmOpJumpTableModTool
hook::refs::Ref<VM_OP_FUNC> gVmOpJumpTableModTool{ nullptr };
// scrVarGlob
hook::refs::Ref<scrVarGlob_t> scrVarGlob{ nullptr };
// scrVarPub
hook::refs::Ref<BO4_scrVarPub> scrVarPub{ nullptr };
// scrVarTypeNames
hook::refs::Ref<const char*> scrVarTypeNames{ nullptr };
// scrVmInvalidFuncs
hook::refs::Ref<void*> scrVmInvalidFuncs{ nullptr };
// scrVmPub
hook::refs::Ref<scrVmPub_t> scrVmPub{ nullptr };

// Lua_BeginTableReadOnly
hook::refs::Ref<void(const char* tname, lua_State* luaVM)> Lua_BeginTableReadOnly{ nullptr };
// Lua_CoD_LoadLuaFile
hook::refs::Ref<bool(lua_State* luaVM, const char* file)> Lua_CoD_LoadLuaFile{ nullptr };
// Lua_Cod_RegisterFunction
hook::refs::Ref<void(lua_State* luaVM, XHash* name, int (*func)(lua_State* s))> Lua_Cod_RegisterFunction{ nullptr };
// Lua_EndTableReadOnly
hook::refs::Ref<void(lua_State* luaVM)> Lua_EndTableReadOnly{ nullptr };
// hks_obj_tolhash
hook::refs::Ref<XHash*(XHash* retval, lua_State* luaVM, int idx)> hks_obj_tolhash{ nullptr };
// hks_obj_tolstring
hook::refs::Ref<const char*(lua_State* luaVM, HksObject* obj, size_t* len)> hks_obj_tolstring{ nullptr };
// hks_obj_tonumber
hook::refs::Ref<float(lua_State* luaVM, const HksObject* obj)> hks_obj_tonumber{ nullptr };
// hksi_lua_pushlstring
hook::refs::Ref<void(lua_State* s, const char* str, size_t l)> hksi_lua_pushlstring{ nullptr };
// hksi_lua_pushxhash
hook::refs::Ref<void(lua_State* s, const char* str)> hksi_lua_pushxhash{ nullptr };
// hksi_lua_setfield
hook::refs::Ref<void(lua_State* s, int index, const char* k)> hksi_lua_setfield{ nullptr };

// Cmd_AddCommandInternal
hook::refs::Ref<void(XHash* cmdName, xcommand_t function, cmd_function_t* allocedCmd)> Cmd_AddCommandInternal{ nullptr };
// SEH_GetLanguageNameAbbr
hook::refs::Ref<const char*(int32_t lang)> SEH_GetLanguageNameAbbr{ nullptr };
// SV_SendServerCommand
hook::refs::Ref<void(client_t* cl_0, svscmd_type type, const char* fmt, ...)> SV_SendServerCommand{ nullptr };
// Sys_GetParamSafe
hook::refs::Ref<const char*(int32_t index)> Sys_GetParamSafe{ nullptr };
// Sys_GetTLS
hook::refs::Ref<TLSData*()> Sys_GetTLS{ nullptr };

// AddBaseDrawTextCmd
hook::refs::Ref<void(const char* text, int maxChars, Font* font, float x, float y, float xScale, float yScale, float rotation, const vec_t* color, int style, int cursorPos, char cursor, float padding)> AddBaseDrawTextCmd{ nullptr };
// R_AddCmdBeginView
hook::refs::Ref<void(const void* sceneDef, const void* viewParms)> R_AddCmdBeginView{ nullptr };
// R_AddCmdClearScreen
hook::refs::Ref<void> R_AddCmdClearScreen{ nullptr };
// R_AddCmdDrawEmblemLayer
hook::refs::Ref<void(const void* emblemLayer)> R_AddCmdDrawEmblemLayer{ nullptr };
// R_AddCmdDrawQuadPic
hook::refs::Ref<void(const vec_t* verts, const vec_t* color, Material* material)> R_AddCmdDrawQuadPic{ nullptr };
// R_AddCmdDrawQuadPicW
hook::refs::Ref<void> R_AddCmdDrawQuadPicW{ nullptr };
// R_AddCmdDrawStretchPic
hook::refs::Ref<void(float x, float y, float w, float h, float s0, float t0, float s1, float t1, float* color, Material* material)> R_AddCmdDrawStretchPic{ nullptr };
// R_AddCmdDrawTextInSpace
hook::refs::Ref<void(const char* text, Font* font, const vec_t* org, const vec_t* xPixelStep, const vec_t* color, const vec_t* yPixelStep)> R_AddCmdDrawTextInSpace{ nullptr };
// R_AddCmdDrawUIQuads
hook::refs::Ref<void> R_AddCmdDrawUIQuads{ nullptr };
// R_AddCmdDrawUIQuadsReplaceImage
hook::refs::Ref<void> R_AddCmdDrawUIQuadsReplaceImage{ nullptr };
// R_AddCmdEndOfList
hook::refs::Ref<void()> R_AddCmdEndOfList{ nullptr };
// R_AddCmdProjectionSet2D
hook::refs::Ref<void()> R_AddCmdProjectionSet2D{ nullptr };
// R_AddCmdProjectionSet3D
hook::refs::Ref<void()> R_AddCmdProjectionSet3D{ nullptr };
// R_AddCmdResolveComposite
hook::refs::Ref<void(GfxImage* image, void* callback)> R_AddCmdResolveComposite{ nullptr };
// R_AddCmdSetImageRenderTarget
hook::refs::Ref<void(const GfxImage* rt)> R_AddCmdSetImageRenderTarget{ nullptr };
// R_AddCmdSetScissorValues
hook::refs::Ref<void(bool enabled, int x, int y, int width, int height)> R_AddCmdSetScissorValues{ nullptr };
// R_AddCmdSetUITextureSources
hook::refs::Ref<void(bool forceBlack)> R_AddCmdSetUITextureSources{ nullptr };
// R_AddCmdSetViewportValues
hook::refs::Ref<void(int x, int y, int width, int height)> R_AddCmdSetViewportValues{ nullptr };
// R_TextHeight
hook::refs::Ref<uint32_t(Font* font)> R_TextHeight{ nullptr };
// R_TextWidth
hook::refs::Ref<float(const LocalClientNum_t localClientNum, const char* text, int maxChars, Font* font)> R_TextWidth{ nullptr };
// ScopedCriticalSectionConstructor
hook::refs::Ref<void(ScopedCriticalSection* sec, int32_t s, ScopedCriticalSectionType type)> ScopedCriticalSectionConstructor{ nullptr };
// ScopedCriticalSectionDestructor
hook::refs::Ref<void(ScopedCriticalSection* sec)> ScopedCriticalSectionDestructor{ nullptr };
// ScrPlace_GetView
hook::refs::Ref<const ScreenPlacement*(const LocalClientNum_t localClientNum)> ScrPlace_GetView{ nullptr };
// UI_TextHeight
hook::refs::Ref<uint32_t(Font* font, float scale)> UI_TextHeight{ nullptr };
// UI_TextWidth
hook::refs::Ref<uint32_t(const LocalClientNum_t localClientNum, const char* text, int maxChars, Font* font, float scale)> UI_TextWidth{ nullptr };
// sharedUiInfo
hook::refs::Ref<sharedUiInfo_t> sharedUiInfo{ nullptr };

constinit static hook::generated_scan_runtime::ScanInformation scans[] { 
    {
        .id = "dvar.Dvar_Register",
        .scan = "48 89 5C 24 08 48 89 6C 24 18 48 89 74 24 20 57 41 54 41 55 41 56 41 57 B8 ?? ?? ?? ?? E8 ?? ?? ?? ?? 48 2B E0 48 8B 05 ?? ?? ?? ?? 48 33 C4 48 89 84 24 ?? ?? ?? ?? 4C 8B B4",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&Dvar_Register.ptr
    },
    {
        .id = "dvar.dvar_loc_language",
        .scan = "48 8B 0D ?? ?? ?? ?? 45 33 C0 8B D3 E8 ?? ?? ?? ?? 48 8D 0C 9B 48 8B C3 48 8D 15 ?? ?? ?? ?? 49 C7 C0 FF FF FF FF",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 3,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&dvar_loc_language.ptr
    },
    {
        .id = "dvar.s_dvarHashTable",
        .scan = "48 8D 3D ?? ?? ?? ?? 66 48 0F 7E C0 0F 29 44 24 20 25 FF 03 00 00 48 8B 3C C7 48 85 FF 74 24 48 8B 0E 48 BA FF FF FF FF FF FF FF 7F 48 23 CA",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 3,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&s_dvarHashTable.ptr
    },
    {
        .id = "dvar.s_dvarPool",
        .scan = "48 8D 35 ?? ?? ?? ?? 4C 89 74 24 48 48 8B 2E 8B 4D 24 8B C1 C1 E8 0F A8 01",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 3,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&s_dvarPool.ptr
    },
    {
        .id = "fastfile.DB_AllocStreamPos",
        .scan = "E8 ?? ?? ?? ?? 48 89 47 18 48 8B CF",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 1,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&DB_AllocStreamPos.ptr
    },
    {
        .id = "fastfile.DB_AllocXBlocks",
        .scan = "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 57 41 54 41 55 41 56 41 57 48 83 EC 50 4C 8B",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&DB_AllocXBlocks.ptr
    },
    {
        .id = "fastfile.DB_ConvertOffsetToAlias",
        .scan = "4C 8B 01 49 FF C8 49 8B C0 48 C1 E8 3C 48 8D 14 40 48 B8 FF FF FF FF FF FF FF 0F 4C 23 C0 48 8B 05 ?? ?? ?? ?? 48",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&DB_ConvertOffsetToAlias.ptr
    },
    {
        .id = "fastfile.DB_ConvertOffsetToPointer",
        .scan = "E8 ?? ?? ?? ?? 48 8D 4B 18 E8 ?? ?? ?? ?? 45 33 F6 48 8D 7B 38 33 C9",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 1,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&DB_ConvertOffsetToPointer.ptr
    },
    {
        .id = "fastfile.DB_DoesXAssetExist",
        .scan = "40 53 48 83 EC 30 0F 10 02 48 8D 54 24 20 0F B6",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&DB_DoesXAssetExist.ptr
    },
    {
        .id = "fastfile.DB_FileExists",
        .scan = "40 53 48 81 EC 40 01 00 00 48 8B 05 ?? ?? ?? ?? 48 33 C4 48 89 84 24 30 01 00 00 48 8B D9 E8",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&DB_FileExists.ptr
    },
    {
        .id = "fastfile.DB_FindXAssetHeader",
        .scan = "E8 ?? ?? ?? ?? 48 85 C0 75 1B 48 8B CB E8",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 1,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&DB_FindXAssetHeader.ptr
    },
    {
        .id = "fastfile.DB_GetOffsetData",
        .scan = "E8 ?? ?? ?? ?? 48 89 44 24 28 0F 10 44 24 20 0F 11 46 20 33 C9",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 1,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&DB_GetOffsetData.ptr
    },
    {
        .id = "fastfile.DB_GetXAssetName",
        .scan = "40 53 48 83 EC 30 0F B6 02",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&DB_GetXAssetName.ptr
    },
    {
        .id = "fastfile.DB_IncStreamPos",
        .scan = "E8 ?? ?? ?? ?? 0F B6 C3 48 83 C4 20 5B C3 B0 01",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 1,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&DB_IncStreamPos.ptr
    },
    {
        .id = "fastfile.DB_InitStreams",
        .scan = "33 D2 48 89 0D ?? ?? ?? ?? 48",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&DB_InitStreams.ptr
    },
    {
        .id = "fastfile.DB_InsertPointer",
        .scan = "48 89 5C 24 08 48 63 15",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&DB_InsertPointer.ptr
    },
    {
        .id = "fastfile.DB_Is4KEnabled",
        .scan = "E8 ?? ?? ?? ?? 33 D2 88 44 24 31",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 1,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&DB_Is4KEnabled.ptr
    },
    {
        .id = "fastfile.DB_LinkXAssetEntry",
        .scan = "E8 ?? ?? ?? ?? 48 8B 50 08 48 89 13",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 1,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&DB_LinkXAssetEntry.ptr
    },
    {
        .id = "fastfile.DB_LoadXFileData",
        .scan = "85 D2 0F 8E 56 01 00 00 41 54 41 56 48 83 EC 38 48 89 5C 24",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&DB_LoadXFileData.ptr
    },
    {
        .id = "fastfile.DB_PopStreamPos",
        .scan = "E8 ?? ?? ?? ?? 8B 05 ?? ?? ?? ?? FF C8 89 05 ?? ?? ?? ?? F6 05",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 1,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&DB_PopStreamPos.ptr
    },
    {
        .id = "fastfile.DB_PushStreamPos",
        .scan = "E8 ?? ?? ?? ?? 48 8B 7C 24 60 48 8B D7 33 C9 E8 ?? ?? ?? ?? E8",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 1,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&DB_PushStreamPos.ptr
    },
    {
        .id = "fastfile.Load_Stream",
        .scan = "E8 ?? ?? ?? ?? 8B FE 45 85 FF 7E 22",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 1,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&Load_Stream.ptr
    },
    {
        .id = "fastfile.Load_XAsset",
        .scan = "E8 ?? ?? ?? ?? 48 83 C3 10 80 3D ?? ?? ?? ?? ?? 75 07",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 1,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&Load_XAsset.ptr
    },
    {
        .id = "fastfile.Load_XHash",
        .scan = "E8 ?? ?? ?? ?? 48 8B CE E8 ?? ?? ?? ?? 48 83 7E 10 00 74 1F B9 1F 00 00 00",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 9,
        .postOffset = 0,
        .single = false,
        .ref = (void**)&Load_XHash.ptr
    },
    {
        .id = "fastfile.Load_XStringCustom",
        .scan = "E8 ?? ?? ?? ?? EB 09 48 8D 4F 48 E8 ?? ?? ?? ?? 33 C9",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 1,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&Load_XStringCustom.ptr
    },
    {
        .id = "fastfile.s_assetPools",
        .scan = "48 89 15 ?? ?? ?? ?? 89 35 ?? ?? ?? ?? C7 05 ?? ?? ?? ?? ?? ?? ?? ?? 48 8D 8A F0 00 00 00 44 88 3D ?? ?? ?? ?? 44 89 3D ?? ?? ?? ?? 44 8D 46 11 48 89 15",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 3,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&s_assetPools.ptr
    },
    {
        .id = "fs.Stream_CloseFile",
        .scan = "40 53 48 83 EC 40 48 C7 44 24 20 FE FF FF FF 48 63 D9 83",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&Stream_CloseFile.ptr
    },
    {
        .id = "fs.Stream_OpenFile49",
        .scan = "E8 ?? ?? ?? ?? 44 8B F8 83 F8 FF 75 6E",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 1,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&Stream_OpenFile49.ptr
    },
    {
        .id = "gsc.ScrStr_ConvertToString",
        .scan = "B8 ?? ?? ?? ?? E8 ?? ?? ?? ?? 48 2B E0 48 8B 05 ?? ?? ?? ?? 48 33 C4 48 89 84 24 ?? ?? ?? ?? 8D 41 FF 3D ?? ?? ?? ?? 77 67",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&ScrStr_ConvertToString.ptr
    },
    {
        .id = "gsc.ScrVar_NewVariableByIndex",
        .scan = "48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 20 48 63 F1 44 8B CA 8B FA 8B CE BA 01",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&ScrVar_NewVariableByIndex.ptr
    },
    {
        .id = "gsc.ScrVar_PushArray",
        .scan = "E8 ?? ?? ?? ?? 44 39 74 24 28",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 1,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&ScrVar_PushArray.ptr
    },
    {
        .id = "gsc.ScrVar_SetValue",
        .scan = "48 89 5C 24 18 48 89 6C 24 20 57 41 56 41 57 48 83 EC 30",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&ScrVar_SetValue.ptr
    },
    {
        .id = "gsc.ScrVm_AddAPIFunction",
        .scan = "48 89 5C 24 08 57 48 83 EC 20 48 63 D9 48 8B FA 8B CB E8 ?? ?? ?? ?? 48 69 CB ?? ?? ?? ?? 48 8B 5C 24 30 48 8D 15 ?? ?? ?? ?? 48 8B 04 11 C7 40 08 0B",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&ScrVm_AddAPIFunction.ptr
    },
    {
        .id = "gsc.ScrVm_AddBool",
        .scan = "48 89 5C 24 08 57 48 83 EC 20 48 63 D9 8B CB 48",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&ScrVm_AddBool.ptr
    },
    {
        .id = "gsc.ScrVm_AddConstString",
        .scan = "E8 ?? ?? ?? ?? 48 B8 F3 A4 48 44 19 AB D7 56",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 1,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&ScrVm_AddConstString.ptr
    },
    {
        .id = "gsc.ScrVm_AddEntityNum",
        .scan = "E8 ?? ?? ?? ?? E9 CE 41 00 00",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 1,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&ScrVm_AddEntityNum.ptr
    },
    {
        .id = "gsc.ScrVm_AddFloat",
        .scan = "40 53 48 83 EC 30 48 63 D9 8B",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&ScrVm_AddFloat.ptr
    },
    {
        .id = "gsc.ScrVm_AddHash",
        .scan = "48 89 5C 24 08 57 48 83 EC 20 48 63 D9 48 8B FA 8B CB E8 ?? ?? ?? ?? 48 8B 0F",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&ScrVm_AddHash.ptr
    },
    {
        .id = "gsc.ScrVm_AddInt",
        .scan = "0F 84 ?? ?? ?? ?? 85 C9 74 0D",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 2,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&ScrVm_AddInt.ptr
    },
    {
        .id = "gsc.ScrVm_AddScriptFunction",
        .scan = "48 89 5C 24 08 57 48 83 EC 20 48 63 D9 48 8B FA 8B CB E8 ?? ?? ?? ?? 48 69 CB ?? ?? ?? ?? 48 8B 5C 24 30 48 8D 15 ?? ?? ?? ?? 48 8B 04 11 C7 40 08 0C",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&ScrVm_AddScriptFunction.ptr
    },
    {
        .id = "gsc.ScrVm_AddString",
        .scan = "48 89 5C 24 08 57 48 83 EC 20 48 63 D9 48 8B FA 8B CB E8 ?? ?? ?? ?? 48 69 DB",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&ScrVm_AddString.ptr
    },
    {
        .id = "gsc.ScrVm_AddStruct",
        .scan = "48 89 5C 24 08 57 48 83 EC 20 48 63 F9 8B CF E8 ?? ?? ?? ?? 8B",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&ScrVm_AddStruct.ptr
    },
    {
        .id = "gsc.ScrVm_AddToArray",
        .scan = "E8 ?? ?? ?? ?? FF C7 3B 7D 20",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 1,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&ScrVm_AddToArray.ptr
    },
    {
        .id = "gsc.ScrVm_AddToArrayStringIndexed",
        .scan = "E8 ?? ?? ?? ?? 8B 4C 1C 68",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 1,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&ScrVm_AddToArrayStringIndexed.ptr
    },
    {
        .id = "gsc.ScrVm_AddUndefined",
        .scan = "40 53 48 83 EC 20 48 63 D9 8B CB E8 ?? ?? ?? ?? 48 69",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&ScrVm_AddUndefined.ptr
    },
    {
        .id = "gsc.ScrVm_AddVector",
        .scan = "40 57 48 83 EC 40 48 8B 05 ?? ?? ?? ?? 48 33 C4 48 89 44 24 38",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&ScrVm_AddVector.ptr
    },
    {
        .id = "gsc.ScrVm_GetBool",
        .scan = "48 89 5C 24 10 48 89 74 24 18 57 48 81 EC B0 00 00 00 48 8B 05 ?? ?? ?? ?? 48 33 C4 48 89 84 24 A8 00 00 00 48 63 D9 48 8D 35 22",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&ScrVm_GetBool.ptr
    },
    {
        .id = "gsc.ScrVm_GetConstString",
        .scan = "48 89 5C 24 18 55 56 57 48 81 EC B0 00 00 00 48 8B 05 ?? ?? ?? ?? 48 33 C4 48 89 84 24 A8 00 00 00 48 63 D9 48 8D 2D C5",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&ScrVm_GetConstString.ptr
    },
    {
        .id = "gsc.ScrVm_GetEntityRef",
        .scan = "48 89 5C 24 08 55 56 57 41 56 41 57 48 81 EC C0 00 00 00 48 8B 05 ?? ?? ?? ?? 48 33 C4 48 89 84 24 B8 00 00 00 48 63 DA",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&ScrVm_GetEntityRef.ptr
    },
    {
        .id = "gsc.ScrVm_GetFloat",
        .scan = "48 89 5C 24 18 55 57 41 56 48 81 EC B0 00 00 00 48 8B 05 ?? ?? ?? ?? 48 33 C4 48 89 84 24 A8 00 00 00 48 63 D9 48",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&ScrVm_GetFloat.ptr
    },
    {
        .id = "gsc.ScrVm_GetHash",
        .scan = "48 89 5C 24 08 55 56 57 41 56 41 57 48 81 EC C0 00 00 00 48 8B 05 ?? ?? ?? ?? 48 33 C4 48 89 84 24 B8 00 00 00 48 63 FA",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&ScrVm_GetHash.ptr
    },
    {
        .id = "gsc.ScrVm_GetInt",
        .scan = "48 89 5C 24 18 55 57 41 56 48 81 EC B0 00 00 00 48 8B 05 ?? ?? ?? ?? 48 33 C4 48 89 84 24 A8 00 00 00 48 63 D9 4C 8D 35 84",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&ScrVm_GetInt.ptr
    },
    {
        .id = "gsc.ScrVm_GetNumParam",
        .scan = "E8 ?? ?? ?? ?? 3B C5 76 0E",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 1,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&ScrVm_GetNumParam.ptr
    },
    {
        .id = "gsc.ScrVm_GetPointerType",
        .scan = "48 89 5C 24 20 55 57 41 56 48 81 EC B0",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&ScrVm_GetPointerType.ptr
    },
    {
        .id = "gsc.ScrVm_GetString",
        .scan = "E8 ?? ?? ?? ?? B9 26 00 00 00",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 1,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&ScrVm_GetString.ptr
    },
    {
        .id = "gsc.ScrVm_GetType",
        .scan = "48 89 5C 24 10 48 89 74 24 18 57 48 81 EC B0 00 00 00 48 8B 05 ?? ?? ?? ?? 48 33 C4 48 89 84 24 A8 00 00 00 48 63 D9 48 8D 35 B2",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&ScrVm_GetType.ptr
    },
    {
        .id = "gsc.ScrVm_GetValue",
        .scan = "48 89 5C 24 10 48 89 74 24 18 57 48 81 EC B0 00 00 00 48 8B 05 ?? ?? ?? ?? 48 33 C4 48 89 84 24 A8 00 00 00 48 63 D9 48 8D 35 72",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&ScrVm_GetValue.ptr
    },
    {
        .id = "gsc.ScrVm_GetVector",
        .scan = "40 53 55 57 48 81 EC B0",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&ScrVm_GetVector.ptr
    },
    {
        .id = "gsc.ScrVm_SetStructField",
        .scan = "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 57 48 83 EC 20 48 63 F1 8B CE E8 ?? ?? ?? ?? 48",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&ScrVm_SetStructField.ptr
    },
    {
        .id = "gscfuncs.CScr_GetFunction",
        .scan = "48 89 5C 24 08 48 89 74 24 10 48 89 7C 24 18 41 56 48 83 EC 20 4C 8B F2 8B D9 48 8D 15 ?? ?? ?? ?? 49 8B F9 48 8B CA 49 8B F0 33 C0 0F 1F 40 00 3B 19 0F 84 EA 00 00 00 FF C0 48 83 C1 20 3D 5F",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&CScr_GetFunction.ptr
    },
    {
        .id = "gscfuncs.CScr_GetFunctionReverseLookup",
        .scan = "48 89 5C 24 10 48 89 74 24 18 57 48 83 EC 20 49 8B F8 48 8B F2 48 8B D9 48 85 D2 0F 84 9B",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&CScr_GetFunctionReverseLookup.ptr
    },
    {
        .id = "gscfuncs.CScr_GetMethod",
        .scan = "48 89 5C 24 08 48 89 74 24 10 48 89 7C 24 18 41 56 48 83 EC 20 4C 8B F2 8B D9 48 8D 15 ?? ?? ?? ?? 49 8B F9 48 8B CA 49 8B F0 33 C0 0F 1F 40 00 3B 19 0F 84 EA 00 00 00 FF C0 48 83 C1 20 3D 45",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&CScr_GetMethod.ptr
    },
    {
        .id = "gscfuncs.SL_GetStringOfSize",
        .scan = "40 55 56 57 41 54 41 55 41 56 41 57 B8 ?? ?? ?? ?? E8 ?? ?? ?? ?? 48 2B E0 48 C7 44 24 20 FE FF FF FF 48 89 9C 24 ?? ?? ?? ?? 48 8B 05 ?? ?? ?? ?? 48 33 C4 48 89 84 24 ?? ?? ?? ?? 45 0F B6 F9 45 8B E8",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&SL_GetStringOfSize.ptr
    },
    {
        .id = "gscfuncs.SL_TransferRefToUser",
        .scan = "8D 0C 89 C1 E1 02 48 03 0D ?? ?? ?? ?? 0F B6 41 02 22 C2 A8 3F 74",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&SL_TransferRefToUser.ptr
    },
    {
        .id = "gscfuncs.ScrEvent_FireCallbackEventEnt",
        .scan = "40 53 55 56 57 41 54 41 55 41 56 41 57 48 81 EC 68 02 00 00 48 C7 44 24 40 FE FF FF FF 48 8B 05 ?? ?? ?? ?? 48 33 C4 48 89 84 24 50 02 00 00 4D 63 E9 49",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&ScrEvent_FireCallbackEventEnt.ptr
    },
    {
        .id = "gscfuncs.ScrVar_AddClassFields",
        .scan = "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 57 41 56 41 57 48 83 EC 20 48 63 F1 4C",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&ScrVar_AddClassFields.ptr
    },
    {
        .id = "gscfuncs.ScrVm_Error",
        .scan = "48 89 5C 24 20 55 56 57 48 81 EC B0 00 00 00 48",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&ScrVm_Error.ptr
    },
    {
        .id = "gscfuncs.Scr_ConstructMessageString",
        .scan = "40 53 55 57 41 56 41 57 48 81 EC A0",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&Scr_ConstructMessageString.ptr
    },
    {
        .id = "gscfuncs.Scr_GetFunction",
        .scan = "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 57 48 83 EC 20 49 8B F8 C7",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&Scr_GetFunction.ptr
    },
    {
        .id = "gscfuncs.Scr_GetFunctionReverseLookup",
        .scan = "48 89 5C 24 10 48 89 74 24 18 57 48 83 EC 20 49 8B F8 48 8B F2 48 8B D9 48 85 D2 0F 84 9F",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&Scr_GetFunctionReverseLookup.ptr
    },
    {
        .id = "gscfuncs.Scr_GetGenericField",
        .scan = "41 83 F8 18 0F 87 F1 01 00 00 48 89",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&Scr_GetGenericField.ptr
    },
    {
        .id = "gscfuncs.Scr_GetGscExportInfo",
        .scan = "48 89 5C 24 08 48 89 74 24 10 48 89 7C 24 18 4C 89 74 24 20 41 57 48 83 EC 30 4D 8B F8",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&Scr_GetGscExportInfo.ptr
    },
    {
        .id = "gscfuncs.Scr_GetMethod",
        .scan = "48 89 5C 24 08 48 89 6C 24 18 56 57 41 56 48 83 EC 30 49 8B F1",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&Scr_GetMethod.ptr
    },
    {
        .id = "gscfuncs.Scr_SetGenericField",
        .scan = "41 83 F8 16 0F 87 4C 01 00 00 48 89",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&Scr_SetGenericField.ptr
    },
    {
        .id = "gscstrucs.gObjFileInfo",
        .scan = "48 8D 05 ?? ?? ?? ?? 48 69 CB ?? ?? ?? ?? 33 D2 41 B8 ?? ?? ?? ?? 48 03 C8 E8 ?? ?? ?? ?? 33 D2 44 8D 47 58 48 8D 0D",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 3,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&gObjFileInfo.ptr
    },
    {
        .id = "gscstrucs.gObjFileInfoCount",
        .scan = "48 8D 0D ?? ?? ?? ?? 33 FF 89 3C 99 48 8D 05 ?? ?? ?? ?? 48 69 CB ?? ?? ?? ?? 33 D2 41 B8 ?? ?? ?? ?? 48 03 C8 E8 ?? ?? ?? ?? 33 D2",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 3,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&gObjFileInfoCount.ptr
    },
    {
        .id = "gscstrucs.gVmOpJumpTable",
        .scan = "41 FF 94 C5 ?? ?? ?? ?? 80 7C 24 20 00 0F 84 30 FF FF FF 48 8B 4C 24 38 48 69 D6",
        .type = hook::generated_scan_runtime::ST_GETOFFSET32,
        .offset = 4,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&gVmOpJumpTable.ptr
    },
    {
        .id = "gscstrucs.gVmOpJumpTableError",
        .scan = "41 FF 94 C5 ?? ?? ?? ?? 33 FF E9 F7 FE FF FF 80 7C 24 20 00 48 8B 5C 24 30 48 63 74 24 28",
        .type = hook::generated_scan_runtime::ST_GETOFFSET32,
        .offset = 4,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&gVmOpJumpTableError.ptr
    },
    {
        .id = "gscstrucs.gVmOpJumpTableErrorModTool",
        .scan = "41 FF 94 C5 ?? ?? ?? ?? 33 FF E9 06 FF FF FF 41 FF 94 C5 ?? ?? ?? ?? 33 FF E9 F7 FE FF FF 80 7C 24 20 00",
        .type = hook::generated_scan_runtime::ST_GETOFFSET32,
        .offset = 4,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&gVmOpJumpTableErrorModTool.ptr
    },
    {
        .id = "gscstrucs.gVmOpJumpTableModTool",
        .scan = "41 FF 94 C5 ?? ?? ?? ?? EB 08 41 FF 94 C5 ?? ?? ?? ?? 80 7C 24 20 00 0F 84 30 FF FF FF",
        .type = hook::generated_scan_runtime::ST_GETOFFSET32,
        .offset = 4,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&gVmOpJumpTableModTool.ptr
    },
    {
        .id = "gscstrucs.scrVarGlob",
        .scan = "48 8D 1D ?? ?? ?? ?? 48 03 D2 49 8B 4C 19 20 45 33 DB C7 44 D1 08 15 00 00 00 49 8B 4C 19 20",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 3,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&scrVarGlob.ptr
    },
    {
        .id = "gscstrucs.scrVarPub",
        .scan = "4C 8D 05 ?? ?? ?? ?? 48 63 C1 48 69 C8 10 01 00 00 42 8B 84 01 F8 00 00 00 89 02",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 3,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&scrVarPub.ptr
    },
    {
        .id = "gscstrucs.scrVarTypeNames",
        .scan = "49 8B 94 C6 ?? ?? ?? ?? 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? 48 8B C8 48 69 C6 10 01 00 00",
        .type = hook::generated_scan_runtime::ST_GETOFFSET32,
        .offset = 4,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&scrVarTypeNames.ptr
    },
    {
        .id = "gscstrucs.scrVmInvalidFuncs",
        .scan = "48 0F 44 05 ?? ?? ?? ?? 48 8B 5C 24 40 48 8B 6C 24 48 48 8B 74 24 50 48 8B 7C 24 58 48 83 C4 30 41 5E C3",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 4,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&scrVmInvalidFuncs.ptr
    },
    {
        .id = "gscstrucs.scrVmPub",
        .scan = "48 8D 15 ?? ?? ?? ?? 66 89 70 08 48 89 38 48 01 8C 2A ?? ?? ?? ?? 48 63 CE 48 8D 59 02 48 8D 1C D8",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 3,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&scrVmPub.ptr
    },
    {
        .id = "lua.Lua_BeginTableReadOnly",
        .scan = "E8 ?? ?? ?? ?? 48 8B 83 A0 00 00 00 48 85 C0 74 04 8B 38",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 1,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&Lua_BeginTableReadOnly.ptr
    },
    {
        .id = "lua.Lua_CoD_LoadLuaFile",
        .scan = "48 8B C4 57 48 81 EC 80 00 00 00 48 C7 40 98 FE FF FF FF 48 89 58 08 48 89 70",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&Lua_CoD_LoadLuaFile.ptr
    },
    {
        .id = "lua.Lua_Cod_RegisterFunction",
        .scan = "40 53 48 83 EC 30 4C 8B 49 48 48 8B D9 48 8B 02 4D ",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&Lua_Cod_RegisterFunction.ptr
    },
    {
        .id = "lua.Lua_EndTableReadOnly",
        .scan = "40 53 48 83 EC 20 48 8D 15 ?? ?? ?? ?? 48 8B D9 E8 ?? ?? ?? ?? 48 8B 53 48 48 8D 42 E0 48 3B 43 50 72 18 4C 8D 42 F0 48 8B CB 48 8B D0 E8 ?? ?? ?? ?? 48 83 43 48 F0 48 8B 53 48 4C 8D 4A F0 48 8B CB 4C 8D 42 E0 48 83 C2 D0 E8 ?? ?? ?? ?? 48 83 43 48 E0 4C",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&Lua_EndTableReadOnly.ptr
    },
    {
        .id = "lua.hks_obj_tolhash",
        .scan = "48 83 EC 18 4C 8B D1 41",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&hks_obj_tolhash.ptr
    },
    {
        .id = "lua.hks_obj_tolstring",
        .scan = "40 53 57 41 56 48 81 EC 50 01 00 00 48 8B 05 ?? ?? ?? ?? 48 33",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&hks_obj_tolstring.ptr
    },
    {
        .id = "lua.hks_obj_tonumber",
        .scan = "48 83 EC 28 8B 02 83 E0 0F 83 F8 03 75 0A F3",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&hks_obj_tonumber.ptr
    },
    {
        .id = "lua.hksi_lua_pushlstring",
        .scan = "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 57 48 83 EC 40 BF",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&hksi_lua_pushlstring.ptr
    },
    {
        .id = "lua.hksi_lua_pushxhash",
        .scan = "48 83 EC 08 4C 8B CA 4C 8B D1 49 BB FF FF FF",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&hksi_lua_pushxhash.ptr
    },
    {
        .id = "lua.hksi_lua_setfield",
        .scan = "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 57 48 83 EC 20 48 8B D9 49 8B F0",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&hksi_lua_setfield.ptr
    },
    {
        .id = "system.Cmd_AddCommandInternal",
        .scan = "48 83 EC 18 0F 10 01 48 8B 05 ?? ?? ?? ?? 0F 29 04 24 48 85 C0 74 2D 4C 8B 0C 24 49 BB",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&Cmd_AddCommandInternal.ptr
    },
    {
        .id = "system.SEH_GetLanguageNameAbbr",
        .scan = "E8 ?? ?? ?? ?? 8D 53 2F",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 1,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&SEH_GetLanguageNameAbbr.ptr
    },
    {
        .id = "system.SV_SendServerCommand",
        .scan = "4C 89 44 24 18 4C 89 4C 24 20 53 56 48 83 EC 28",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&SV_SendServerCommand.ptr
    },
    {
        .id = "system.Sys_GetParamSafe",
        .scan = "40 53 48 83 EC 20 48 63 D9 E8 ?? ?? ?? ?? 48 8B 40",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&Sys_GetParamSafe.ptr
    },
    {
        .id = "system.Sys_GetTLS",
        .scan = "8B 0D ?? ?? ?? ?? 65 48 8B 04 25 58 00 00 00 BA 28",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&Sys_GetTLS.ptr
    },
    {
        .id = "ui.AddBaseDrawTextCmd",
        .scan = "48 89 6C 24 20 41 54 41 56 41 57 48 83 EC 30 80",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&AddBaseDrawTextCmd.ptr
    },
    {
        .id = "ui.R_AddCmdBeginView",
        .scan = "48 89 5C 24 08 57 48 83 EC 20 48 8B FA 48 8B D9 BA 08 00 00 00 44 8D 42 20",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&R_AddCmdBeginView.ptr
    },
    {
        .id = "ui.R_AddCmdClearScreen",
        .scan = "48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 30 48 8B F2 0F",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&R_AddCmdClearScreen.ptr
    },
    {
        .id = "ui.R_AddCmdDrawEmblemLayer",
        .scan = "40 53 48 83 EC 20 BA 08 00 00 00 48 8B D9 41",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&R_AddCmdDrawEmblemLayer.ptr
    },
    {
        .id = "ui.R_AddCmdDrawQuadPic",
        .scan = "48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 20 48 8B F2 49 8B F8 BA",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&R_AddCmdDrawQuadPic.ptr
    },
    {
        .id = "ui.R_AddCmdDrawQuadPicW",
        .scan = "48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 30 BA 08",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&R_AddCmdDrawQuadPicW.ptr
    },
    {
        .id = "ui.R_AddCmdDrawStretchPic",
        .scan = "40 53 48 83 EC 60 48 8B 84",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&R_AddCmdDrawStretchPic.ptr
    },
    {
        .id = "ui.R_AddCmdDrawTextInSpace",
        .scan = "48 89 6C 24 18 57 41 56 41 57 48 83 EC 20 80 39",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&R_AddCmdDrawTextInSpace.ptr
    },
    {
        .id = "ui.R_AddCmdDrawUIQuads",
        .scan = "4C 89 4C 24 20 4C 89 44 24 18 53 57 41 57",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&R_AddCmdDrawUIQuads.ptr
    },
    {
        .id = "ui.R_AddCmdDrawUIQuadsReplaceImage",
        .scan = "4C 89 4C 24 20 48 89 54 24 10 53 57 41",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&R_AddCmdDrawUIQuadsReplaceImage.ptr
    },
    {
        .id = "ui.R_AddCmdEndOfList",
        .scan = "E8 ?? ?? ?? ?? BA 02 00 00 00 EB 1C",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 1,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&R_AddCmdEndOfList.ptr
    },
    {
        .id = "ui.R_AddCmdProjectionSet2D",
        .scan = "48 83 EC 28 BA 04 00 00 00 44 8D 42 08 8D 4A 10 E8 ?? ?? ?? ?? 48 85 C0 74 07 C7 40 08 00",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&R_AddCmdProjectionSet2D.ptr
    },
    {
        .id = "ui.R_AddCmdProjectionSet3D",
        .scan = "48 83 EC 28 BA 04 00 00 00 44 8D 42 08 8D 4A 10 E8 ?? ?? ?? ?? 48 85 C0 74 07 C7 40 08 01",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&R_AddCmdProjectionSet3D.ptr
    },
    {
        .id = "ui.R_AddCmdResolveComposite",
        .scan = "48 89 5C 24 08 57 48 83 EC 20 48 8B FA 48 8B D9 BA 08 00 00 00 44 8D 42 10",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&R_AddCmdResolveComposite.ptr
    },
    {
        .id = "ui.R_AddCmdSetImageRenderTarget",
        .scan = "40 53 48 83 EC 20 BA 08 00 00 00 48 8B D9 44",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&R_AddCmdSetImageRenderTarget.ptr
    },
    {
        .id = "ui.R_AddCmdSetScissorValues",
        .scan = "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 57 48 83 EC 20 0F B6 FA",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&R_AddCmdSetScissorValues.ptr
    },
    {
        .id = "ui.R_AddCmdSetUITextureSources",
        .scan = "40 53 48 83 EC 20 BA 04 00 00 00 0F",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&R_AddCmdSetUITextureSources.ptr
    },
    {
        .id = "ui.R_AddCmdSetViewportValues",
        .scan = "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 57 48 83 EC 20 8B FA 41 8B F0",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&R_AddCmdSetViewportValues.ptr
    },
    {
        .id = "ui.R_TextHeight",
        .scan = "E8 ?? ?? ?? ?? F3 0F 10 0D ?? ?? ?? ?? 44 8B C0",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 1,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&R_TextHeight.ptr
    },
    {
        .id = "ui.R_TextWidth",
        .scan = "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 57 48 83 EC 30 8B E9 49 8B D9 49 8B C9",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&R_TextWidth.ptr
    },
    {
        .id = "ui.ScopedCriticalSectionConstructor",
        .scan = "40 53 48 83 EC 20 89 11 48 8B D9 C6",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&ScopedCriticalSectionConstructor.ptr
    },
    {
        .id = "ui.ScopedCriticalSectionDestructor",
        .scan = "40 57 48 83 EC 30 48 C7 44 24 20 FE FF FF FF 48 89 5C 24 40 48 8B D9 8B",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&ScopedCriticalSectionDestructor.ptr
    },
    {
        .id = "ui.ScrPlace_GetView",
        .scan = "E8 ?? ?? ?? ?? 48 69 F5",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 1,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&ScrPlace_GetView.ptr
    },
    {
        .id = "ui.UI_TextHeight",
        .scan = "40 53 48 83 EC 30 0F 29 74 24 20 48 8B D9 E8 ?? ?? ?? ?? 48 8B CB",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&UI_TextHeight.ptr
    },
    {
        .id = "ui.UI_TextWidth",
        .scan = "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 57 48 83 EC 30 F3 0F 10 4C",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&UI_TextWidth.ptr
    },
    {
        .id = "ui.sharedUiInfo",
        .scan = "48 89 05 ?? ?? ?? ?? 48 8D 4D F0 48 B8 8E 4C 9E 0F 27 52 F4 5D B2 01 48 89 45 F0 0F 28 45 F0 66 0F 7F 45 F0",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 3,
        .postOffset = 0,
        .single = true,
        .ref = (void**)&sharedUiInfo.ptr
    },
};

void LoadScans(hook::scan_container::ScanContainer& scan) {
    hook::generated_scan_runtime::LoadScans(scan, scans, ACTS_ARRAYSIZE(scans));
}
