#pragma once

namespace tool::mw22 {
    enum IW9HashAssetType : uint32_t {
        IW9H_ASSET_PHYSICSLIBRARY = hash::HashX32("physicslibrary"),
        IW9H_ASSET_PHYSICSSFXEVENTASSET = hash::HashX32("physicssfxeventasset"),
        IW9H_ASSET_PHYSICSVFXEVENTASSET = hash::HashX32("physicsvfxeventasset"),
        IW9H_ASSET_PHYSICSASSET = hash::HashX32("physicsasset"),
        IW9H_ASSET_PHYSICSFXPIPELINE = hash::HashX32("physicsfxpipeline"),
        IW9H_ASSET_PHYSICSFXSHAPE = hash::HashX32("physicsfxshape"),
        IW9H_ASSET_PHYSICSDEBUGDATA = hash::HashX32("physicsdebugdata"),
        IW9H_ASSET_XANIM = hash::HashX32("xanim"),
        IW9H_ASSET_XMODELSURFS = hash::HashX32("xmodelsurfs"),
        IW9H_ASSET_XMODEL = hash::HashX32("xmodel"),
        IW9H_ASSET_MAYHEM = hash::HashX32("mayhem"),
        IW9H_ASSET_MATERIAL = hash::HashX32("material"),
        IW9H_ASSET_COMPUTESHADER = hash::HashX32("computeshader"),
        IW9H_ASSET_LIBSHADER = hash::HashX32("libshader"),
        IW9H_ASSET_VERTEXSHADER = hash::HashX32("vertexshader"),
        IW9H_ASSET_HULLSHADER = hash::HashX32("hullshader"),
        IW9H_ASSET_DOMAINSHADER = hash::HashX32("domainshader"),
        IW9H_ASSET_PIXELSHADER = hash::HashX32("pixelshader"),
        IW9H_ASSET_TECHSET = hash::HashX32("techset"),
        IW9H_ASSET_IMAGE = hash::HashX32("image"),
        IW9H_ASSET_SOUNDGLOBALVOLMOD = hash::HashX32("soundglobalvolmod"),
        IW9H_ASSET_SOUNDGLOBALENTCHANNEL = hash::HashX32("soundglobalentchannel"),
        IW9H_ASSET_SOUNDGLOBALCONTEXT = hash::HashX32("soundglobalcontext"),
        IW9H_ASSET_SOUNDGLOBALMASTER = hash::HashX32("soundglobalmaster"),
        IW9H_ASSET_SOUNDGLOBALWHIZBY = hash::HashX32("soundglobalwhizby"),
        IW9H_ASSET_SOUNDGLOBALBULLETCRACK = hash::HashX32("soundglobalbulletcrack"),
        IW9H_ASSET_SOUNDGLOBALPERK = hash::HashX32("soundglobalperk"),
        IW9H_ASSET_SOUNDGLOBALOCCLUSION = hash::HashX32("soundglobalocclusion"),
        IW9H_ASSET_SOUNDGLOBALSURFACEINFO = hash::HashX32("soundglobalsurfaceinfo"),
        IW9H_ASSET_SOUNDGLOBALCURVE = hash::HashX32("soundglobalcurve"),
        IW9H_ASSET_SOUNDGLOBALDOPPLER = hash::HashX32("soundglobaldoppler"),
        IW9H_ASSET_SOUNDGLOBALSHAPECONE = hash::HashX32("soundglobalshapecone"),
        IW9H_ASSET_SOUNDGLOBALFUTZ = hash::HashX32("soundglobalfutz"),
        IW9H_ASSET_SOUNDGLOBALSENDEFFECT = hash::HashX32("soundglobalsendeffect"),
        IW9H_ASSET_SOUNDGLOBALNAMETABLE = hash::HashX32("soundglobalnametable"),
        IW9H_ASSET_SOUNDGLOBALFACTIONTABLE = hash::HashX32("soundglobalfactiontable"),
        IW9H_ASSET_SOUNDGLOBALSPEAKERMAP = hash::HashX32("soundglobalspeakermap"),
        IW9H_ASSET_SOUNDBANK = hash::HashX32("soundbank"),
        IW9H_ASSET_SOUNDBANK_MERGE = hash::HashX32("soundbank_merge"),
        IW9H_ASSET_SOUNDBANKTRANSIENT = hash::HashX32("soundbanktransient"),
        IW9H_ASSET_COL_MAP = hash::HashX32("col_map"),
        IW9H_ASSET_COM_MAP = hash::HashX32("com_map"),
        IW9H_ASSET_GLASS_MAP = hash::HashX32("glass_map"),
        IW9H_ASSET_AIPATHS = hash::HashX32("aipaths"),
        IW9H_ASSET_NAVMESH = hash::HashX32("navmesh"),
        IW9H_ASSET_TACGRAPH = hash::HashX32("tacgraph"),
        IW9H_ASSET_AIREGIONGRAPHS = hash::HashX32("airegiongraphs"),
        IW9H_ASSET_MAP_ENTS = hash::HashX32("map_ents"),
        IW9H_ASSET_MAP_ENTS_TRZONE = hash::HashX32("map_ents_trzone"),
        IW9H_ASSET_FX_MAP = hash::HashX32("fx_map"),
        IW9H_ASSET_GFX_MAP = hash::HashX32("gfx_map"),
        IW9H_ASSET_GFX_MAP_TRZONE = hash::HashX32("gfx_map_trzone"),
        IW9H_ASSET_IESPROFILE = hash::HashX32("iesprofile"),
        IW9H_ASSET_LIGHTDEF = hash::HashX32("lightdef"),
        IW9H_ASSET_GRADINGCLUT = hash::HashX32("gradingclut"),
        IW9H_ASSET_UI_MAP = hash::HashX32("ui_map"),
        IW9H_ASSET_FOGSPLINE = hash::HashX32("fogspline"),
        IW9H_ASSET_ANIMCLASS = hash::HashX32("animclass"),
        IW9H_ASSET_PLAYERANIM = hash::HashX32("playeranim"),
        IW9H_ASSET_GESTURE = hash::HashX32("gesture"),
        IW9H_ASSET_LOCALIZE = hash::HashX32("localize"),
        IW9H_ASSET_ATTACHMENT = hash::HashX32("attachment"),
        IW9H_ASSET_WEAPON = hash::HashX32("weapon"),
        IW9H_ASSET_VFX = hash::HashX32("vfx"),
        IW9H_ASSET_IMPACTFX = hash::HashX32("impactfx"),
        IW9H_ASSET_SURFACEFX = hash::HashX32("surfacefx"),
        IW9H_ASSET_AITYPE = hash::HashX32("aitype"),
        IW9H_ASSET_MPTYPE = hash::HashX32("mptype"),
        IW9H_ASSET_CHARACTER = hash::HashX32("character"),
        IW9H_ASSET_XMODELALIAS = hash::HashX32("xmodelalias"),
        IW9H_ASSET_RAWFILE = hash::HashX32("rawfile"),
        IW9H_ASSET_SCRIPTFILE = hash::HashX32("scriptfile"),
        IW9H_ASSET_SCRIPTDEBUGDATA = hash::HashX32("scriptdebugdata"),
        IW9H_ASSET_GSCOBJ = hash::HashX32("gscobj"),
        IW9H_ASSET_GSCGDB = hash::HashX32("gscgdb"),
        IW9H_ASSET_STRINGTABLE = hash::HashX32("stringtable"),
        IW9H_ASSET_LEADERBOARDDEF = hash::HashX32("leaderboarddef"),
        IW9H_ASSET_VIRTUALLEADERBOARDDEF = hash::HashX32("virtualleaderboarddef"),
        IW9H_ASSET_DDL = hash::HashX32("ddl"),
        IW9H_ASSET_TRACER = hash::HashX32("tracer"),
        IW9H_ASSET_VEHICLE = hash::HashX32("vehicle"),
        IW9H_ASSET_NETCONSTSTRINGS = hash::HashX32("netconststrings"),
        IW9H_ASSET_LUAFILE = hash::HashX32("luafile"),
        IW9H_ASSET_SCRIPTABLE = hash::HashX32("scriptable"),
        IW9H_ASSET_EQUIPSNDTABLE = hash::HashX32("equipsndtable"),
        IW9H_ASSET_VECTORFIELD = hash::HashX32("vectorfield"),
        IW9H_ASSET_PARTICLESIMANIMATION = hash::HashX32("particlesimanimation"),
        IW9H_ASSET_STREAMINGINFO = hash::HashX32("streaminginfo"),
        IW9H_ASSET_LASER = hash::HashX32("laser"),
        IW9H_ASSET_GAMEPROPS = hash::HashX32("gameprops"),
        IW9H_ASSET_MATERIALSTANDARD = hash::HashX32("materialstandard"),
        IW9H_ASSET_BEAM = hash::HashX32("beam"),
        IW9H_ASSET_TTF = hash::HashX32("ttf"),
        IW9H_ASSET_SUIT = hash::HashX32("suit"),
        IW9H_ASSET_SUITANIMPACKAGE = hash::HashX32("suitanimpackage"),
        IW9H_ASSET_CAMERA = hash::HashX32("camera"),
        IW9H_ASSET_HUDOUTLINE = hash::HashX32("hudoutline"),
        IW9H_ASSET_RUMBLE = hash::HashX32("rumble"),
        IW9H_ASSET_RUMBLEGRAPH = hash::HashX32("rumblegraph"),
        IW9H_ASSET_ANIMPKG = hash::HashX32("animpkg"),
        IW9H_ASSET_SFXPKG = hash::HashX32("sfxpkg"),
        IW9H_ASSET_VFXPKG = hash::HashX32("vfxpkg"),
        IW9H_ASSET_FOOTSTEPVFX = hash::HashX32("footstepvfx"),
        IW9H_ASSET_BEHAVIORTREE = hash::HashX32("behaviortree"),
        IW9H_ASSET_BEHAVIORSEQUENCER = hash::HashX32("behaviorsequencer"),
        IW9H_ASSET_SIGHTCONFIG = hash::HashX32("sightconfig"),
        IW9H_ASSET_SIGHTCONFIGTEMPLATE = hash::HashX32("sightconfigtemplate"),
        IW9H_ASSET_AIANIMSET = hash::HashX32("aianimset"),
        IW9H_ASSET_AIASM = hash::HashX32("aiasm"),
        IW9H_ASSET_PROCEDURALBONES = hash::HashX32("proceduralbones"),
        IW9H_ASSET_DYNAMICBONES = hash::HashX32("dynamicbones"),
        IW9H_ASSET_RETICLE = hash::HashX32("reticle"),
        IW9H_ASSET_XANIMCURVE = hash::HashX32("xanimcurve"),
        IW9H_ASSET_COVERSELECTOR = hash::HashX32("coverselector"),
        IW9H_ASSET_ENEMYSELECTOR = hash::HashX32("enemyselector"),
        IW9H_ASSET_CLIENTCHARACTER = hash::HashX32("clientcharacter"),
        IW9H_ASSET_CLOTHASSET = hash::HashX32("clothasset"),
        IW9H_ASSET_CINEMATICMOTION = hash::HashX32("cinematicmotion"),
        IW9H_ASSET_ACCESSORY = hash::HashX32("accessory"),
        IW9H_ASSET_LOCDMGTABLE = hash::HashX32("locdmgtable"),
        IW9H_ASSET_BULLETPENETRATION = hash::HashX32("bulletpenetration"),
        IW9H_ASSET_SCRIPTBUNDLE = hash::HashX32("scriptbundle"),
        IW9H_ASSET_BLENDSPACE2D = hash::HashX32("blendspace2d"),
        IW9H_ASSET_XCAM = hash::HashX32("xcam"),
        IW9H_ASSET_CAMO = hash::HashX32("camo"),
        IW9H_ASSET_XCOMPOSITEMODEL = hash::HashX32("xcompositemodel"),
        IW9H_ASSET_XMODELDETAILCOLLISION = hash::HashX32("xmodeldetailcollision"),
        IW9H_ASSET_STREAMTREEOVERRIDE = hash::HashX32("streamtreeoverride"),
        IW9H_ASSET_KEYVALUEPAIRS = hash::HashX32("keyvaluepairs"),
        IW9H_ASSET_STTERRAIN = hash::HashX32("stterrain"),
        IW9H_ASSET_VHMDATA = hash::HashX32("vhmdata"),
        IW9H_ASSET_NATIVESCRIPTPATCH = hash::HashX32("nativescriptpatch"),
        IW9H_ASSET_COLLISIONTILE = hash::HashX32("collisiontile"),
        IW9H_ASSET_EXECUTION = hash::HashX32("execution"),
        IW9H_ASSET_CARRYOBJECT = hash::HashX32("carryobject"),
        IW9H_ASSET_SOUNDBANKLIST = hash::HashX32("soundbanklist"),
        IW9H_ASSET_WEAPONACCURACY = hash::HashX32("weaponaccuracy"),
        IW9H_ASSET_DECALVOLUMEMATERIAL = hash::HashX32("decalvolumematerial"),
        IW9H_ASSET_DECALVOLUMEMASK = hash::HashX32("decalvolumemask"),
        IW9H_ASSET_DYNENTITYLIST = hash::HashX32("dynentitylist"),
        IW9H_ASSET_FX_MAP_TRZONE = hash::HashX32("fx_map_trzone"),
        IW9H_ASSET_VOLUMETRICHEIGHTMAP = hash::HashX32("volumetricheightmap"),
        IW9H_ASSET_DLOGSCHEMA = hash::HashX32("dlogschema"),
        IW9H_ASSET_EDGELIST = hash::HashX32("edgelist"),
        IW9H_ASSET_XBONESET = hash::HashX32("xboneset"),
        IW9H_ASSET_RAGDOLLASSET = hash::HashX32("ragdollasset"),
        IW9H_ASSET_PHYSICSBONEGRAPH = hash::HashX32("physicsbonegraph"),
        IW9H_ASSET_CURVE = hash::HashX32("curve"),
        IW9H_ASSET_SKELETONCONSTRAINTS = hash::HashX32("skeletonconstraints"),
        IW9H_ASSET_TRIGGEREFFECT = hash::HashX32("triggereffect"),
        IW9H_ASSET_WEAPONTRIGGER = hash::HashX32("weapontrigger"),
        IW9H_ASSET_VOLUMETRICCLOUD = hash::HashX32("volumetriccloud"),
        IW9H_ASSET_CODCASTERDATA = hash::HashX32("codcasterdata"),
        IW9H_ASSET_WATERSYSTEM = hash::HashX32("watersystem"),
        IW9H_ASSET_WATERBUOYANCY = hash::HashX32("waterbuoyancy"),
        IW9H_ASSET_KEYBINDS = hash::HashX32("keybinds"),
        IW9H_ASSET_CALLOUTMARKERPING = hash::HashX32("calloutmarkerping"),
        IW9H_ASSET_LIGHTSTATE = hash::HashX32("lightstate"),
        IW9H_ASSET_RADIANTTELEMETRY = hash::HashX32("radianttelemetry"),
        IW9H_ASSET_AIMARKUP = hash::HashX32("aimarkup"),
        IW9H_ASSET_SCENARIO = hash::HashX32("scenario"),
        IW9H_ASSET_AI_INTERACTION = hash::HashX32("ai_interaction"),
        IW9H_ASSET_MAPVOXELIZEDSTATEFORMAT = hash::HashX32("mapvoxelizedstateformat"),
        IW9H_ASSET_WATERVIS = hash::HashX32("watervis"),
        IW9H_ASSET_GAMETYPE = hash::HashX32("gametype"),
        IW9H_ASSET_GAMETYPETABLE = hash::HashX32("gametypetable"),
        IW9H_ASSET_SNDMODIFIER = hash::HashX32("sndmodifier"),
        IW9H_ASSET_WEAPONBLUEPRINT = hash::HashX32("weaponblueprint"),
        IW9H_ASSET_ATTACHMENTBLUEPRINT = hash::HashX32("attachmentblueprint"),
        IW9H_ASSET_MOVINGPLATFORM = hash::HashX32("movingplatform"),
        IW9H_ASSET_HWCONFIG = hash::HashX32("hwconfig"),
        IW9H_ASSET_TIMELAPSESKY = hash::HashX32("timelapsesky"),
        IW9H_ASSET_HWCONFIGURATORINFO = hash::HashX32("hwconfiguratorinfo"),
        IW9H_ASSET_OBJECTIVEDATA = hash::HashX32("objectivedata"),
        IW9H_ASSET_FONT = hash::HashX32("font"),
        IW9H_ASSET_MOTIONMATCHINGFEATURES = hash::HashX32("motionmatchingfeatures"),
        IW9H_ASSET_MOTIONMATCHINGSET = hash::HashX32("motionmatchingset"),
        IW9H_ASSET_GAMETYPESTATDATA = hash::HashX32("gametypestatdata"),
        IW9H_ASSET_FONTICON = hash::HashX32("fonticon"),
        IW9H_ASSET_CALLOUTMARKERPINGWHEEL = hash::HashX32("calloutmarkerpingwheel"),
        IW9H_ASSET_HWCONFIGVAR = hash::HashX32("hwconfigvar"),
        IW9H_ASSET_ZIVART = hash::HashX32("zivart"),
        IW9H_ASSET_MOVIE = hash::HashX32("movie"),
        IW9H_ASSET_MAPINFO = hash::HashX32("mapinfo"),
        IW9H_ASSET_MAPTABLE = hash::HashX32("maptable"),
        IW9H_ASSET_ACHIEVEMENT = hash::HashX32("achievement"),
        IW9H_ASSET_ACHIEVEMENTLIST = hash::HashX32("achievementlist"),
        IW9H_ASSET_MATERIALDEBUGDATA = hash::HashX32("materialdebugdata"),
        IW9H_ASSET_SCRIPTABLEVARIANT = hash::HashX32("scriptablevariant"),
        IW9H_ASSET_LEAGUEPLAYSEASONS = hash::HashX32("leagueplayseasons"),
        IW9H_ASSET_SETTINGCONTEXT = hash::HashX32("settingcontext"),
        IW9H_ASSET_AI_EVENTLIST = hash::HashX32("ai_eventlist"),
        IW9H_ASSET_SOUNDEVENT = hash::HashX32("soundevent"),
        IW9H_ASSET_CALLOUTMARKERPINGMETADATA = hash::HashX32("calloutmarkerpingmetadata"),
        IW9H_ASSET_PROJECT = hash::HashX32("project"),
        IW9H_ASSET_PROJECTTABLE = hash::HashX32("projecttable"),
        IW9H_ASSET_GAMEMODE = hash::HashX32("gamemode"),
        IW9H_ASSET_SNDASSET = hash::HashX32("sndasset"),
        IW9H_ASSET_GFXUMBRATOME = hash::HashX32("gfxumbratome"),
        IW9H_ASSET_AUDIOVISUALIZER = hash::HashX32("audiovisualizer"),
        IW9H_ASSET_MATERIALANIMATIONPARAMS = hash::HashX32("materialanimationparams"),
        IW9H_ASSET_NAMEPLATESETTINGS = hash::HashX32("nameplatesettings"),
        IW9H_ASSET_REACTIVEAUDIOPARAMS = hash::HashX32("reactiveaudioparams"),
        IW9H_ASSET_REACTIVEVFXPACKAGE = hash::HashX32("reactivevfxpackage"),
        IW9H_ASSET_MATERIALTINTANIMATIONPARAMS = hash::HashX32("materialtintanimationparams"),
        IW9H_ASSET_MATERIALUVANIMATIONPARAMS = hash::HashX32("materialuvanimationparams"),
        IW9H_ASSET_MATERIALCAMOANIMATIONPARAMS = hash::HashX32("materialcamoanimationparams"),
        IW9H_ASSET_MATERIALANIMATION = hash::HashX32("materialanimation"),
        IW9H_ASSET_IMPACTFXTABLE = hash::HashX32("impactfxtable"),
        IW9H_ASSET_IMPACTTYPETOIMPACTFXTABLE = hash::HashX32("impacttypetoimpactfxtable"),
        IW9H_ASSET_REACTIVEOPERATOR = hash::HashX32("reactiveoperator"),
        IW9H_ASSET_WEATHERVOLUME = hash::HashX32("weathervolume"),
        IW9H_ASSET_VEHICLETRICK = hash::HashX32("vehicletrick"),
        IW9H_ASSET_REACTIVEAUDIOPACKAGE = hash::HashX32("reactiveaudiopackage"),
    };


    enum IW9AssetType : uint32_t {
        IW9_ASSET_PHYSICSLIBRARY = 0x0, // physicslibrary
        IW9_ASSET_PHYSICSSFXEVENTASSET = 0x1, // physicssfxeventasset
        IW9_ASSET_PHYSICSVFXEVENTASSET = 0x2, // physicsvfxeventasset
        IW9_ASSET_PHYSICSASSET = 0x3, // physicsasset
        IW9_ASSET_PHYSICSFXPIPELINE = 0x4, // physicsfxpipeline
        IW9_ASSET_PHYSICSFXSHAPE = 0x5, // physicsfxshape
        IW9_ASSET_PHYSICSDEBUGDATA = 0x6, // physicsdebugdata
        IW9_ASSET_XANIM = 0x7, // xanim
        IW9_ASSET_XMODELSURFS = 0x8, // xmodelsurfs
        IW9_ASSET_XMODEL = 0x9, // xmodel
        IW9_ASSET_MAYHEM = 0xa, // mayhem
        IW9_ASSET_MATERIAL = 0xb, // material
        IW9_ASSET_COMPUTESHADER = 0xc, // computeshader
        IW9_ASSET_LIBSHADER = 0xd, // libshader
        IW9_ASSET_VERTEXSHADER = 0xe, // vertexshader
        IW9_ASSET_HULLSHADER = 0xf, // hullshader
        IW9_ASSET_DOMAINSHADER = 0x10, // domainshader
        IW9_ASSET_PIXELSHADER = 0x11, // pixelshader
        IW9_ASSET_TECHSET = 0x12, // techset
        IW9_ASSET_IMAGE = 0x13, // image
        IW9_ASSET_SOUNDGLOBALVOLMOD = 0x14, // soundglobalvolmod
        IW9_ASSET_SOUNDGLOBALENTCHANNEL = 0x15, // soundglobalentchannel
        IW9_ASSET_SOUNDGLOBALCONTEXT = 0x16, // soundglobalcontext
        IW9_ASSET_SOUNDGLOBALMASTER = 0x17, // soundglobalmaster
        IW9_ASSET_SOUNDGLOBALWHIZBY = 0x18, // soundglobalwhizby
        IW9_ASSET_SOUNDGLOBALBULLETCRACK = 0x19, // soundglobalbulletcrack
        IW9_ASSET_SOUNDGLOBALPERK = 0x1a, // soundglobalperk
        IW9_ASSET_SOUNDGLOBALOCCLUSION = 0x1b, // soundglobalocclusion
        IW9_ASSET_SOUNDGLOBALSURFACEINFO = 0x1c, // soundglobalsurfaceinfo
        IW9_ASSET_SOUNDGLOBALCURVE = 0x1d, // soundglobalcurve
        IW9_ASSET_SOUNDGLOBALDOPPLER = 0x1e, // soundglobaldoppler
        IW9_ASSET_SOUNDGLOBALSHAPECONE = 0x1f, // soundglobalshapecone
        IW9_ASSET_SOUNDGLOBALFUTZ = 0x20, // soundglobalfutz
        IW9_ASSET_SOUNDGLOBALSENDEFFECT = 0x21, // soundglobalsendeffect
        IW9_ASSET_SOUNDGLOBALNAMETABLE = 0x22, // soundglobalnametable
        IW9_ASSET_SOUNDGLOBALFACTIONTABLE = 0x23, // soundglobalfactiontable
        IW9_ASSET_SOUNDGLOBALSPEAKERMAP = 0x24, // soundglobalspeakermap
        IW9_ASSET_SOUNDBANK = 0x25, // soundbank
        IW9_ASSET_SOUNDBANK_MERGE = 0x26, // soundbank_merge
        IW9_ASSET_SOUNDBANKTRANSIENT = 0x27, // soundbanktransient
        IW9_ASSET_COL_MAP = 0x28, // col_map
        IW9_ASSET_COM_MAP = 0x29, // com_map
        IW9_ASSET_GLASS_MAP = 0x2a, // glass_map
        IW9_ASSET_AIPATHS = 0x2b, // aipaths
        IW9_ASSET_NAVMESH = 0x2c, // navmesh
        IW9_ASSET_TACGRAPH = 0x2d, // tacgraph
        IW9_ASSET_AIREGIONGRAPHS = 0x2e, // airegiongraphs
        IW9_ASSET_MAP_ENTS = 0x2f, // map_ents
        IW9_ASSET_MAP_ENTS_TRZONE = 0x30, // map_ents_trzone
        IW9_ASSET_FX_MAP = 0x31, // fx_map
        IW9_ASSET_GFX_MAP = 0x32, // gfx_map
        IW9_ASSET_GFX_MAP_TRZONE = 0x33, // gfx_map_trzone
        IW9_ASSET_IESPROFILE = 0x34, // iesprofile
        IW9_ASSET_LIGHTDEF = 0x35, // lightdef
        IW9_ASSET_GRADINGCLUT = 0x36, // gradingclut
        IW9_ASSET_UI_MAP = 0x37, // ui_map
        IW9_ASSET_FOGSPLINE = 0x38, // fogspline
        IW9_ASSET_ANIMCLASS = 0x39, // animclass
        IW9_ASSET_PLAYERANIM = 0x3a, // playeranim
        IW9_ASSET_GESTURE = 0x3b, // gesture
        IW9_ASSET_LOCALIZE = 0x3c, // localize
        IW9_ASSET_ATTACHMENT = 0x3d, // attachment
        IW9_ASSET_WEAPON = 0x3e, // weapon
        IW9_ASSET_VFX = 0x3f, // vfx
        IW9_ASSET_IMPACTFX = 0x40, // impactfx
        IW9_ASSET_SURFACEFX = 0x41, // surfacefx
        IW9_ASSET_AITYPE = 0x42, // aitype
        IW9_ASSET_MPTYPE = 0x43, // mptype
        IW9_ASSET_CHARACTER = 0x44, // character
        IW9_ASSET_XMODELALIAS = 0x45, // xmodelalias
        IW9_ASSET_RAWFILE = 0x46, // rawfile
        IW9_ASSET_SCRIPTFILE = 0x47, // scriptfile
        IW9_ASSET_SCRIPTDEBUGDATA = 0x48, // scriptdebugdata
        IW9_ASSET_GSCOBJ = 0x49, // gscobj
        IW9_ASSET_GSCGDB = 0x4a, // gscgdb
        IW9_ASSET_STRINGTABLE = 0x4b, // stringtable
        IW9_ASSET_LEADERBOARDDEF = 0x4c, // leaderboarddef
        IW9_ASSET_VIRTUALLEADERBOARDDEF = 0x4d, // virtualleaderboarddef
        IW9_ASSET_DDL = 0x4e, // ddl
        IW9_ASSET_TRACER = 0x4f, // tracer
        IW9_ASSET_VEHICLE = 0x50, // vehicle
        IW9_ASSET_NETCONSTSTRINGS = 0x51, // netconststrings
        IW9_ASSET_LUAFILE = 0x52, // luafile
        IW9_ASSET_SCRIPTABLE = 0x53, // scriptable
        IW9_ASSET_EQUIPSNDTABLE = 0x54, // equipsndtable
        IW9_ASSET_VECTORFIELD = 0x55, // vectorfield
        IW9_ASSET_PARTICLESIMANIMATION = 0x56, // particlesimanimation
        IW9_ASSET_STREAMINGINFO = 0x57, // streaminginfo
        IW9_ASSET_LASER = 0x58, // laser
        IW9_ASSET_GAMEPROPS = 0x59, // gameprops
        IW9_ASSET_MATERIALSTANDARD = 0x5a, // materialstandard
        IW9_ASSET_BEAM = 0x5b, // beam
        IW9_ASSET_TTF = 0x5c, // ttf
        IW9_ASSET_SUIT = 0x5d, // suit
        IW9_ASSET_SUITANIMPACKAGE = 0x5e, // suitanimpackage
        IW9_ASSET_CAMERA = 0x5f, // camera
        IW9_ASSET_HUDOUTLINE = 0x60, // hudoutline
        IW9_ASSET_RUMBLE = 0x61, // rumble
        IW9_ASSET_RUMBLEGRAPH = 0x62, // rumblegraph
        IW9_ASSET_ANIMPKG = 0x63, // animpkg
        IW9_ASSET_SFXPKG = 0x64, // sfxpkg
        IW9_ASSET_VFXPKG = 0x65, // vfxpkg
        IW9_ASSET_FOOTSTEPVFX = 0x66, // footstepvfx
        IW9_ASSET_BEHAVIORTREE = 0x67, // behaviortree
        IW9_ASSET_BEHAVIORSEQUENCER = 0x68, // behaviorsequencer
        IW9_ASSET_SIGHTCONFIG = 0x69, // sightconfig
        IW9_ASSET_SIGHTCONFIGTEMPLATE = 0x6a, // sightconfigtemplate
        IW9_ASSET_AIANIMSET = 0x6b, // aianimset
        IW9_ASSET_AIASM = 0x6c, // aiasm
        IW9_ASSET_PROCEDURALBONES = 0x6d, // proceduralbones
        IW9_ASSET_DYNAMICBONES = 0x6e, // dynamicbones
        IW9_ASSET_RETICLE = 0x6f, // reticle
        IW9_ASSET_XANIMCURVE = 0x70, // xanimcurve
        IW9_ASSET_COVERSELECTOR = 0x71, // coverselector
        IW9_ASSET_ENEMYSELECTOR = 0x72, // enemyselector
        IW9_ASSET_CLIENTCHARACTER = 0x73, // clientcharacter
        IW9_ASSET_CLOTHASSET = 0x74, // clothasset
        IW9_ASSET_CINEMATICMOTION = 0x75, // cinematicmotion
        IW9_ASSET_ACCESSORY = 0x76, // accessory
        IW9_ASSET_LOCDMGTABLE = 0x77, // locdmgtable
        IW9_ASSET_BULLETPENETRATION = 0x78, // bulletpenetration
        IW9_ASSET_SCRIPTBUNDLE = 0x79, // scriptbundle
        IW9_ASSET_BLENDSPACE2D = 0x7a, // blendspace2d
        IW9_ASSET_XCAM = 0x7b, // xcam
        IW9_ASSET_CAMO = 0x7c, // camo
        IW9_ASSET_XCOMPOSITEMODEL = 0x7d, // xcompositemodel
        IW9_ASSET_XMODELDETAILCOLLISION = 0x7e, // xmodeldetailcollision
        IW9_ASSET_STREAMTREEOVERRIDE = 0x7f, // streamtreeoverride
        IW9_ASSET_KEYVALUEPAIRS = 0x80, // keyvaluepairs
        IW9_ASSET_STTERRAIN = 0x81, // stterrain
        IW9_ASSET_VHMDATA = 0x82, // vhmdata
        IW9_ASSET_NATIVESCRIPTPATCH = 0x83, // nativescriptpatch
        IW9_ASSET_COLLISIONTILE = 0x84, // collisiontile
        IW9_ASSET_EXECUTION = 0x85, // execution
        IW9_ASSET_CARRYOBJECT = 0x86, // carryobject
        IW9_ASSET_SOUNDBANKLIST = 0x87, // soundbanklist
        IW9_ASSET_WEAPONACCURACY = 0x88, // weaponaccuracy
        IW9_ASSET_DECALVOLUMEMATERIAL = 0x89, // decalvolumematerial
        IW9_ASSET_DECALVOLUMEMASK = 0x8a, // decalvolumemask
        IW9_ASSET_DYNENTITYLIST = 0x8b, // dynentitylist
        IW9_ASSET_FX_MAP_TRZONE = 0x8c, // fx_map_trzone
        IW9_ASSET_VOLUMETRICHEIGHTMAP = 0x8d, // volumetricheightmap
        IW9_ASSET_DLOGSCHEMA = 0x8e, // dlogschema
        IW9_ASSET_EDGELIST = 0x8f, // edgelist
        IW9_ASSET_XBONESET = 0x90, // xboneset
        IW9_ASSET_RAGDOLLASSET = 0x91, // ragdollasset
        IW9_ASSET_PHYSICSBONEGRAPH = 0x92, // physicsbonegraph
        IW9_ASSET_CURVE = 0x93, // curve
        IW9_ASSET_SKELETONCONSTRAINTS = 0x94, // skeletonconstraints
        IW9_ASSET_TRIGGEREFFECT = 0x95, // triggereffect
        IW9_ASSET_WEAPONTRIGGER = 0x96, // weapontrigger
        IW9_ASSET_VOLUMETRICCLOUD = 0x97, // volumetriccloud
        IW9_ASSET_CODCASTERDATA = 0x98, // codcasterdata
        IW9_ASSET_WATERSYSTEM = 0x99, // watersystem
        IW9_ASSET_WATERBUOYANCY = 0x9a, // waterbuoyancy
        IW9_ASSET_KEYBINDS = 0x9b, // keybinds
        IW9_ASSET_CALLOUTMARKERPING = 0x9c, // calloutmarkerping
        IW9_ASSET_LIGHTSTATE = 0x9d, // lightstate
        IW9_ASSET_RADIANTTELEMETRY = 0x9e, // radianttelemetry
        IW9_ASSET_AIMARKUP = 0x9f, // aimarkup
        IW9_ASSET_SCENARIO = 0xa0, // scenario
        IW9_ASSET_AI_INTERACTION = 0xa1, // ai_interaction
        IW9_ASSET_MAPVOXELIZEDSTATEFORMAT = 0xa2, // mapvoxelizedstateformat
        IW9_ASSET_WATERVIS = 0xa3, // watervis
        IW9_ASSET_GAMETYPE = 0xa4, // gametype
        IW9_ASSET_GAMETYPETABLE = 0xa5, // gametypetable
        IW9_ASSET_SNDMODIFIER = 0xa6, // sndmodifier
        IW9_ASSET_WEAPONBLUEPRINT = 0xa7, // weaponblueprint
        IW9_ASSET_ATTACHMENTBLUEPRINT = 0xa8, // attachmentblueprint
        IW9_ASSET_MOVINGPLATFORM = 0xa9, // movingplatform
        IW9_ASSET_HWCONFIG = 0xaa, // hwconfig
        IW9_ASSET_TIMELAPSESKY = 0xab, // timelapsesky
        IW9_ASSET_HWCONFIGURATORINFO = 0xac, // hwconfiguratorinfo
        IW9_ASSET_OBJECTIVEDATA = 0xad, // objectivedata
        IW9_ASSET_FONT = 0xae, // font
        IW9_ASSET_MOTIONMATCHINGFEATURES = 0xaf, // motionmatchingfeatures
        IW9_ASSET_MOTIONMATCHINGSET = 0xb0, // motionmatchingset
        IW9_ASSET_GAMETYPESTATDATA = 0xb1, // gametypestatdata
        IW9_ASSET_FONTICON = 0xb2, // fonticon
        IW9_ASSET_CALLOUTMARKERPINGWHEEL = 0xb3, // calloutmarkerpingwheel
        IW9_ASSET_HWCONFIGVAR = 0xb4, // hwconfigvar
        IW9_ASSET_ZIVART = 0xb5, // zivart
        IW9_ASSET_MOVIE = 0xb6, // movie
        IW9_ASSET_MAPINFO = 0xb7, // mapinfo
        IW9_ASSET_MAPTABLE = 0xb8, // maptable
        IW9_ASSET_ACHIEVEMENT = 0xb9, // achievement
        IW9_ASSET_ACHIEVEMENTLIST = 0xba, // achievementlist
        IW9_ASSET_MATERIALDEBUGDATA = 0xbb, // materialdebugdata
        IW9_ASSET_SCRIPTABLEVARIANT = 0xbc, // scriptablevariant
        IW9_ASSET_LEAGUEPLAYSEASONS = 0xbd, // leagueplayseasons
        IW9_ASSET_SETTINGCONTEXT = 0xbe, // settingcontext
        IW9_ASSET_AI_EVENTLIST = 0xbf, // ai_eventlist
        IW9_ASSET_SOUNDEVENT = 0xc0, // soundevent
        IW9_ASSET_CALLOUTMARKERPINGMETADATA = 0xc1, // calloutmarkerpingmetadata
        IW9_ASSET_PROJECT = 0xc2, // project
        IW9_ASSET_PROJECTTABLE = 0xc3, // projecttable
        IW9_ASSET_GAMEMODE = 0xc4, // gamemode
        IW9_ASSET_SNDASSET = 0xc5, // sndasset
        IW9_ASSET_GFXUMBRATOME = 0xc6, // gfxumbratome
        IW9_ASSET_AUDIOVISUALIZER = 0xc7, // audiovisualizer
        IW9_ASSET_MATERIALANIMATIONPARAMS = 0xc8, // materialanimationparams
        IW9_ASSET_NAMEPLATESETTINGS = 0xc9, // nameplatesettings
        IW9_ASSET_REACTIVEAUDIOPARAMS = 0xca, // reactiveaudioparams
        IW9_ASSET_REACTIVEVFXPACKAGE = 0xcb, // reactivevfxpackage
        IW9_ASSET_MATERIALTINTANIMATIONPARAMS = 0xcc, // materialtintanimationparams
        IW9_ASSET_MATERIALUVANIMATIONPARAMS = 0xcd, // materialuvanimationparams
        IW9_ASSET_MATERIALCAMOANIMATIONPARAMS = 0xce, // materialcamoanimationparams
        IW9_ASSET_MATERIALANIMATION = 0xcf, // materialanimation
        IW9_ASSET_IMPACTFXTABLE = 0xd0, // impactfxtable
        IW9_ASSET_IMPACTTYPETOIMPACTFXTABLE = 0xd1, // impacttypetoimpactfxtable
        IW9_ASSET_REACTIVEOPERATOR = 0xd2, // reactiveoperator
        IW9_ASSET_WEATHERVOLUME = 0xd3, // weathervolume
        IW9_ASSET_VEHICLETRICK = 0xd4, // vehicletrick
        IW9_ASSET_REACTIVEAUDIOPACKAGE = 0xd5, // reactiveaudiopackage
    };



    const char* PoolName(IW9HashAssetType type);
    IW9HashAssetType PoolId(const char* name);

}