#include <includes.hpp>
#include <tools/mw22/mw22.hpp>

namespace tool::mw22 {
    namespace {
        const char* poolNames[]{
            "physicslibrary", // 0
            "physicssfxeventasset", // 1
            "physicsvfxeventasset", // 2
            "physicsasset", // 3
            "physicsfxpipeline", // 4
            "physicsfxshape", // 5
            "physicsdebugdata", // 6
            "xanim", // 7
            "xmodelsurfs", // 8
            "xmodel", // 9
            "mayhem", // a
            "material", // b
            "computeshader", // c
            "libshader", // d
            "vertexshader", // e
            "hullshader", // f
            "domainshader", // 10
            "pixelshader", // 11
            "techset", // 12
            "image", // 13
            "soundglobalvolmod", // 14
            "soundglobalentchannel", // 15
            "soundglobalcontext", // 16
            "soundglobalmaster", // 17
            "soundglobalwhizby", // 18
            "soundglobalbulletcrack", // 19
            "soundglobalperk", // 1a
            "soundglobalocclusion", // 1b
            "soundglobalsurfaceinfo", // 1c
            "soundglobalcurve", // 1d
            "soundglobaldoppler", // 1e
            "soundglobalshapecone", // 1f
            "soundglobalfutz", // 20
            "soundglobalsendeffect", // 21
            "soundglobalnametable", // 22
            "soundglobalfactiontable", // 23
            "soundglobalspeakermap", // 24
            "soundbank", // 25
            "soundbank_merge", // 26
            "soundbanktransient", // 27
            "col_map", // 28
            "com_map", // 29
            "glass_map", // 2a
            "aipaths", // 2b
            "navmesh", // 2c
            "tacgraph", // 2d
            "airegiongraphs", // 2e
            "map_ents", // 2f
            "map_ents_trzone", // 30
            "fx_map", // 31
            "gfx_map", // 32
            "gfx_map_trzone", // 33
            "iesprofile", // 34
            "lightdef", // 35
            "gradingclut", // 36
            "ui_map", // 37
            "fogspline", // 38
            "animclass", // 39
            "playeranim", // 3a
            "gesture", // 3b
            "localize", // 3c
            "attachment", // 3d
            "weapon", // 3e
            "vfx", // 3f
            "impactfx", // 40
            "surfacefx", // 41
            "aitype", // 42
            "mptype", // 43
            "character", // 44
            "xmodelalias", // 45
            "rawfile", // 46
            "scriptfile", // 47
            "scriptdebugdata", // 48
            "gscobj", // 49
            "gscgdb", // 4a
            "stringtable", // 4b
            "leaderboarddef", // 4c
            "virtualleaderboarddef", // 4d
            "ddl", // 4e
            "tracer", // 4f
            "vehicle", // 50
            "netconststrings", // 51
            "luafile", // 52
            "scriptable", // 53
            "equipsndtable", // 54
            "vectorfield", // 55
            "particlesimanimation", // 56
            "streaminginfo", // 57
            "laser", // 58
            "gameprops", // 59
            "materialstandard", // 5a
            "beam", // 5b
            "ttf", // 5c
            "suit", // 5d
            "suitanimpackage", // 5e
            "camera", // 5f
            "hudoutline", // 60
            "rumble", // 61
            "rumblegraph", // 62
            "animpkg", // 63
            "sfxpkg", // 64
            "vfxpkg", // 65
            "footstepvfx", // 66
            "behaviortree", // 67
            "behaviorsequencer", // 68
            "sightconfig", // 69
            "sightconfigtemplate", // 6a
            "aianimset", // 6b
            "aiasm", // 6c
            "proceduralbones", // 6d
            "dynamicbones", // 6e
            "reticle", // 6f
            "xanimcurve", // 70
            "coverselector", // 71
            "enemyselector", // 72
            "clientcharacter", // 73
            "clothasset", // 74
            "cinematicmotion", // 75
            "accessory", // 76
            "locdmgtable", // 77
            "bulletpenetration", // 78
            "scriptbundle", // 79
            "blendspace2d", // 7a
            "xcam", // 7b
            "camo", // 7c
            "xcompositemodel", // 7d
            "xmodeldetailcollision", // 7e
            "streamtreeoverride", // 7f
            "keyvaluepairs", // 80
            "stterrain", // 81
            "vhmdata", // 82
            "nativescriptpatch", // 83
            "collisiontile", // 84
            "execution", // 85
            "carryobject", // 86
            "soundbanklist", // 87
            "weaponaccuracy", // 88
            "decalvolumematerial", // 89
            "decalvolumemask", // 8a
            "dynentitylist", // 8b
            "fx_map_trzone", // 8c
            "volumetricheightmap", // 8d
            "dlogschema", // 8e
            "edgelist", // 8f
            "xboneset", // 90
            "ragdollasset", // 91
            "physicsbonegraph", // 92
            "curve", // 93
            "skeletonconstraints", // 94
            "triggereffect", // 95
            "weapontrigger", // 96
            "volumetriccloud", // 97
            "codcasterdata", // 98
            "watersystem", // 99
            "waterbuoyancy", // 9a
            "keybinds", // 9b
            "calloutmarkerping", // 9c
            "lightstate", // 9d
            "radianttelemetry", // 9e
            "aimarkup", // 9f
            "scenario", // a0
            "ai_interaction", // a1
            "mapvoxelizedstateformat", // a2
            "watervis", // a3
            "gametype", // a4
            "gametypetable", // a5
            "sndmodifier", // a6
            "weaponblueprint", // a7
            "attachmentblueprint", // a8
            "movingplatform", // a9
            "hwconfig", // aa
            "timelapsesky", // ab
            "hwconfiguratorinfo", // ac
            "objectivedata", // ad
            "font", // ae
            "motionmatchingfeatures", // af
            "motionmatchingset", // b0
            "gametypestatdata", // b1
            "fonticon", // b2
            "calloutmarkerpingwheel", // b3
            "hwconfigvar", // b4
            "zivart", // b5
            "movie", // b6
            "mapinfo", // b7
            "maptable", // b8
            "achievement", // b9
            "achievementlist", // ba
            "materialdebugdata", // bb
            "scriptablevariant", // bc
            "leagueplayseasons", // bd
            "settingcontext", // be
            "ai_eventlist", // bf
            "soundevent", // c0
            "calloutmarkerpingmetadata", // c1
            "project", // c2
            "projecttable", // c3
            "gamemode", // c4
            "sndasset", // c5
            "gfxumbratome", // c6
            "audiovisualizer", // c7
            "materialanimationparams", // c8
            "nameplatesettings", // c9
            "reactiveaudioparams", // ca
            "reactivevfxpackage", // cb
            "materialtintanimationparams", // cc
            "materialuvanimationparams", // cd
            "materialcamoanimationparams", // ce
            "materialanimation", // cf
            "impactfxtable", // d0
            "impacttypetoimpactfxtable", // d1
            "reactiveoperator", // d2
            "weathervolume", // d3
            "vehicletrick", // d4
            "reactiveaudiopackage", // d5
        };
    }

    const char* PoolName(IW9HashAssetType type) {
        static std::unordered_map<uint32_t, const char*> maps{};
        if (maps.empty()) {
            for (const char* s : poolNames) {
                maps[PoolId(s)] = s;
            }
        }
        auto it{ maps.find(type) };
        if (it == maps.end()) {
            return hashutils::ExtractTmp("hash", type);
        }
        return it->second;
    }

    IW9HashAssetType PoolId(const char* name) {
        return (IW9HashAssetType)hash::HashX32(name);
    }
}