#pragma once
#include <hook/scan_container.hpp>

namespace hook::generated_scan_runtime {
    // runtime used for the autogenerated scan files

    enum ScanType {
        ST_RELATIVE,
        ST_ABSOLUTE,
        ST_OFFSET,
        ST_GETOFFSET32,
    };

    struct ScanInformation {
        const char* id;
        const char* scan;
        ScanType type;
        int offset;
        int postOffset;
        bool single;
        void** ref;
    };

    // load registered scans
    void LoadScans(hook::scan_container::ScanContainer& scan, ScanInformation* list, size_t count);
} // namespace hook::generated_scan_runtime