// autogenerated file from cw.json, do not edit this file

// game template id
constexpr const char* GAME_ID = "cw";
// dumped module name
constexpr const char* MODULE_NAME = "BlackOpsColdWar_dump.exe";
// first asset name
constexpr const char* FIRST_ASSET_NAME = "zone";
// end asset name
constexpr const char* END_ASSET_NAME = "";

/*
 * Common
 */

// Decrypt strings (Common)
extern hook::refs::Ref<const char* (const char* str)> DecryptString;

/*
 * Fast Files
 */

// $UnkNavMesh (Fast Files)
extern hook::refs::Ref<> $UnkNavMesh;
// DB_AllocStreamPos (Fast Files)
extern hook::refs::Ref<> DB_AllocStreamPos;
// DB_AllocXBlocks (Fast Files)
extern hook::refs::Ref<> DB_AllocXBlocks;
// DB_ConvertOffsetToPointer (Fast Files)
extern hook::refs::Ref<> DB_ConvertOffsetToPointer;
// Find XAsset (Fast Files)
extern hook::refs::Ref<XAssetHeader (XAssetType type, CWXHash name, bool inv, int timeout)> DB_FindXAssetHeader;
// DB_GetXAssetTypeSize (Fast Files)
extern hook::refs::Ref<> DB_GetXAssetTypeSize;
// DB_IncStreamPos (Fast Files)
extern hook::refs::Ref<> DB_IncStreamPos;
// DB_InitStreams (Fast Files)
extern hook::refs::Ref<> DB_InitStreams;
// DB_LinkAttachmentUnique (Fast Files)
extern hook::refs::Ref<> DB_LinkAttachmentUnique;
// DB_LinkDestructibleDef (Fast Files)
extern hook::refs::Ref<> DB_LinkDestructibleDef;
// DB_LinkDynModel (Fast Files)
extern hook::refs::Ref<> DB_LinkDynModel;
// DB_LinkSoundBank (Fast Files)
extern hook::refs::Ref<> DB_LinkSoundBank;
// DB_LinkWeapon (Fast Files)
extern hook::refs::Ref<> DB_LinkWeapon;
// DB_LinkXAssetEntry (Fast Files)
extern hook::refs::Ref<> DB_LinkXAssetEntry;
// DB_LoadXFileData (Fast Files)
extern hook::refs::Ref<> DB_LoadXFileData;
// DB_PopStreamPos (Fast Files)
extern hook::refs::Ref<> DB_PopStreamPos;
// DB_PushStreamPos (Fast Files)
extern hook::refs::Ref<> DB_PushStreamPos;
// Load_Stream (Fast Files)
extern hook::refs::Ref<> Load_Stream;
// Load_XAsset (Fast Files)
extern hook::refs::Ref<> Load_XAsset;
// Load_XStringCustom (Fast Files)
extern hook::refs::Ref<> Load_XStringCustom;
// PMem_Alloc (Fast Files)
extern hook::refs::Ref<> PMem_Alloc;
// XAsset pools (Fast Files)
extern hook::refs::Ref<XAssetPool> xassetpool;

/*
 * Gsc
 */

// Link a gsc script (Gsc)
extern hook::refs::Ref<void (scriptInstance_t inst, CWXHash scriptname)> Scr_GscObjLink;
// Linked GSC objects (Gsc)
extern hook::refs::Ref<objFileInfo_t[scriptInstance_t::SI_COUNT][800]> gObjFileInfo;
// Linked GSC objects count (Gsc)
extern hook::refs::Ref<uint32_t> gObjFileInfoCount;
// OPCODE jump table (Gsc)
extern hook::refs::Ref<VM_OP_FUNC> gVmOpJumpTable;

/*
 * Lua
 */

// cod_lua_setxhash (Lua)
extern hook::refs::Ref<> cod_lua_setxhash;
// lj_cf_string_dump (Lua)
extern hook::refs::Ref<> lj_cf_string_dump;
// lua_loadx (Lua)
extern hook::refs::Ref<> lua_loadx;
// lua_newstate (Lua)
extern hook::refs::Ref<> lua_newstate;
// lua_tolstring (Lua)
extern hook::refs::Ref<> lua_tolstring;
// writer_buf (Lua)
extern hook::refs::Ref<> writer_buf;

/*
 * @return the common fastfile names
 */
std::span<const char*> GetCommonFastFiles();

/*
 * Load the scans for the game
 * @param scan game
 */
void LoadScans(hook::scan_container::ScanContainer& scan);
