// autogenerated file from cw.json, do not edit this file

// common fastfiles names
std::span<const char*> GetCommonFastFiles() {
    static const char* files[] { 
        "zone/core_common.ff",
        "zone/cp_common.ff",
        "zone/mp_common.ff",
        "zone/zm_common.ff",
    };
    return files;
}

// refs

// DecryptString
hook::refs::Ref<const char* (const char* str)> DecryptString{};

// $UnkNavMesh
hook::refs::Ref<> $UnkNavMesh{};
// DB_AllocStreamPos
hook::refs::Ref<> DB_AllocStreamPos{};
// DB_AllocXBlocks
hook::refs::Ref<> DB_AllocXBlocks{};
// DB_ConvertOffsetToPointer
hook::refs::Ref<> DB_ConvertOffsetToPointer{};
// DB_FindXAssetHeader
hook::refs::Ref<XAssetHeader (XAssetType type, CWXHash name, bool inv, int timeout)> DB_FindXAssetHeader{};
// DB_GetXAssetTypeSize
hook::refs::Ref<> DB_GetXAssetTypeSize{};
// DB_IncStreamPos
hook::refs::Ref<> DB_IncStreamPos{};
// DB_InitStreams
hook::refs::Ref<> DB_InitStreams{};
// DB_LinkAttachmentUnique
hook::refs::Ref<> DB_LinkAttachmentUnique{};
// DB_LinkDestructibleDef
hook::refs::Ref<> DB_LinkDestructibleDef{};
// DB_LinkDynModel
hook::refs::Ref<> DB_LinkDynModel{};
// DB_LinkSoundBank
hook::refs::Ref<> DB_LinkSoundBank{};
// DB_LinkWeapon
hook::refs::Ref<> DB_LinkWeapon{};
// DB_LinkXAssetEntry
hook::refs::Ref<> DB_LinkXAssetEntry{};
// DB_LoadXFileData
hook::refs::Ref<> DB_LoadXFileData{};
// DB_PopStreamPos
hook::refs::Ref<> DB_PopStreamPos{};
// DB_PushStreamPos
hook::refs::Ref<> DB_PushStreamPos{};
// Load_Stream
hook::refs::Ref<> Load_Stream{};
// Load_XAsset
hook::refs::Ref<> Load_XAsset{};
// Load_XStringCustom
hook::refs::Ref<> Load_XStringCustom{};
// PMem_Alloc
hook::refs::Ref<> PMem_Alloc{};
// xassetpool
hook::refs::Ref<XAssetPool> xassetpool{};

// Scr_GscObjLink
hook::refs::Ref<void (scriptInstance_t inst, CWXHash scriptname)> Scr_GscObjLink{};
// gObjFileInfo
hook::refs::Ref<objFileInfo_t[scriptInstance_t::SI_COUNT][800]> gObjFileInfo{};
// gObjFileInfoCount
hook::refs::Ref<uint32_t> gObjFileInfoCount{};
// gVmOpJumpTable
hook::refs::Ref<VM_OP_FUNC> gVmOpJumpTable{};

// cod_lua_setxhash
hook::refs::Ref<> cod_lua_setxhash{};
// lj_cf_string_dump
hook::refs::Ref<> lj_cf_string_dump{};
// lua_loadx
hook::refs::Ref<> lua_loadx{};
// lua_newstate
hook::refs::Ref<> lua_newstate{};
// lua_tolstring
hook::refs::Ref<> lua_tolstring{};
// writer_buf
hook::refs::Ref<> writer_buf{};

constinit static hook::generated_scan_runtime::ScanInformation scans[] { 
    {
        .id = "common.DecryptString",
        .scan = "48 89 5C 24 ? 48 89 6C 24 ? 48 89 74 24 ? 57 41 54 41 55 41 56 41 57 48 83 EC ? 48 8B D9 0F B6",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .multiple = false,
        .ref = (void**)&DecryptString.ptr
    },
    {
        .id = "fastfile.$UnkNavMesh",
        .scan = "E8 ?? ?? ?? ?? 8B F0 83 FD",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 1,
        .postOffset = 0,
        .single = true,
        .multiple = false,
        .ref = (void**)&$UnkNavMesh.ptr
    },
    {
        .id = "fastfile.DB_AllocStreamPos",
        .scan = "4C 8B 05 ? ? ? ? 48 63 D1 48",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .multiple = false,
        .ref = (void**)&DB_AllocStreamPos.ptr
    },
    {
        .id = "fastfile.DB_AllocXBlocks",
        .scan = "40 55 56 57 41 54 41 55 41 56 41 57 B8 ? ? ? ? E8 ? ? ? ? 48 2B E0 48 8B 05 ? ? ? ? 48 33 C4 48 89 84 24 ? ? ? ? 8B",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .multiple = false,
        .ref = (void**)&DB_AllocXBlocks.ptr
    },
    {
        .id = "fastfile.DB_ConvertOffsetToPointer",
        .scan = "4C 8B 01 49 FF C8 49 8B C0 48 C1 E8 ? 48 8D 14 40 48 B8 FF FF FF FF FF FF FF 0F 4C 23 C0 48 8B 05 ? ? ? ? 4C",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .multiple = false,
        .ref = (void**)&DB_ConvertOffsetToPointer.ptr
    },
    {
        .id = "fastfile.DB_FindXAssetHeader",
        .scan = "48 89 74 24 ? 55 57 41 54 41 56 41 57 48 8D AC 24 80 D0",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .multiple = false,
        .ref = (void**)&DB_FindXAssetHeader.ptr
    },
    {
        .id = "fastfile.DB_GetXAssetTypeSize",
        .scan = "0F B6 C1 48 8D 0C 80 48 8D 05 ? ? ? ? 8B",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .multiple = false,
        .ref = (void**)&DB_GetXAssetTypeSize.ptr
    },
    {
        .id = "fastfile.DB_IncStreamPos",
        .scan = "48 01 0D ? ? ? ? C3",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .multiple = false,
        .ref = (void**)&DB_IncStreamPos.ptr
    },
    {
        .id = "fastfile.DB_InitStreams",
        .scan = "33 D2 48 89 0D ? ? ? ? 48",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .multiple = false,
        .ref = (void**)&DB_InitStreams.ptr
    },
    {
        .id = "fastfile.DB_LinkAttachmentUnique",
        .scan = "48 89 5C 24 ? 57 48 83 EC ? 48 89 6C 24 ? 48 8B D9",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .multiple = false,
        .ref = (void**)&DB_LinkAttachmentUnique.ptr
    },
    {
        .id = "fastfile.DB_LinkDestructibleDef",
        .scan = "E8 ? ? ? ? E8 ? ? ? ? 48 83 7B ? ? 74 37",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 1,
        .postOffset = 0,
        .single = true,
        .multiple = false,
        .ref = (void**)&DB_LinkDestructibleDef.ptr
    },
    {
        .id = "fastfile.DB_LinkDynModel",
        .scan = "E8 ? ? ? ? E8 ? ? ? ? 48 8D 4B ? E8 ? ? ? ? 48 83 C3",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 1,
        .postOffset = 0,
        .single = true,
        .multiple = false,
        .ref = (void**)&DB_LinkDynModel.ptr
    },
    {
        .id = "fastfile.DB_LinkSoundBank",
        .scan = "48 89 5C 24 ? 57 48 83 EC ? 48 8B 11 48 8B F9 B1",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .multiple = false,
        .ref = (void**)&DB_LinkSoundBank.ptr
    },
    {
        .id = "fastfile.DB_LinkWeapon",
        .scan = "48 89 5C 24 ? 48 89 74 24 ? 57 48 83 EC ? 48 8B F9 84 D2 75 0D 48 8B 11 B1 ? E8 ? ? ? ? 48 89 07 48 8B 3F 48 8D 9F ? ? ? ?",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .multiple = false,
        .ref = (void**)&DB_LinkWeapon.ptr
    },
    {
        .id = "fastfile.DB_LinkXAssetEntry",
        .scan = "48 89 5C 24 ? 55 56 57 41 54 41 55 41 56 41 57 B8 ? ? ? ? E8 ? ? ? ? 48 2B E0 48 8B 05 ? ? ? ? 48 33 C4 48 89 84 24 ? ? ? ? 48 8B EA",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .multiple = false,
        .ref = (void**)&DB_LinkXAssetEntry.ptr
    },
    {
        .id = "fastfile.DB_LoadXFileData",
        .scan = "85 D2 0F 8E 45 01 00 00 41",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .multiple = false,
        .ref = (void**)&DB_LoadXFileData.ptr
    },
    {
        .id = "fastfile.DB_PopStreamPos",
        .scan = "44 8B 05 ? ? ? ? 4C 8D 0D ? ? ? ? 48 63",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .multiple = false,
        .ref = (void**)&DB_PopStreamPos.ptr
    },
    {
        .id = "fastfile.DB_PushStreamPos",
        .scan = "40 53 48 83 EC 20 8B D9 83 F9 09",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .multiple = false,
        .ref = (void**)&DB_PushStreamPos.ptr
    },
    {
        .id = "fastfile.Load_Stream",
        .scan = "48 89 5C 24 ? 57 48 83 EC ? 49 8B D8 4C 8B CA 40 B7 ? 84 C9 74 46 48 85 DB 74 41 48 63 05 ? ? ? ? 83 F8 ? 77 2D 48 8D 15 71",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .multiple = false,
        .ref = (void**)&Load_Stream.ptr
    },
    {
        .id = "fastfile.Load_XAsset",
        .scan = "E8 ? ? ? ? 48 83 C3 ? 8D 4E ? E8 ? ? ? ? 8B F1 84 C0 75 06",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 1,
        .postOffset = 0,
        .single = true,
        .multiple = false,
        .ref = (void**)&Load_XAsset.ptr
    },
    {
        .id = "fastfile.Load_XStringCustom",
        .scan = "E8 ? ? ? ? EB 08 48 8B CF E8 ? ? ? ? 33 C9",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 1,
        .postOffset = 0,
        .single = true,
        .multiple = false,
        .ref = (void**)&Load_XStringCustom.ptr
    },
    {
        .id = "fastfile.PMem_Alloc",
        .scan = "44 89 4C 24 ? 4C 89 44 24 ? 48 89 54 24 ? 48 89 4C 24 ? 57",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .multiple = false,
        .ref = (void**)&PMem_Alloc.ptr
    },
    {
        .id = "fastfile.xassetpool",
        .scan = "48 8D 05 ? ? ? ? 48 C1 E2 ? 48 03 D0",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 3,
        .postOffset = 0,
        .single = true,
        .multiple = false,
        .ref = (void**)&xassetpool.ptr
    },
    {
        .id = "gsc.Scr_GscObjLink",
        .scan = "48 89 5C 24 ? 55 56 57 41 54 41 55 41 56 41 57 48 83 EC ? 48 8B DA 4C",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .multiple = false,
        .ref = (void**)&Scr_GscObjLink.ptr
    },
    {
        .id = "gsc.gObjFileInfo",
        .scan = "4C 8D 2D ? ? ? ? 48 8D 15 ? ? ? ? 43 39 4C B5 00",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 10,
        .postOffset = 0,
        .single = true,
        .multiple = false,
        .ref = (void**)&gObjFileInfo.ptr
    },
    {
        .id = "gsc.gObjFileInfoCount",
        .scan = "4C 8D 2D ? ? ? ? 48 8D 15 ? ? ? ? 43 39 4C B5 00",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 3,
        .postOffset = 0,
        .single = true,
        .multiple = false,
        .ref = (void**)&gObjFileInfoCount.ptr
    },
    {
        .id = "gsc.gVmOpJumpTable",
        .scan = "41 FF 94 FC ? ? ? ? 80 7C 24",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 4,
        .postOffset = 0,
        .single = true,
        .multiple = false,
        .ref = (void**)&gVmOpJumpTable.ptr
    },
    {
        .id = "lua.cod_lua_setxhash",
        .scan = "E8 ?? ?? ?? ?? 48 8D 15 ?? ?? ?? ?? 48 8B CB E8 ?? ?? ?? ?? 45 33 C9",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 1,
        .postOffset = 0,
        .single = true,
        .multiple = false,
        .ref = (void**)&cod_lua_setxhash.ptr
    },
    {
        .id = "lua.lj_cf_string_dump",
        .scan = "48 89 5C 24 08 57 48 83 EC 30 BA 01 00 00 00 48 8B D9 E8 ?? ?? ?? ?? 48",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .multiple = false,
        .ref = (void**)&lj_cf_string_dump.ptr
    },
    {
        .id = "lua.lua_loadx",
        .scan = "E8 ?? ?? ?? ?? 41 B8 ?? ?? ?? ?? 8B D0 48 8B CB 48 8B 7C 24 ?? 48 8B 74 24",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 1,
        .postOffset = 0,
        .single = true,
        .multiple = false,
        .ref = (void**)&lua_loadx.ptr
    },
    {
        .id = "lua.lua_newstate",
        .scan = "E8 ?? ?? ?? ?? 48 8B D8 48 85 C0 0F 84 92 01 00 00",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 1,
        .postOffset = 0,
        .single = true,
        .multiple = false,
        .ref = (void**)&lua_newstate.ptr
    },
    {
        .id = "lua.lua_tolstring",
        .scan = "E8 ?? ?? ?? ?? 41 BF ?? ?? ?? ?? 48 8B CD",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 1,
        .postOffset = 0,
        .single = true,
        .multiple = false,
        .ref = (void**)&lua_tolstring.ptr
    },
    {
        .id = "lua.writer_buf",
        .scan = "4C 8D 05 ?? ?? ?? ?? 89 4C 24 20 48 83 EA 68",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 3,
        .postOffset = 0,
        .single = true,
        .multiple = false,
        .ref = (void**)&writer_buf.ptr
    },
};

void LoadScans(hook::scan_container::ScanContainer& scan) {
    hook::generated_scan_runtime::LoadScans(scan, scans, ACTS_ARRAYSIZE(scans));
}
