#include <includes.hpp>
#include <tools/ff/handlers/handler_game_bo4.hpp>
#include <tools/utils/raw_file_extractor.hpp>
#include <tools/utils/data_utils.hpp>

namespace {
	using namespace fastfile::handlers::bo4;
	using namespace games::bo4::pool;
	class ImplWorker : public Worker {
		void Unlink(fastfile::FastFileOption& opt, void* ptr) {
			struct WeaponDefObj21329beb {
				XModel* model;
				uint64_t unk8;
				uint64_t unk10;
				uint64_t unk18;
				uint64_t unk20;
				uint64_t unk28;
				uint64_t unk30;
				uint64_t unk38;
				uint64_t unk40;
			};

			struct WeaponDef {
				XHash name;
				XHash baseWeapon;
				XHash displayname;
				XHash unk30;
				XHash unk40;
				XHash unk50;
				XHash unk60;
				XHash unk70;
				XHash streamkey;
				XHash sound90;
				XHash sounda0;
				XHash soundb0;
				XHash soundc0;
				XHash firesounddistant;
				XHash firesound;
				XHash firesoundplayer;
				XHash sound100;
				XHash sound110;
				XHash sound120;
				XHash sound130;
				XHash sound140;
				XHash sound150;
				XHash sound160;
				XHash sound170;
				XHash sound180;
				XHash sound190;
				XHash sound1a0;
				XHash sound1b0;
				XHash sound1c0;
				XHash sound1d0;
				XHash sound1e0;
				XHash sound1f0;
				XHash sound200;
				XHash sound210;
				XHash sound220;
				XHash sound230;
				XHash sound240;
				XHash sound250;
				XHash sound260;
				XHash sound270;
				XHash sound280;
				XHash sound290;
				XHash sound2a0;
				XHash sound2b0;
				XHash sound2c0;
				XHash sound2d0;
				XHash sound2e0;
				XHash sound2f0;
				XHash sound300;
				XHash sound310;
				XHash sound320;
				XHash sound330;
				XHash sound340;
				XHash sound350;
				XHash sound360;
				XHash sound370;
				XHash sound380;
				XHash gadgetreadysound;
				XHash var_1f7ccc3b;
				XHash sound3b0;
				XHash sound3c0;
				XHash sound3d0;
				XHash sound3e0;
				XHash sound3f0;
				XHash sound400;
				XHash sound410;
				XHash gadgetreadysoundplayer;
				XHash var_fb22040b;
				XHash sound440;
				XHash sound450;
				XHash sound460;
				XHash sound470;
				XHash sound480;
				XHash sound490;
				XHash sound4a0;
				XHash sound4b0;
				XHash sound4c0;
				XHash sound4d0;
				XHash sound4e0;
				XHash sound4f0;
				XHash sound500;
				XHash sound510;
				XHash sound520;
				XHash sound530;
				XHash sound540;
				XHash sound550;
				XHash sound560;
				XHash sound570;
				XHash sound580;
				XHash sound590;
				XHash sound5a0;
				XHash sound5b0;
				XHash sound5c0;
				XHash sound5d0;
				XHash sound5e0;
				XHash sound5f0;
				XHash sound600;
				XHash sound610;
				XHash sound620;
				XHash sound630;
				XHash sound640;
				XHash sound650;
				XHash sound660;
				XHash sound670;
				XHash sound680;
				XHash sound690;
				XHash sound6a0;
				XHash sound6b0;
				XHash sound6c0;
				XHash lockonseekersearchsound;
				XHash lockonseekerlockedsound;
				XHash lockontargetlockedsound;
				XHash lockontargetfiredonsound;
				XHash sound710;
				XHash sound720;
				XHash sound730;
				XHash sound740;
				XHash var_8a03df2b;
				XHash var_2f3ca476;
				XHash var_5c29f743;
				XHash projexplosionsound;
				XHash projexplosionsoundplayer;
				XHash projsmokestartsound;
				XHash projsmokeloopsound;
				XHash projsmokeendsound;
				XHash sound7d0;
				XHash sound7e0;
				XHash sound7f0;
				XHash sound800;
				XHash sound810;
				XHash sound820;
				XHash sound830;
				XHash sound840;
				XHash sound850;
				XHash sound860;
				XHash hitsound;
				XHash sound880;
				XHash sound890;
				uint64_t unk8a0;
				uint64_t unk8a8;
				const char* luigiReticleWidget;
				XAnim** unk8b8;
				XAnim** unk8c0;
				ScrString_t(*unk8c8)[64];
				ScrString_t(*unk8d0)[64];
				ScrString_t(*unk8d8)[2];
				uint64_t unk8e0;
				XCam* cacWeaponXCam;
				XCam* cacAttachmentsXCam;
				XCam* weaponIconXCam;
				uint64_t unk900;
				uint64_t unk908;
				uint64_t unk910;
				uint64_t unk918;
				uint64_t unk920;
				uint64_t unk928;
				TagFxSet* unk930;
				vec2_t* accuracyGraphKnots[2];
				uint64_t unk948;
				uint64_t unk950;
				uint64_t unk958;
				uint64_t unk960;
				uint64_t unk968;
				int32_t var_6566504b;
				uint32_t unk974;
				uint64_t unk978;
				uint64_t unk980[4];
				uint64_t unk9a0;
				uint64_t unk9a8;
				uint64_t unk9b0;
				uint64_t unk9b8;
				uint64_t unk9c0;
				uint64_t unk9c8;
				uint64_t unk9d0;
				uint64_t unk9d8;
				uint64_t unk9e0;
				uint64_t unk9e8;
				uint64_t unk9f0;
				uint64_t unk9f8;
				uint64_t unka00;
				uint64_t unka08;
				uint64_t unka10;
				uint64_t unka18;
				uint64_t unka20;
				WeaponCamo* weaponCamo;
				uint64_t unka30;
				uint64_t unka38;
				WeaponAttachment (*attachments)[64];
				WeaponAttachmentUnique (*attachmentUniques)[128];
				uint64_t unka50;
				WeaponTunables* tunables1;
				WeaponTunables* tunables2;
				XAnim* unka68;
				XModel** viewmodel;
				XModel** frontendmodel;
				XModel* handModel;
				uint64_t unka88;
				uint64_t unka90;
				uint64_t unka98;
				uint64_t unkaa0;
				uint64_t unkaa8;
				uint64_t unkab0;
				uint64_t unkab8;
				uint64_t unkac0;
				uint64_t unkac8;
				uint64_t unkad0;
				uint64_t unkad8;
				uint64_t unkae0;
				uint64_t unkae8;
				uint64_t unkaf0;
				uint64_t unkaf8;
				uint64_t unkb00;
				uint64_t unkb08;
				uint64_t unkb10;
				uint64_t unkb18;
				uint64_t unkb20;
				uint64_t unkb28;
				uint64_t unkb30;
				uint64_t unkb38;
				uint64_t unkb40;
				uint64_t unkb48;
				uint64_t unkb50;
				uint64_t unkb58;
				uint64_t unkb60;
				uint64_t unkb68;
				uint64_t unkb70;
				uint64_t unkb78;
				uint64_t unkb80;
				uint64_t unkb88;
				uint64_t unkb90;
				uint64_t unkb98;
				uint64_t unkba0;
				uint64_t unkba8;
				uint64_t unkbb0;
				uint64_t unkbb8;
				uint64_t unkbc0;
				FxEffectDef* unkbc8;
				FxEffectDef* unkbd0;
				FxEffectDef* unkbd8;
				FxEffectDef* unkbe0;
				FxEffectDef* unkbe8;
				TagFxSet* viewPersistentEffectSet;
				TagFxSet* worldPersistentEffectSet;
				TagFxSet* enemyDeathFxSet;
				FxEffectDef* unkc08;
				SharedWeaponSounds* sharedWeaponSounds;
				uint64_t unkc18;
				TagFxSet* tagFXSetFirstPerson[4];
				TagFxSet* tagFXSetThirdPerson[4];
				GfxImage* gadgetIconAvailable;
				GfxImage* gadgetIconUnavailable;
				GfxImage* unkc70;
				GfxImage* unkc78;
				FxEffectDef* unkc80;
				FxEffectDef* unkc88;
				FxEffectDef* unkc90;
				FxEffectDef* unkc98;
				FxEffectDef* unkca0;
				FxEffectDef* unkca8;
				GfxImage* reticleCenter;
				GfxImage* reticleSide;
				uint64_t unkcc0;
				XModel** worldModel;
				XModel** unkcd0;
				XModel** stowedmodel;
				XModel** clipmodel;
				XHash* unkce8;
				XHash* unkcf0;
				GfxImage** unkcf8;
				GfxImage** unkd00;
				GfxImage** unkd08;
				XHash* unkd10;
				uint64_t unkd18;
				uint64_t unkd20;
				XModel* unkd28;
				XModel* var_22082a57;
				GfxImage* inventoryIcon;
				GfxImage* inventoryIconZm;
				GfxImage* hudIcon;
				GfxImage* reticleSeekingLockOn;
				GfxImage* reticleLockOn;
				Material* reticlePivotLocked;
				Material* reticlePivotInvalid;
				Material* reticlePivotTarget;
				Material* reticlePivotSides;
				Material* reticlePivotLine;
				GfxImage* unkd88;
				GfxImage* unkd90;
				GfxImage* unkd98;
				GfxImage* unkda0;
				GfxImage* unkda8;
				GfxImage* unkdb0;
				GfxImage* unkdb8;
				RumbleInfo* fireRumble;
				RumbleInfo* unkdc8;
				RumbleInfo* unkdd0;
				RumbleInfo* meleeImpactRumble;
				RumbleInfo* unkde0;
				RumbleInfo* unkde8;
				RumbleInfo* unkdf0;
				RumbleInfo* unkdf8;
				RumbleInfo* unke00;
				RumbleInfo* unke08;
				RumbleInfo* unke10;
				RumbleInfo* unke18;
				RumbleInfo* unke20;
				RumbleInfo* unke28;
				LaserDef* unke30;
				LaserDef* unke38;
				LaserDef* unke40;
				FlameTable* flameTableFirstPerson;
				FlameTable* flameTableThirdPerson;
				BeamDef* unke58;
				BeamDef* unke60;
				BeamDef* unke68;
				BeamDef* unke70;
				BeamDef* unke78;
				BeamDef* unke80;
				BeamDef* unke88;
				GfxImage* unke90;
				GfxImage* unke98;
				GfxImage* unkea0;
				BallisticDesc* ballisticDesc;
				GfxImage* unkeb0;
				Objective* weaponHeadObjective;
				Objective* crateObjective;
				XModel* projectilemodel;
				XModel* projectileModelEnemy;
				FxEffectDef* unked8;
				FxEffectDef* unkee0;
				FxEffectDef* unkee8;
				FxEffectDef* unkef0;
				XModel* var_4bcd08b0;
				FxEffectDef* unkf00;
				FxEffectDef* unkf08;
				FxEffectDef* unkf10;
				FxEffectDef* unkf18;
				FxEffectDef* underwaterExplosionSurfaceFX[3];
				FxEffectDef* unkf38;
				FxEffectDef* unkf40;
				FxEffectDef* unkf48;
				FxEffectDef* unkf50;
				FxEffectDef* unkf58;
				FxEffectDef* unkf60;
				FxEffectDef* unkf68;
				FxEffectDef* unkf70;
				TagFxSet* var_96850284;
				TagFxSet* var_26f68e75;
				FxEffectDef* unkf88;
				FxEffectDef* unkf90;
				FxEffectDef* unkf98;
				FxEffectDef* unkfa0;
				uint64_t unkfa8;
				uint64_t unkfb0;
				FxImpactTable* normalImpactFX;
				FxImpactTable* exitImpactFX;
				FxImpactTable* bounceImpactFX;
				FxImpactTable* dudImpactFX;
				FxImpactTable* unkfd8;
				SoundsImpactTable* normalImpactSounds;
				SoundsImpactTable* exitImpactSounds;
				SoundsImpactTable* bounceImpactSounds;
				SoundsImpactTable* dudImpactSounds;
				SoundsImpactTable* unk1000;
				ScriptBundle* unk1008;
				ScriptBundle* turretAnimSettings;
				ScriptBundle* killcamSettings;
				ScriptBundle* customsettings;
				ScriptBundle* shrapnelsettings;
				ScriptBundle* var_2e4a8800;
				GfxImage* unk1038;
				GfxImage* unk1040;
				GfxImage* unk1048;
				ScriptBundle* var_8456d4d;
				uint64_t unk1058;
				uint64_t unk1060;
				uint64_t unk1068;
				uint64_t unk1070;
				uint64_t unk1078;
				uint64_t unk1080;
				uint64_t unk1088;
				uint64_t unk1090;
				uint64_t unk1098;
				uint64_t unk10a0;
				uint64_t unk10a8;
				uint64_t unk10b0;
				uint64_t unk10b8;
				uint64_t unk10c0;
				uint64_t unk10c8;
				uint64_t unk10d0;
				uint64_t unk10d8;
				uint64_t unk10e0;
				uint64_t unk10e8;
				uint64_t unk10f0;
				uint64_t unk10f8;
				uint64_t unk1100;
				uint64_t unk1108;
				uint64_t unk1110;
				uint64_t unk1118;
				uint64_t unk1120;
				uint64_t unk1128;
				uint64_t unk1130;
				uint64_t unk1138;
				uint64_t unk1140;
				uint64_t unk1148;
				uint64_t unk1150;
				uint64_t unk1158;
				uint64_t unk1160;
				uint64_t unk1168;
				uint64_t unk1170;
				uint64_t unk1178;
				uint32_t unk1180;
				ScrString_t worldModelTagRight;
				ScrString_t worldModelTagLeft;
				ScrString_t unk118c;
				ScrString_t unk1190;
				ScrString_t stowedModelTag;
				ScrString_t unk1198;
				ScrString_t unk119c;
				ScrString_t unk11a0;
				ScrString_t unk11a4;
				ScrString_t unk11a8;
				ScrString_t unk11ac;
				ScrString_t unk11b0;
				ScrString_t unk11b4;
				uint64_t unk11b8;
				uint64_t unk11c0;
				uint64_t unk11c8;
				uint64_t unk11d0;
				uint64_t unk11d8;
				uint64_t unk11e0;
				uint64_t unk11e8;
				uint64_t unk11f0;
				uint64_t unk11f8;
				uint64_t unk1200;
				uint64_t unk1208;
				uint64_t unk1210;
				uint64_t unk1218;
				uint64_t unk1220;
				uint64_t unk1228;
				uint64_t unk1230;
				uint64_t unk1238;
				uint64_t unk1240;
				uint64_t unk1248;
				uint64_t unk1250;
				uint64_t unk1258;
				uint64_t unk1260;
				uint64_t unk1268;
				uint64_t unk1270;
				uint64_t unk1278;
				uint64_t unk1280;
				uint64_t unk1288;
				uint64_t unk1290;
				uint64_t unk1298;
				uint64_t unk12a0;
				uint64_t unk12a8;
				uint64_t unk12b0;
				uint64_t unk12b8;
				uint64_t unk12c0;
				uint64_t unk12c8;
				uint64_t unk12d0;
				uint64_t unk12d8;
				uint64_t unk12e0;
				uint64_t unk12e8;
				uint64_t unk12f0;
				uint64_t unk12f8;
				uint32_t unk1300;
				float weaponheadobjectiveheight;
				uint64_t unk1308;
				uint64_t unk1310;
				uint64_t unk1318;
				uint64_t unk1320;
				uint64_t unk1328;
				uint64_t unk1330;
				uint64_t unk1338;
				eModes sessionMode;
				uint32_t unk1344;
				uint64_t unk1348;
				int32_t var_5b73038c;
				uint32_t unk1354;
				int itemIndex;
				uint32_t unk135c;
				uint64_t unk1360;
				uint32_t unk1368;
				int32_t weaponstarthitpoints;
				uint64_t unk1370;
				int32_t soundrattlerangemin;
				int32_t soundrattlerangemax;
				uint32_t unk1380;
				int accuracyGraphKnotCount[2];
				uint64_t unk1390;
				uint64_t unk1398;
				uint64_t unk13a0;
				uint64_t unk13a8;
				uint32_t unk13b0;
				uint32_t grenadeweapon;
				uint32_t unk13b8;
				uint32_t dualwieldweapon;
				uint32_t unk13c0;
				uint32_t dualWieldWeaponIndex;
				uint32_t altWeaponIndex;
				uint32_t unk13cc;
				uint32_t unk13d0;
				byte var_50d2316b;
				byte var_83b1dc1;
				uint16_t unk13d6;
				byte unk13d8;
				bool bDrawOffhandModelInHand;
				uint16_t unk13da;
				bool lockonseekersearchsoundloops;
				bool lockonseekerlockedsoundloops;
				bool lockontargetlockedsoundloops;
				bool lockontargetfiredonsoundloops;
				uint32_t unk13e0;
				byte var_965cc0b3;
				byte unk13e5;
				uint16_t unk13e6;
				uint16_t unk13e8;
				byte forcedamageshellshockandrumble;
				byte unk13eb;
				uint32_t unk13ec;
				uint32_t unk13f0;
				byte var_2cf49821;
				byte var_d2751f9d;
				byte var_554be9f7;
				byte unk13f7;
				uint64_t unk13f8;
				uint64_t unk1400;
				uint64_t unk1408;
				uint64_t unk1410;
				uint64_t unk1418;
				uint64_t unk1420;
				uint64_t unk1428;
				WeaponDefObj21329beb var_21329beb[4];
			};
			static_assert(sizeof(WeaponDef) == 0x1550);
			WeaponDef* asset{ (WeaponDef*)ptr };

			// refs
			constexpr size_t postWeaponDefNameField = offsetof(WeaponDef, name) + sizeof(WeaponDef::name);
			constexpr size_t testLen = sizeof(WeaponDef) - postWeaponDefNameField;
			
			if (utils::data::IsNulled(&((byte*)ptr)[postWeaponDefNameField], testLen)) {
				LOG_INFO("ignore empty weapondef {}", hashutils::ExtractTmp("file", asset->name.name));
				return;
			}

			const char* baseWeaponStr{ hashutils::ExtractPtr(asset->baseWeapon) };

			if (baseWeaponStr) {
				// load default hashes
				static const char* suffixes[]{
					"_wz", "_zm", "_mp", "_cp", // gamemode values
					"_gold", "_operator", // wz weapons
					"_tunables", "_tunables_wz", "_tunables_zm", "_tunables_mp", // tunables
				};
				static const char* prefixes[]{
					"weapon/" // localize
				};

				for (const char* suffix : suffixes) {
					const char* s{ utils::va("%s%s", baseWeaponStr, suffix) };
					hashutils::AddPrecomputed(hash::Hash64(s), s, true);
				}

				for (const char* prefix : prefixes) {
					const char* s{ utils::va("%s%s", prefix, baseWeaponStr) };
					hashutils::AddPrecomputed(hash::Hash64(s), s, true);
				}
			}

			std::filesystem::path outFile{ opt.m_output / "bo4" / "source" / "tables" / "weapon" 
				/ fastfile::GetCurrentContext().ffname
				/ std::format("{}.json", hashutils::ExtractTmp("file", asset->name.name)) };
			std::filesystem::create_directories(outFile.parent_path());

			BO4JsonWriter json{};

			LOG_INFO("Dump weapon {}", outFile.string());


			json.BeginObject();
			{
				
				json.WriteFieldValueXHash("name", asset->name);
				json.WriteFieldValueXHash("baseWeapon", asset->baseWeapon);
				json.WriteFieldValueXHash("displayname", asset->displayname);

				json.WriteFieldValueXHash("xhash_30", asset->unk30);
				json.WriteFieldValueXHash("xhash_40", asset->unk40);
				json.WriteFieldValueXHash("xhash_50", asset->unk50);
				json.WriteFieldValueXHash("xhash_60", asset->unk60);
				json.WriteFieldValueXHash("xhash_70", asset->unk70);
				if (asset->luigiReticleWidget && *asset->luigiReticleWidget) {
					json.WriteFieldValueString("luigiReticleWidget", asset->luigiReticleWidget);
				}
				json.WriteFieldValueXHash("streamkey", asset->streamkey);

				json.WriteFieldValueScrStringArray("scrstr_8c8", ARRAYSIZE(*asset->unk8c8), *asset->unk8c8);
				json.WriteFieldValueScrStringArray("scrstr_8d0", ARRAYSIZE(*asset->unk8d0), *asset->unk8d0);
				json.WriteFieldValueScrStringArray("scrstr_8d8", ARRAYSIZE(*asset->unk8d8), *asset->unk8d8);

				json.WriteFieldValueScrString("worldModelTagRight", asset->worldModelTagRight);
				json.WriteFieldValueScrString("worldModelTagLeft", asset->worldModelTagLeft);
				json.WriteFieldValueScrString("scrstr_118c", asset->unk118c);
				json.WriteFieldValueScrString("scrstr_1190", asset->unk1190);
				json.WriteFieldValueScrString("stowedModelTag", asset->stowedModelTag);
				json.WriteFieldValueScrString("scrstr_1198", asset->unk1198);
				json.WriteFieldValueScrString("scrstr_119c", asset->unk119c);
				json.WriteFieldValueScrString("scrstr_11a0", asset->unk11a0);
				json.WriteFieldValueScrString("scrstr_11a4", asset->unk11a4);
				json.WriteFieldValueScrString("scrstr_11a8", asset->unk11a8);
				json.WriteFieldValueScrString("scrstr_11ac", asset->unk11ac);
				json.WriteFieldValueScrString("scrstr_11b0", asset->unk11b0);
				json.WriteFieldValueScrString("scrstr_11b4", asset->unk11b4);

				json.WriteFieldValueNumber("weaponstarthitpoints", asset->weaponstarthitpoints);
				json.WriteFieldValueNumber("soundrattlerangemin", asset->soundrattlerangemin);
				json.WriteFieldValueNumber("soundrattlerangemax", asset->soundrattlerangemax);
				json.WriteFieldValueNumber("grenadeweapon", asset->grenadeweapon);
				json.WriteFieldValueNumber("dualwieldweapon", asset->dualwieldweapon);
				json.WriteFieldValueNumber("dualWieldWeaponIndex", asset->dualWieldWeaponIndex);
				json.WriteFieldValueNumber("altWeaponIndex", asset->altWeaponIndex);
				json.WriteFieldValueNumber("itemIndex", asset->itemIndex);
				json.WriteFieldValueNumber(0x5b73038c, asset->var_5b73038c);
				json.WriteFieldValueNumber("weaponheadobjectiveheight", asset->weaponheadobjectiveheight);
				json.WriteFieldValueString("sessionMode", GetEModeName(asset->sessionMode));
				json.WriteFieldValueBool("bDrawOffhandModelInHand", asset->bDrawOffhandModelInHand);
				json.WriteFieldValueBool("lockonseekersearchsoundloops", asset->lockonseekersearchsoundloops);
				json.WriteFieldValueBool("lockonseekerlockedsoundloops", asset->lockonseekerlockedsoundloops);
				json.WriteFieldValueBool("lockontargetlockedsoundloops", asset->lockontargetlockedsoundloops);
				json.WriteFieldValueBool(0x965cc0b3, asset->var_965cc0b3);
				json.WriteFieldValueBool("lockontargetfiredonsoundloops", asset->lockontargetfiredonsoundloops);
				json.WriteFieldValueBool("forcedamageshellshockandrumble", asset->forcedamageshellshockandrumble);

				json.WriteFieldValueXHash("sound90", asset->sound90);
				json.WriteFieldValueXHash("sounda0", asset->sounda0);
				json.WriteFieldValueXHash("soundb0", asset->soundb0);
				json.WriteFieldValueXHash("soundc0", asset->soundc0);
				json.WriteFieldValueXHash("firesounddistant", asset->firesounddistant);
				json.WriteFieldValueXHash("firesound", asset->firesound);
				json.WriteFieldValueXHash("firesoundplayer", asset->firesoundplayer);
				json.WriteFieldValueXHash("sound100", asset->sound100);
				json.WriteFieldValueXHash("sound110", asset->sound110);
				json.WriteFieldValueXHash("sound120", asset->sound120);
				json.WriteFieldValueXHash("sound130", asset->sound130);
				json.WriteFieldValueXHash("sound140", asset->sound140);
				json.WriteFieldValueXHash("sound150", asset->sound150);
				json.WriteFieldValueXHash("sound160", asset->sound160);
				json.WriteFieldValueXHash("sound170", asset->sound170);
				json.WriteFieldValueXHash("sound180", asset->sound180);
				json.WriteFieldValueXHash("sound190", asset->sound190);
				json.WriteFieldValueXHash("sound1a0", asset->sound1a0);
				json.WriteFieldValueXHash("sound1b0", asset->sound1b0);
				json.WriteFieldValueXHash("sound1c0", asset->sound1c0);
				json.WriteFieldValueXHash("sound1d0", asset->sound1d0);
				json.WriteFieldValueXHash("sound1e0", asset->sound1e0);
				json.WriteFieldValueXHash("sound1f0", asset->sound1f0);
				json.WriteFieldValueXHash("sound200", asset->sound200);
				json.WriteFieldValueXHash("sound210", asset->sound210);
				json.WriteFieldValueXHash("sound220", asset->sound220);
				json.WriteFieldValueXHash("sound230", asset->sound230);
				json.WriteFieldValueXHash("sound240", asset->sound240);
				json.WriteFieldValueXHash("sound250", asset->sound250);
				json.WriteFieldValueXHash("sound260", asset->sound260);
				json.WriteFieldValueXHash("sound270", asset->sound270);
				json.WriteFieldValueXHash("sound280", asset->sound280);
				json.WriteFieldValueXHash("sound290", asset->sound290);
				json.WriteFieldValueXHash("sound2a0", asset->sound2a0);
				json.WriteFieldValueXHash("sound2b0", asset->sound2b0);
				json.WriteFieldValueXHash("sound2c0", asset->sound2c0);
				json.WriteFieldValueXHash("sound2d0", asset->sound2d0);
				json.WriteFieldValueXHash("sound2e0", asset->sound2e0);
				json.WriteFieldValueXHash("sound2f0", asset->sound2f0);
				json.WriteFieldValueXHash("sound300", asset->sound300);
				json.WriteFieldValueXHash("sound310", asset->sound310);
				json.WriteFieldValueXHash("sound320", asset->sound320);
				json.WriteFieldValueXHash("sound330", asset->sound330);
				json.WriteFieldValueXHash("sound340", asset->sound340);
				json.WriteFieldValueXHash("sound350", asset->sound350);
				json.WriteFieldValueXHash("sound360", asset->sound360);
				json.WriteFieldValueXHash("sound370", asset->sound370);
				json.WriteFieldValueXHash("sound380", asset->sound380);
				json.WriteFieldValueXHash("gadgetreadysound", asset->gadgetreadysound);
				json.WriteFieldValueXHash(0x1f7ccc3b, asset->var_1f7ccc3b);
				json.WriteFieldValueXHash("sound3b0", asset->sound3b0);
				json.WriteFieldValueXHash("sound3c0", asset->sound3c0);
				json.WriteFieldValueXHash("sound3d0", asset->sound3d0);
				json.WriteFieldValueXHash("sound3e0", asset->sound3e0);
				json.WriteFieldValueXHash("sound3f0", asset->sound3f0);
				json.WriteFieldValueXHash("sound400", asset->sound400);
				json.WriteFieldValueXHash("sound410", asset->sound410);
				json.WriteFieldValueXHash("gadgetreadysoundplayer", asset->gadgetreadysoundplayer);
				json.WriteFieldValueXHash(0xfb22040b, asset->var_fb22040b);
				json.WriteFieldValueXHash("sound440", asset->sound440);
				json.WriteFieldValueXHash("sound450", asset->sound450);
				json.WriteFieldValueXHash("sound460", asset->sound460);
				json.WriteFieldValueXHash("sound470", asset->sound470);
				json.WriteFieldValueXHash("sound480", asset->sound480);
				json.WriteFieldValueXHash("sound490", asset->sound490);
				json.WriteFieldValueXHash("sound4a0", asset->sound4a0);
				json.WriteFieldValueXHash("sound4b0", asset->sound4b0);
				json.WriteFieldValueXHash("sound4c0", asset->sound4c0);
				json.WriteFieldValueXHash("sound4d0", asset->sound4d0);
				json.WriteFieldValueXHash("sound4e0", asset->sound4e0);
				json.WriteFieldValueXHash("sound4f0", asset->sound4f0);
				json.WriteFieldValueXHash("sound500", asset->sound500);
				json.WriteFieldValueXHash("sound510", asset->sound510);
				json.WriteFieldValueXHash("sound520", asset->sound520);
				json.WriteFieldValueXHash("sound530", asset->sound530);
				json.WriteFieldValueXHash("sound540", asset->sound540);
				json.WriteFieldValueXHash("sound550", asset->sound550);
				json.WriteFieldValueXHash("sound560", asset->sound560);
				json.WriteFieldValueXHash("sound570", asset->sound570);
				json.WriteFieldValueXHash("sound580", asset->sound580);
				json.WriteFieldValueXHash("sound590", asset->sound590);
				json.WriteFieldValueXHash("sound5a0", asset->sound5a0);
				json.WriteFieldValueXHash("sound5b0", asset->sound5b0);
				json.WriteFieldValueXHash("sound5c0", asset->sound5c0);
				json.WriteFieldValueXHash("sound5d0", asset->sound5d0);
				json.WriteFieldValueXHash("sound5e0", asset->sound5e0);
				json.WriteFieldValueXHash("sound5f0", asset->sound5f0);
				json.WriteFieldValueXHash("sound600", asset->sound600);
				json.WriteFieldValueXHash("sound610", asset->sound610);
				json.WriteFieldValueXHash("sound620", asset->sound620);
				json.WriteFieldValueXHash("sound630", asset->sound630);
				json.WriteFieldValueXHash("sound640", asset->sound640);
				json.WriteFieldValueXHash("sound650", asset->sound650);
				json.WriteFieldValueXHash("sound660", asset->sound660);
				json.WriteFieldValueXHash("sound670", asset->sound670);
				json.WriteFieldValueXHash("sound680", asset->sound680);
				json.WriteFieldValueXHash("sound690", asset->sound690);
				json.WriteFieldValueXHash("sound6a0", asset->sound6a0);
				json.WriteFieldValueXHash("sound6b0", asset->sound6b0);
				json.WriteFieldValueXHash("sound6c0", asset->sound6c0);
				json.WriteFieldValueXHash("lockonseekersearchsound", asset->lockonseekersearchsound);
				json.WriteFieldValueXHash("lockonseekerlockedsound", asset->lockonseekerlockedsound);
				json.WriteFieldValueXHash("lockontargetlockedsound", asset->lockontargetlockedsound);
				json.WriteFieldValueXHash("lockontargetfiredonsound", asset->lockontargetfiredonsound);
				json.WriteFieldValueXHash("sound710", asset->sound710);
				json.WriteFieldValueXHash("sound720", asset->sound720);
				json.WriteFieldValueXHash("sound730", asset->sound730);
				json.WriteFieldValueXHash("sound740", asset->sound740);
				json.WriteFieldValueXHash(0x8a03df2b, asset->var_8a03df2b);
				json.WriteFieldValueXHash(0x2f3ca476, asset->var_2f3ca476);
				json.WriteFieldValueXHash(0x5c29f743, asset->var_5c29f743);
				json.WriteFieldValueXHash("projexplosionsound", asset->projexplosionsound);
				json.WriteFieldValueXHash("projexplosionsoundplayer", asset->projexplosionsoundplayer);
				json.WriteFieldValueXHash("projsmokestartsound", asset->projsmokestartsound);
				json.WriteFieldValueXHash("projsmokeloopsound", asset->projsmokeloopsound);
				json.WriteFieldValueXHash("projsmokeendsound", asset->projsmokeendsound);
				json.WriteFieldValueXHash("sound7d0", asset->sound7d0);
				json.WriteFieldValueXHash("sound7e0", asset->sound7e0);
				json.WriteFieldValueXHash("sound7f0", asset->sound7f0);
				json.WriteFieldValueXHash("sound800", asset->sound800);
				json.WriteFieldValueXHash("sound810", asset->sound810);
				json.WriteFieldValueXHash("sound820", asset->sound820);
				json.WriteFieldValueXHash("sound830", asset->sound830);
				json.WriteFieldValueXHash("sound840", asset->sound840);
				json.WriteFieldValueXHash("sound850", asset->sound850);
				json.WriteFieldValueXHash("sound860", asset->sound860);
				json.WriteFieldValueXHash("hitsound", asset->hitsound);
				json.WriteFieldValueXHash("sound880", asset->sound880);
				json.WriteFieldValueXHash("sound890", asset->sound890);

				json.WriteFieldValueXAsset("tunables1", ASSET_TYPE_WEAPON_TUNABLES, asset->tunables1);
				json.WriteFieldValueXAsset("tunables2", ASSET_TYPE_WEAPON_TUNABLES, asset->tunables2);
				json.WriteFieldValueXAsset("weaponCamo", ASSET_TYPE_WEAPON_CAMO, asset->weaponCamo);
				json.WriteFieldValueXAsset("cacWeaponXCam", ASSET_TYPE_XCAM, asset->cacWeaponXCam);
				json.WriteFieldValueXAsset("cacAttachmentsXCam", ASSET_TYPE_XCAM, asset->cacAttachmentsXCam);
				json.WriteFieldValueXAsset("weaponIconXCam", ASSET_TYPE_XCAM, asset->weaponIconXCam);
				json.WriteFieldValueXAssetArray("attachments", ASSET_TYPE_ATTACHMENT, ARRAYSIZE(*asset->attachments), asset->attachments);
				json.WriteFieldValueXAssetArray("attachmentUniques", ASSET_TYPE_ATTACHMENT_UNIQUE, ARRAYSIZE(*asset->attachmentUniques), asset->attachmentUniques);
				json.WriteFieldValueXAsset("xanim_a68", ASSET_TYPE_XANIM, asset->unka68);
				json.WriteFieldValueXAsset("sharedWeaponSounds", ASSET_TYPE_SHAREDWEAPONSOUNDS, asset->sharedWeaponSounds);
				json.WriteFieldValueXAsset("ballisticDesc", ASSET_TYPE_BALLISTICDESC, asset->ballisticDesc);
				json.WriteFieldValueXAsset("weaponHeadObjective", ASSET_TYPE_OBJECTIVE, asset->weaponHeadObjective);
				json.WriteFieldValueXAsset("crateObjective", ASSET_TYPE_OBJECTIVE, asset->crateObjective);
				json.WriteFieldValueXAsset("flameTableFirstPerson", ASSET_TYPE_FLAMETABLE, asset->flameTableFirstPerson);
				json.WriteFieldValueXAsset("flameTableThirdPerson", ASSET_TYPE_FLAMETABLE, asset->flameTableThirdPerson);

				json.WriteFieldValueXAsset("scriptbundle_1008", ASSET_TYPE_SCRIPTBUNDLE, asset->unk1008);
				json.WriteFieldValueXAsset("turretAnimSettings", ASSET_TYPE_SCRIPTBUNDLE, asset->turretAnimSettings);
				json.WriteFieldValueXAsset("killcamSettings", ASSET_TYPE_SCRIPTBUNDLE, asset->killcamSettings);
				json.WriteFieldValueXAsset("customsettings", ASSET_TYPE_SCRIPTBUNDLE, asset->customsettings);
				json.WriteFieldValueXAsset("shrapnelsettings", ASSET_TYPE_SCRIPTBUNDLE, asset->shrapnelsettings);
				json.WriteFieldValueXAsset(0x2e4a8800, ASSET_TYPE_SCRIPTBUNDLE, asset->var_2e4a8800);
				json.WriteFieldValueXAsset(0x8456d4d, ASSET_TYPE_SCRIPTBUNDLE, asset->var_8456d4d);

				json.WriteFieldValueXAsset("handModel", ASSET_TYPE_XMODEL, asset->handModel);
				json.WriteFieldValueXAsset("model_d28", ASSET_TYPE_XMODEL, asset->unkd28);
				json.WriteFieldValueXAsset(0x22082a57, ASSET_TYPE_XMODEL, asset->var_22082a57);
				json.WriteFieldValueXAsset("projectilemodel", ASSET_TYPE_XMODEL, asset->projectilemodel);
				json.WriteFieldValueXAsset("projectileModelEnemy", ASSET_TYPE_XMODEL, asset->projectileModelEnemy);
				json.WriteFieldValueXAsset(0x4bcd08b0, ASSET_TYPE_XMODEL, asset->var_4bcd08b0);
				json.WriteFieldValueXAssetArray("viewmodel", ASSET_TYPE_XMODEL, asset->var_5b73038c, asset->viewmodel);
				json.WriteFieldValueXAssetArray("frontendmodel", ASSET_TYPE_XMODEL, asset->var_5b73038c, asset->frontendmodel);
				json.WriteFieldValueXAssetArray("worldModel", ASSET_TYPE_XMODEL, asset->var_5b73038c, asset->worldModel);
				json.WriteFieldValueXAssetArray("models_cd0", ASSET_TYPE_XMODEL, asset->var_5b73038c, asset->unkcd0);
				json.WriteFieldValueXAssetArray("stowedmodel", ASSET_TYPE_XMODEL, asset->var_5b73038c, asset->stowedmodel);
				json.WriteFieldValueXAssetArray("clipmodel", ASSET_TYPE_XMODEL, asset->var_5b73038c, asset->clipmodel);

				json.WriteFieldValueXAsset("gadgetIconAvailable", ASSET_TYPE_IMAGE, asset->gadgetIconAvailable);
				json.WriteFieldValueXAsset("gadgetIconUnavailable", ASSET_TYPE_IMAGE, asset->gadgetIconUnavailable);
				json.WriteFieldValueXAsset("image_c70", ASSET_TYPE_IMAGE, asset->unkc70);
				json.WriteFieldValueXAsset("image_c78", ASSET_TYPE_IMAGE, asset->unkc78);
				json.WriteFieldValueXAsset("reticleCenter", ASSET_TYPE_IMAGE, asset->reticleCenter);
				json.WriteFieldValueXAsset("reticleSide", ASSET_TYPE_IMAGE, asset->reticleSide);
				json.WriteFieldValueXAssetArray("images_cf8", ASSET_TYPE_IMAGE, asset->var_5b73038c, asset->unkcf8);
				json.WriteFieldValueXAssetArray("images_d00", ASSET_TYPE_IMAGE, asset->var_5b73038c, asset->unkd00);
				json.WriteFieldValueXAssetArray("images_d08", ASSET_TYPE_IMAGE, asset->var_5b73038c, asset->unkd08);
				json.WriteFieldValueXAsset("inventoryIcon", ASSET_TYPE_IMAGE, asset->inventoryIcon);
				json.WriteFieldValueXAsset("inventoryIconZm", ASSET_TYPE_IMAGE, asset->inventoryIconZm);
				json.WriteFieldValueXAsset("hudIcon", ASSET_TYPE_IMAGE, asset->hudIcon);
				json.WriteFieldValueXAsset("reticleSeekingLockOn", ASSET_TYPE_IMAGE, asset->reticleSeekingLockOn);
				json.WriteFieldValueXAsset("reticleLockOn", ASSET_TYPE_IMAGE, asset->reticleLockOn);
				json.WriteFieldValueXAsset("image_d88", ASSET_TYPE_IMAGE, asset->unkd88);
				json.WriteFieldValueXAsset("image_d90", ASSET_TYPE_IMAGE, asset->unkd90);
				json.WriteFieldValueXAsset("image_d98", ASSET_TYPE_IMAGE, asset->unkd98);
				json.WriteFieldValueXAsset("image_da0", ASSET_TYPE_IMAGE, asset->unkda0);
				json.WriteFieldValueXAsset("image_da8", ASSET_TYPE_IMAGE, asset->unkda8);
				json.WriteFieldValueXAsset("image_db0", ASSET_TYPE_IMAGE, asset->unkdb0);
				json.WriteFieldValueXAsset("image_db8", ASSET_TYPE_IMAGE, asset->unkdb8);
				json.WriteFieldValueXAsset("image_e90", ASSET_TYPE_IMAGE, asset->unke90);
				json.WriteFieldValueXAsset("image_e98", ASSET_TYPE_IMAGE, asset->unke98);
				json.WriteFieldValueXAsset("image_ea0", ASSET_TYPE_IMAGE, asset->unkea0);
				json.WriteFieldValueXAsset("image_eb0", ASSET_TYPE_IMAGE, asset->unkeb0);
				json.WriteFieldValueXAsset("image_1038", ASSET_TYPE_IMAGE, asset->unk1038);
				json.WriteFieldValueXAsset("image_1040", ASSET_TYPE_IMAGE, asset->unk1040);
				json.WriteFieldValueXAsset("image_1048", ASSET_TYPE_IMAGE, asset->unk1048);

				json.WriteFieldValueXAsset("fireRumble", ASSET_TYPE_RUMBLE, asset->fireRumble);
				json.WriteFieldValueXAsset("rumble_dc8", ASSET_TYPE_RUMBLE, asset->unkdc8);
				json.WriteFieldValueXAsset("rumble_dd0", ASSET_TYPE_RUMBLE, asset->unkdd0);
				json.WriteFieldValueXAsset("meleeImpactRumble", ASSET_TYPE_RUMBLE, asset->meleeImpactRumble);
				json.WriteFieldValueXAsset("rumble_de0", ASSET_TYPE_RUMBLE, asset->unkde0);
				json.WriteFieldValueXAsset("rumble_de8", ASSET_TYPE_RUMBLE, asset->unkde8);
				json.WriteFieldValueXAsset("rumble_df0", ASSET_TYPE_RUMBLE, asset->unkdf0);
				json.WriteFieldValueXAsset("rumble_df8", ASSET_TYPE_RUMBLE, asset->unkdf8);
				json.WriteFieldValueXAsset("rumble_e00", ASSET_TYPE_RUMBLE, asset->unke00);
				json.WriteFieldValueXAsset("rumble_e08", ASSET_TYPE_RUMBLE, asset->unke08);
				json.WriteFieldValueXAsset("rumble_e10", ASSET_TYPE_RUMBLE, asset->unke10);
				json.WriteFieldValueXAsset("rumble_e18", ASSET_TYPE_RUMBLE, asset->unke18);
				json.WriteFieldValueXAsset("rumble_e20", ASSET_TYPE_RUMBLE, asset->unke20);
				json.WriteFieldValueXAsset("rumble_e28", ASSET_TYPE_RUMBLE, asset->unke28);

				json.WriteFieldValueXAsset("laser_e30", ASSET_TYPE_LASER, asset->unke30);
				json.WriteFieldValueXAsset("laser_e38", ASSET_TYPE_LASER, asset->unke38);
				json.WriteFieldValueXAsset("laser_e40", ASSET_TYPE_LASER, asset->unke40);

				json.WriteFieldValueXAsset("beam_e58", ASSET_TYPE_BEAM, asset->unke58);
				json.WriteFieldValueXAsset("beam_e60", ASSET_TYPE_BEAM, asset->unke60);
				json.WriteFieldValueXAsset("beam_e68", ASSET_TYPE_BEAM, asset->unke68);
				json.WriteFieldValueXAsset("beam_e70", ASSET_TYPE_BEAM, asset->unke70);
				json.WriteFieldValueXAsset("beam_e78", ASSET_TYPE_BEAM, asset->unke78);
				json.WriteFieldValueXAsset("beam_e80", ASSET_TYPE_BEAM, asset->unke80);
				json.WriteFieldValueXAsset("beam_e88", ASSET_TYPE_BEAM, asset->unke88);


				json.WriteFieldValueXAsset("reticlePivotLocked", ASSET_TYPE_MATERIAL, asset->reticlePivotLocked);
				json.WriteFieldValueXAsset("reticlePivotInvalid", ASSET_TYPE_MATERIAL, asset->reticlePivotInvalid);
				json.WriteFieldValueXAsset("reticlePivotTarget", ASSET_TYPE_MATERIAL, asset->reticlePivotTarget);
				json.WriteFieldValueXAsset("reticlePivotSides", ASSET_TYPE_MATERIAL, asset->reticlePivotSides);
				json.WriteFieldValueXAsset("reticlePivotLine", ASSET_TYPE_MATERIAL, asset->reticlePivotLine);

				json.WriteFieldValueXAsset("fx_bc8", ASSET_TYPE_FX, asset->unkbc8);
				json.WriteFieldValueXAsset("fx_bd0", ASSET_TYPE_FX, asset->unkbd0);
				json.WriteFieldValueXAsset("fx_bd8", ASSET_TYPE_FX, asset->unkbd8);
				json.WriteFieldValueXAsset("fx_be0", ASSET_TYPE_FX, asset->unkbe0);
				json.WriteFieldValueXAsset("fx_be8", ASSET_TYPE_FX, asset->unkbe8);
				json.WriteFieldValueXAsset("fx_c08", ASSET_TYPE_FX, asset->unkc08);
				json.WriteFieldValueXAsset("fx_c80", ASSET_TYPE_FX, asset->unkc80);
				json.WriteFieldValueXAsset("fx_c88", ASSET_TYPE_FX, asset->unkc88);
				json.WriteFieldValueXAsset("fx_c90", ASSET_TYPE_FX, asset->unkc90);
				json.WriteFieldValueXAsset("fx_c98", ASSET_TYPE_FX, asset->unkc98);
				json.WriteFieldValueXAsset("fx_ca0", ASSET_TYPE_FX, asset->unkca0);
				json.WriteFieldValueXAsset("fx_ca8", ASSET_TYPE_FX, asset->unkca8);
				json.WriteFieldValueXAsset("fx_ed8", ASSET_TYPE_FX, asset->unked8);
				json.WriteFieldValueXAsset("fx_ee0", ASSET_TYPE_FX, asset->unkee0);
				json.WriteFieldValueXAsset("fx_ee8", ASSET_TYPE_FX, asset->unkee8);
				json.WriteFieldValueXAsset("fx_ef0", ASSET_TYPE_FX, asset->unkef0);
				json.WriteFieldValueXAsset("fx_f00", ASSET_TYPE_FX, asset->unkf00);
				json.WriteFieldValueXAsset("fx_f08", ASSET_TYPE_FX, asset->unkf08);
				json.WriteFieldValueXAsset("fx_f10", ASSET_TYPE_FX, asset->unkf10);
				json.WriteFieldValueXAsset("fx_f18", ASSET_TYPE_FX, asset->unkf18);
				json.WriteFieldValueXAssetArray("underwaterExplosionSurfaceFX", ASSET_TYPE_FX, ARRAYSIZE(asset->underwaterExplosionSurfaceFX), asset->underwaterExplosionSurfaceFX);
				json.WriteFieldValueXAsset("fx_f38", ASSET_TYPE_FX, asset->unkf38);
				json.WriteFieldValueXAsset("fx_f40", ASSET_TYPE_FX, asset->unkf40);
				json.WriteFieldValueXAsset("fx_f48", ASSET_TYPE_FX, asset->unkf48);
				json.WriteFieldValueXAsset("fx_f50", ASSET_TYPE_FX, asset->unkf50);
				json.WriteFieldValueXAsset("fx_f58", ASSET_TYPE_FX, asset->unkf58);
				json.WriteFieldValueXAsset("fx_f60", ASSET_TYPE_FX, asset->unkf60);
				json.WriteFieldValueXAsset("fx_f68", ASSET_TYPE_FX, asset->unkf68);
				json.WriteFieldValueXAsset("fx_f70", ASSET_TYPE_FX, asset->unkf70);
				json.WriteFieldValueXAsset("fx_f88", ASSET_TYPE_FX, asset->unkf88);
				json.WriteFieldValueXAsset("fx_f90", ASSET_TYPE_FX, asset->unkf90);
				json.WriteFieldValueXAsset("fx_f98", ASSET_TYPE_FX, asset->unkf98);
				json.WriteFieldValueXAsset("fx_fa0", ASSET_TYPE_FX, asset->unkfa0);

				json.WriteFieldValueXAsset("viewPersistentEffectSet", ASSET_TYPE_TAGFX, asset->viewPersistentEffectSet);
				json.WriteFieldValueXAsset("worldPersistentEffectSet", ASSET_TYPE_TAGFX, asset->worldPersistentEffectSet);
				json.WriteFieldValueXAsset("enemyDeathFxSet", ASSET_TYPE_TAGFX, asset->enemyDeathFxSet);
				json.WriteFieldValueXAssetArray("tagFXSetFirstPerson", ASSET_TYPE_TAGFX, ARRAYSIZE(asset->tagFXSetFirstPerson), asset->tagFXSetFirstPerson);
				json.WriteFieldValueXAssetArray("tagFXSetThirdPerson", ASSET_TYPE_TAGFX, ARRAYSIZE(asset->tagFXSetThirdPerson), asset->tagFXSetThirdPerson);
				json.WriteFieldValueXAsset(0x96850284, ASSET_TYPE_TAGFX, asset->var_96850284);
				json.WriteFieldValueXAsset(0x26f68e75, ASSET_TYPE_TAGFX, asset->var_26f68e75);

				json.WriteFieldValueXAsset("normalImpactFX", ASSET_TYPE_IMPACT_FX, asset->normalImpactFX);
				json.WriteFieldValueXAsset("exitImpactFX", ASSET_TYPE_IMPACT_FX, asset->exitImpactFX);
				json.WriteFieldValueXAsset("bounceImpactFX", ASSET_TYPE_IMPACT_FX, asset->bounceImpactFX);
				json.WriteFieldValueXAsset("dudImpactFX", ASSET_TYPE_IMPACT_FX, asset->dudImpactFX);
				json.WriteFieldValueXAsset("fxImpact_fd8", ASSET_TYPE_IMPACT_FX, asset->unkfd8);

				json.WriteFieldValueXAsset("normalImpactSounds", ASSET_TYPE_IMPACT_SOUND, asset->normalImpactSounds);
				json.WriteFieldValueXAsset("exitImpactSounds", ASSET_TYPE_IMPACT_SOUND, asset->exitImpactSounds);
				json.WriteFieldValueXAsset("bounceImpactSounds", ASSET_TYPE_IMPACT_SOUND, asset->bounceImpactSounds);
				json.WriteFieldValueXAsset("dudImpactSounds", ASSET_TYPE_IMPACT_SOUND, asset->dudImpactSounds);
				json.WriteFieldValueXAsset("soundsImpact_1000", ASSET_TYPE_IMPACT_SOUND, asset->unk1000);

			}
			json.EndObject();

			if (!json.WriteToFile(outFile)) {
				LOG_ERROR("Error when dumping {}", outFile.string());
			}
		}
	};

	utils::MapAdder<ImplWorker, games::bo4::pool::XAssetType, Worker> impl{ GetWorkers(), games::bo4::pool::XAssetType::ASSET_TYPE_WEAPON };
}