#pragma once
namespace tool::mw19 {
    enum IW8PoolType : uint32_t {
        IW8_ASSET_PHYSICSLIBRARY = 0x0, // physicslibrary
        IW8_ASSET_PHYSICSSFXEVENTASSET = 0x1, // physicssfxeventasset
        IW8_ASSET_PHYSICSVFXEVENTASSET = 0x2, // physicsvfxeventasset
        IW8_ASSET_PHYSICSASSET = 0x3, // physicsasset
        IW8_ASSET_PHYSICSFXPIPELINE = 0x4, // physicsfxpipeline
        IW8_ASSET_PHYSICSFXSHAPE = 0x5, // physicsfxshape
        IW8_ASSET_PHYSICSDEBUGDATA = 0x6, // physicsdebugdata
        IW8_ASSET_XANIM = 0x7, // xanim
        IW8_ASSET_XMODELSURFS = 0x8, // xmodelsurfs
        IW8_ASSET_XMODEL = 0x9, // xmodel
        IW8_ASSET_MAYHEM = 0xa, // mayhem
        IW8_ASSET_MATERIAL = 0xb, // material
        IW8_ASSET_COMPUTESHADER = 0xc, // computeshader
        IW8_ASSET_LIBSHADER = 0xd, // libshader
        IW8_ASSET_VERTEXSHADER = 0xe, // vertexshader
        IW8_ASSET_HULLSHADER = 0xf, // hullshader
        IW8_ASSET_DOMAINSHADER = 0x10, // domainshader
        IW8_ASSET_PIXELSHADER = 0x11, // pixelshader
        IW8_ASSET_TECHSET = 0x12, // techset
        IW8_ASSET_IMAGE = 0x13, // image
        IW8_ASSET_SOUNDGLOBALS = 0x14, // soundglobals
        IW8_ASSET_SOUNDBANK = 0x15, // soundbank
        IW8_ASSET_SOUNDBANKTRANSIENT = 0x16, // soundbanktransient
        IW8_ASSET_COL_MAP = 0x17, // col_map
        IW8_ASSET_COM_MAP = 0x18, // com_map
        IW8_ASSET_GLASS_MAP = 0x19, // glass_map
        IW8_ASSET_AIPATHS = 0x1a, // aipaths
        IW8_ASSET_NAVMESH = 0x1b, // navmesh
        IW8_ASSET_TACGRAPH = 0x1c, // tacgraph
        IW8_ASSET_MAP_ENTS = 0x1d, // map_ents
        IW8_ASSET_FX_MAP = 0x1e, // fx_map
        IW8_ASSET_GFX_MAP = 0x1f, // gfx_map
        IW8_ASSET_GFX_MAP_TRZONE = 0x20, // gfx_map_trzone
        IW8_ASSET_IESPROFILE = 0x21, // iesprofile
        IW8_ASSET_LIGHTDEF = 0x22, // lightdef
        IW8_ASSET_GRADINGCLUT = 0x23, // gradingclut
        IW8_ASSET_UI_MAP = 0x24, // ui_map
        IW8_ASSET_FOGSPLINE = 0x25, // fogspline
        IW8_ASSET_ANIMCLASS = 0x26, // animclass
        IW8_ASSET_PLAYERANIM = 0x27, // playeranim
        IW8_ASSET_GESTURE = 0x28, // gesture
        IW8_ASSET_LOCALIZE = 0x29, // localize
        IW8_ASSET_ATTACHMENT = 0x2a, // attachment
        IW8_ASSET_WEAPON = 0x2b, // weapon
        IW8_ASSET_VFX = 0x2c, // vfx
        IW8_ASSET_IMPACTFX = 0x2d, // impactfx
        IW8_ASSET_SURFACEFX = 0x2e, // surfacefx
        IW8_ASSET_AITYPE = 0x2f, // aitype
        IW8_ASSET_MPTYPE = 0x30, // mptype
        IW8_ASSET_CHARACTER = 0x31, // character
        IW8_ASSET_XMODELALIAS = 0x32, // xmodelalias
        IW8_ASSET_RAWFILE = 0x33, // rawfile
        IW8_ASSET_SCRIPTFILE = 0x34, // scriptfile
        IW8_ASSET_SCRIPTDEBUGDATA = 0x35, // scriptdebugdata
        IW8_ASSET_STRINGTABLE = 0x36, // stringtable
        IW8_ASSET_LEADERBOARDDEF = 0x37, // leaderboarddef
        IW8_ASSET_VIRTUALLEADERBOARDDEF = 0x38, // virtualleaderboarddef
        IW8_ASSET_DDL = 0x39, // ddl
        IW8_ASSET_TRACER = 0x3a, // tracer
        IW8_ASSET_VEHICLE = 0x3b, // vehicle
        IW8_ASSET_ADDON_MAP_ENTS = 0x3c, // addon_map_ents
        IW8_ASSET_NETCONSTSTRINGS = 0x3d, // netconststrings
        IW8_ASSET_LUAFILE = 0x3e, // luafile
        IW8_ASSET_SCRIPTABLE = 0x3f, // scriptable
        IW8_ASSET_EQUIPSNDTABLE = 0x40, // equipsndtable
        IW8_ASSET_VECTORFIELD = 0x41, // vectorfield
        IW8_ASSET_PARTICLESIMANIMATION = 0x42, // particlesimanimation
        IW8_ASSET_STREAMINGINFO = 0x43, // streaminginfo
        IW8_ASSET_LASER = 0x44, // laser
        IW8_ASSET_TTF = 0x45, // ttf
        IW8_ASSET_SUIT = 0x46, // suit
        IW8_ASSET_SUITANIMPACKAGE = 0x47, // suitanimpackage
        IW8_ASSET_CAMERA = 0x48, // camera
        IW8_ASSET_HUDOUTLINE = 0x49, // hudoutline
        IW8_ASSET_SPACESHIPTARGET = 0x4a, // spaceshiptarget
        IW8_ASSET_RUMBLE = 0x4b, // rumble
        IW8_ASSET_RUMBLEGRAPH = 0x4c, // rumblegraph
        IW8_ASSET_ANIMPKG = 0x4d, // animpkg
        IW8_ASSET_SFXPKG = 0x4e, // sfxpkg
        IW8_ASSET_VFXPKG = 0x4f, // vfxpkg
        IW8_ASSET_FOOTSTEPVFX = 0x50, // footstepvfx
        IW8_ASSET_BEHAVIORTREE = 0x51, // behaviortree
        IW8_ASSET_AIANIMSET = 0x52, // aianimset
        IW8_ASSET_AIASM = 0x53, // aiasm
        IW8_ASSET_PROCEDURALBONES = 0x54, // proceduralbones
        IW8_ASSET_DYNAMICBONES = 0x55, // dynamicbones
        IW8_ASSET_RETICLE = 0x56, // reticle
        IW8_ASSET_XANIMCURVE = 0x57, // xanimcurve
        IW8_ASSET_COVERSELECTOR = 0x58, // coverselector
        IW8_ASSET_ENEMYSELECTOR = 0x59, // enemyselector
        IW8_ASSET_CLIENTCHARACTER = 0x5a, // clientcharacter
        IW8_ASSET_CLOTHASSET = 0x5b, // clothasset
        IW8_ASSET_CINEMATICMOTION = 0x5c, // cinematicmotion
        IW8_ASSET_ACCESSORY = 0x5d, // accessory
        IW8_ASSET_LOCDMGTABLE = 0x5e, // locdmgtable
        IW8_ASSET_BULLETPENETRATION = 0x5f, // bulletpenetration
        IW8_ASSET_SCRIPTBUNDLE = 0x60, // scriptbundle
        IW8_ASSET_BLENDSPACE2D = 0x61, // blendspace2d
        IW8_ASSET_XCAM = 0x62, // xcam
        IW8_ASSET_CAMO = 0x63, // camo
        IW8_ASSET_XCOMPOSITEMODEL = 0x64, // xcompositemodel
        IW8_ASSET_XMODELDETAILCOLLISION = 0x65, // xmodeldetailcollision
        IW8_ASSET_STREAMKEY = 0x66, // streamkey
        IW8_ASSET_STREAMTREEOVERRIDE = 0x67, // streamtreeoverride
        IW8_ASSET_KEYVALUEPAIRS = 0x68, // keyvaluepairs
        IW8_ASSET_STTERRAIN = 0x69, // stterrain
        IW8_ASSET_NATIVESCRIPTPATCH = 0x6a, // nativescriptpatch
        IW8_ASSET_COLLISIONTILE = 0x6b, // collisiontile
        IW8_ASSET_EXECUTION = 0x6c, // execution
        IW8_ASSET_CARRYOBJECT = 0x6d, // carryobject
        IW8_ASSET_SOUNDBANKLIST = 0x6e, // soundbanklist
        IW8_ASSET_DECALVOLUMEMATERIAL = 0x6f, // decalvolumematerial
        IW8_ASSET_DECALVOLUMEMASK = 0x70, // decalvolumemask
        IW8_ASSET_DYNENTITYLIST = 0x71, // dynentitylist
        IW8_ASSET_FX_MAP_TRZONE = 0x72, // fx_map_trzone
        IW8_ASSET_DLOGSCHEMA = 0x73, // dlogschema
        IW8_ASSET_EDGELIST = 0x74, // edgelist
        IW8_ASSET_TRIGGEREFFECT = 0x75, // triggereffect
        IW8_ASSET_WEAPONTRIGGER = 0x76, // weapontrigger
        IW8_ASSET_DWIDATA = 0x77, // dwidata
    };

    enum IW8HashAssetType : uint32_t {
        IW8H_ASSET_PHYSICSLIBRARY = hash::HashX32("physicslibrary"),
        IW8H_ASSET_PHYSICSSFXEVENTASSET = hash::HashX32("physicssfxeventasset"),
        IW8H_ASSET_PHYSICSVFXEVENTASSET = hash::HashX32("physicsvfxeventasset"),
        IW8H_ASSET_PHYSICSASSET = hash::HashX32("physicsasset"),
        IW8H_ASSET_PHYSICSFXPIPELINE = hash::HashX32("physicsfxpipeline"),
        IW8H_ASSET_PHYSICSFXSHAPE = hash::HashX32("physicsfxshape"),
        IW8H_ASSET_PHYSICSDEBUGDATA = hash::HashX32("physicsdebugdata"),
        IW8H_ASSET_XANIM = hash::HashX32("xanim"),
        IW8H_ASSET_XMODELSURFS = hash::HashX32("xmodelsurfs"),
        IW8H_ASSET_XMODEL = hash::HashX32("xmodel"),
        IW8H_ASSET_MAYHEM = hash::HashX32("mayhem"),
        IW8H_ASSET_MATERIAL = hash::HashX32("material"),
        IW8H_ASSET_COMPUTESHADER = hash::HashX32("computeshader"),
        IW8H_ASSET_LIBSHADER = hash::HashX32("libshader"),
        IW8H_ASSET_VERTEXSHADER = hash::HashX32("vertexshader"),
        IW8H_ASSET_HULLSHADER = hash::HashX32("hullshader"),
        IW8H_ASSET_DOMAINSHADER = hash::HashX32("domainshader"),
        IW8H_ASSET_PIXELSHADER = hash::HashX32("pixelshader"),
        IW8H_ASSET_TECHSET = hash::HashX32("techset"),
        IW8H_ASSET_IMAGE = hash::HashX32("image"),
        IW8H_ASSET_SOUNDGLOBALS = hash::HashX32("soundglobals"),
        IW8H_ASSET_SOUNDBANK = hash::HashX32("soundbank"),
        IW8H_ASSET_SOUNDBANKTRANSIENT = hash::HashX32("soundbanktransient"),
        IW8H_ASSET_COL_MAP = hash::HashX32("col_map"),
        IW8H_ASSET_COM_MAP = hash::HashX32("com_map"),
        IW8H_ASSET_GLASS_MAP = hash::HashX32("glass_map"),
        IW8H_ASSET_AIPATHS = hash::HashX32("aipaths"),
        IW8H_ASSET_NAVMESH = hash::HashX32("navmesh"),
        IW8H_ASSET_TACGRAPH = hash::HashX32("tacgraph"),
        IW8H_ASSET_MAP_ENTS = hash::HashX32("map_ents"),
        IW8H_ASSET_FX_MAP = hash::HashX32("fx_map"),
        IW8H_ASSET_GFX_MAP = hash::HashX32("gfx_map"),
        IW8H_ASSET_GFX_MAP_TRZONE = hash::HashX32("gfx_map_trzone"),
        IW8H_ASSET_IESPROFILE = hash::HashX32("iesprofile"),
        IW8H_ASSET_LIGHTDEF = hash::HashX32("lightdef"),
        IW8H_ASSET_GRADINGCLUT = hash::HashX32("gradingclut"),
        IW8H_ASSET_UI_MAP = hash::HashX32("ui_map"),
        IW8H_ASSET_FOGSPLINE = hash::HashX32("fogspline"),
        IW8H_ASSET_ANIMCLASS = hash::HashX32("animclass"),
        IW8H_ASSET_PLAYERANIM = hash::HashX32("playeranim"),
        IW8H_ASSET_GESTURE = hash::HashX32("gesture"),
        IW8H_ASSET_LOCALIZE = hash::HashX32("localize"),
        IW8H_ASSET_ATTACHMENT = hash::HashX32("attachment"),
        IW8H_ASSET_WEAPON = hash::HashX32("weapon"),
        IW8H_ASSET_VFX = hash::HashX32("vfx"),
        IW8H_ASSET_IMPACTFX = hash::HashX32("impactfx"),
        IW8H_ASSET_SURFACEFX = hash::HashX32("surfacefx"),
        IW8H_ASSET_AITYPE = hash::HashX32("aitype"),
        IW8H_ASSET_MPTYPE = hash::HashX32("mptype"),
        IW8H_ASSET_CHARACTER = hash::HashX32("character"),
        IW8H_ASSET_XMODELALIAS = hash::HashX32("xmodelalias"),
        IW8H_ASSET_RAWFILE = hash::HashX32("rawfile"),
        IW8H_ASSET_SCRIPTFILE = hash::HashX32("scriptfile"),
        IW8H_ASSET_SCRIPTDEBUGDATA = hash::HashX32("scriptdebugdata"),
        IW8H_ASSET_STRINGTABLE = hash::HashX32("stringtable"),
        IW8H_ASSET_LEADERBOARDDEF = hash::HashX32("leaderboarddef"),
        IW8H_ASSET_VIRTUALLEADERBOARDDEF = hash::HashX32("virtualleaderboarddef"),
        IW8H_ASSET_DDL = hash::HashX32("ddl"),
        IW8H_ASSET_TRACER = hash::HashX32("tracer"),
        IW8H_ASSET_VEHICLE = hash::HashX32("vehicle"),
        IW8H_ASSET_ADDON_MAP_ENTS = hash::HashX32("addon_map_ents"),
        IW8H_ASSET_NETCONSTSTRINGS = hash::HashX32("netconststrings"),
        IW8H_ASSET_LUAFILE = hash::HashX32("luafile"),
        IW8H_ASSET_SCRIPTABLE = hash::HashX32("scriptable"),
        IW8H_ASSET_EQUIPSNDTABLE = hash::HashX32("equipsndtable"),
        IW8H_ASSET_VECTORFIELD = hash::HashX32("vectorfield"),
        IW8H_ASSET_PARTICLESIMANIMATION = hash::HashX32("particlesimanimation"),
        IW8H_ASSET_STREAMINGINFO = hash::HashX32("streaminginfo"),
        IW8H_ASSET_LASER = hash::HashX32("laser"),
        IW8H_ASSET_TTF = hash::HashX32("ttf"),
        IW8H_ASSET_SUIT = hash::HashX32("suit"),
        IW8H_ASSET_SUITANIMPACKAGE = hash::HashX32("suitanimpackage"),
        IW8H_ASSET_CAMERA = hash::HashX32("camera"),
        IW8H_ASSET_HUDOUTLINE = hash::HashX32("hudoutline"),
        IW8H_ASSET_SPACESHIPTARGET = hash::HashX32("spaceshiptarget"),
        IW8H_ASSET_RUMBLE = hash::HashX32("rumble"),
        IW8H_ASSET_RUMBLEGRAPH = hash::HashX32("rumblegraph"),
        IW8H_ASSET_ANIMPKG = hash::HashX32("animpkg"),
        IW8H_ASSET_SFXPKG = hash::HashX32("sfxpkg"),
        IW8H_ASSET_VFXPKG = hash::HashX32("vfxpkg"),
        IW8H_ASSET_FOOTSTEPVFX = hash::HashX32("footstepvfx"),
        IW8H_ASSET_BEHAVIORTREE = hash::HashX32("behaviortree"),
        IW8H_ASSET_AIANIMSET = hash::HashX32("aianimset"),
        IW8H_ASSET_AIASM = hash::HashX32("aiasm"),
        IW8H_ASSET_PROCEDURALBONES = hash::HashX32("proceduralbones"),
        IW8H_ASSET_DYNAMICBONES = hash::HashX32("dynamicbones"),
        IW8H_ASSET_RETICLE = hash::HashX32("reticle"),
        IW8H_ASSET_XANIMCURVE = hash::HashX32("xanimcurve"),
        IW8H_ASSET_COVERSELECTOR = hash::HashX32("coverselector"),
        IW8H_ASSET_ENEMYSELECTOR = hash::HashX32("enemyselector"),
        IW8H_ASSET_CLIENTCHARACTER = hash::HashX32("clientcharacter"),
        IW8H_ASSET_CLOTHASSET = hash::HashX32("clothasset"),
        IW8H_ASSET_CINEMATICMOTION = hash::HashX32("cinematicmotion"),
        IW8H_ASSET_ACCESSORY = hash::HashX32("accessory"),
        IW8H_ASSET_LOCDMGTABLE = hash::HashX32("locdmgtable"),
        IW8H_ASSET_BULLETPENETRATION = hash::HashX32("bulletpenetration"),
        IW8H_ASSET_SCRIPTBUNDLE = hash::HashX32("scriptbundle"),
        IW8H_ASSET_BLENDSPACE2D = hash::HashX32("blendspace2d"),
        IW8H_ASSET_XCAM = hash::HashX32("xcam"),
        IW8H_ASSET_CAMO = hash::HashX32("camo"),
        IW8H_ASSET_XCOMPOSITEMODEL = hash::HashX32("xcompositemodel"),
        IW8H_ASSET_XMODELDETAILCOLLISION = hash::HashX32("xmodeldetailcollision"),
        IW8H_ASSET_STREAMKEY = hash::HashX32("streamkey"),
        IW8H_ASSET_STREAMTREEOVERRIDE = hash::HashX32("streamtreeoverride"),
        IW8H_ASSET_KEYVALUEPAIRS = hash::HashX32("keyvaluepairs"),
        IW8H_ASSET_STTERRAIN = hash::HashX32("stterrain"),
        IW8H_ASSET_NATIVESCRIPTPATCH = hash::HashX32("nativescriptpatch"),
        IW8H_ASSET_COLLISIONTILE = hash::HashX32("collisiontile"),
        IW8H_ASSET_EXECUTION = hash::HashX32("execution"),
        IW8H_ASSET_CARRYOBJECT = hash::HashX32("carryobject"),
        IW8H_ASSET_SOUNDBANKLIST = hash::HashX32("soundbanklist"),
        IW8H_ASSET_DECALVOLUMEMATERIAL = hash::HashX32("decalvolumematerial"),
        IW8H_ASSET_DECALVOLUMEMASK = hash::HashX32("decalvolumemask"),
        IW8H_ASSET_DYNENTITYLIST = hash::HashX32("dynentitylist"),
        IW8H_ASSET_FX_MAP_TRZONE = hash::HashX32("fx_map_trzone"),
        IW8H_ASSET_DLOGSCHEMA = hash::HashX32("dlogschema"),
        IW8H_ASSET_EDGELIST = hash::HashX32("edgelist"),
        IW8H_ASSET_TRIGGEREFFECT = hash::HashX32("triggereffect"),
        IW8H_ASSET_WEAPONTRIGGER = hash::HashX32("weapontrigger"),
        IW8H_ASSET_DWIDATA = hash::HashX32("dwidata"),
    };


    enum IW19PoolType : int {
        IW19_ASSETTYPE_PHYSICSLIBRARY = 0, // 0x0
        IW19_ASSETTYPE_PHYSICSSFXEVENTASSET = 1, // 0x1
        IW19_ASSETTYPE_PHYSICSVFXEVENTASSET = 2, // 0x2
        IW19_ASSETTYPE_PHYSICSASSET = 3, // 0x3
        IW19_ASSETTYPE_PHYSICSFXPIPELINE = 4, // 0x4
        IW19_ASSETTYPE_PHYSICSFXSHAPE = 5, // 0x5
        IW19_ASSETTYPE_PHYSICSDEBUGDATA = 6, // 0x6
        IW19_ASSETTYPE_XANIM = 7, // 0x7
        IW19_ASSETTYPE_XMODELSURFS = 8, // 0x8
        IW19_ASSETTYPE_XMODEL = 9, // 0x9
        IW19_ASSETTYPE_MAYHEM = 10, // 0xa
        IW19_ASSETTYPE_MATERIAL = 11, // 0xb
        IW19_ASSETTYPE_COMPUTESHADER = 12, // 0xc
        IW19_ASSETTYPE_LIBSHADER = 13, // 0xd
        IW19_ASSETTYPE_VERTEXSHADER = 14, // 0xe
        IW19_ASSETTYPE_HULLSHADER = 15, // 0xf
        IW19_ASSETTYPE_DOMAINSHADER = 16, // 0x10
        IW19_ASSETTYPE_PIXELSHADER = 17, // 0x11
        IW19_ASSETTYPE_TECHSET = 18, // 0x12
        IW19_ASSETTYPE_IMAGE = 19, // 0x13
        IW19_ASSETTYPE_SOUNDGLOBALS = 20, // 0x14
        IW19_ASSETTYPE_SOUNDBANK = 21, // 0x15
        IW19_ASSETTYPE_SOUNDBANKTRANSIENT = 22, // 0x16
        IW19_ASSETTYPE_COL_MAP = 23, // 0x17
        IW19_ASSETTYPE_COM_MAP = 24, // 0x18
        IW19_ASSETTYPE_GLASS_MAP = 25, // 0x19
        IW19_ASSETTYPE_AIPATHS = 26, // 0x1a
        IW19_ASSETTYPE_NAVMESH = 27, // 0x1b
        IW19_ASSETTYPE_TACGRAPH = 28, // 0x1c
        IW19_ASSETTYPE_MAP_ENTS = 29, // 0x1d
        IW19_ASSETTYPE_FX_MAP = 30, // 0x1e
        IW19_ASSETTYPE_GFX_MAP = 31, // 0x1f
        IW19_ASSETTYPE_GFX_MAP_TRZONE = 32, // 0x20
        IW19_ASSETTYPE_IESPROFILE = 33, // 0x21
        IW19_ASSETTYPE_LIGHTDEF = 34, // 0x22
        IW19_ASSETTYPE_GRADINGCLUT = 35, // 0x23
        IW19_ASSETTYPE_UI_MAP = 36, // 0x24
        IW19_ASSETTYPE_FOGSPLINE = 37, // 0x25
        IW19_ASSETTYPE_ANIMCLASS = 38, // 0x26
        IW19_ASSETTYPE_PLAYERANIM = 39, // 0x27
        IW19_ASSETTYPE_GESTURE = 40, // 0x28
        IW19_ASSETTYPE_LOCALIZE = 41, // 0x29
        IW19_ASSETTYPE_ATTACHMENT = 42, // 0x2a
        IW19_ASSETTYPE_WEAPON = 43, // 0x2b
        IW19_ASSETTYPE_VFX = 44, // 0x2c
        IW19_ASSETTYPE_IMPACTFX = 45, // 0x2d
        IW19_ASSETTYPE_SURFACEFX = 46, // 0x2e
        IW19_ASSETTYPE_AITYPE = 47, // 0x2f
        IW19_ASSETTYPE_MPTYPE = 48, // 0x30
        IW19_ASSETTYPE_CHARACTER = 49, // 0x31
        IW19_ASSETTYPE_XMODELALIAS = 50, // 0x32
        IW19_ASSETTYPE_RAWFILE = 51, // 0x33
        IW19_ASSETTYPE_SCRIPTFILE = 52, // 0x34
        IW19_ASSETTYPE_SCRIPTDEBUGDATA = 53, // 0x35
        IW19_ASSETTYPE_STRINGTABLE = 54, // 0x36
        IW19_ASSETTYPE_LEADERBOARDDEF = 55, // 0x37
        IW19_ASSETTYPE_VIRTUALLEADERBOARDDEF = 56, // 0x38
        IW19_ASSETTYPE_DDL = 57, // 0x39
        IW19_ASSETTYPE_TRACER = 58, // 0x3a
        IW19_ASSETTYPE_VEHICLE = 59, // 0x3b
        IW19_ASSETTYPE_ADDON_MAP_ENTS = 60, // 0x3c
        IW19_ASSETTYPE_NETCONSTSTRINGS = 61, // 0x3d
        IW19_ASSETTYPE_LUAFILE = 62, // 0x3e
        IW19_ASSETTYPE_SCRIPTABLE = 63, // 0x3f
        IW19_ASSETTYPE_EQUIPSNDTABLE = 64, // 0x40
        IW19_ASSETTYPE_VECTORFIELD = 65, // 0x41
        IW19_ASSETTYPE_PARTICLESIMANIMATION = 66, // 0x42
        IW19_ASSETTYPE_STREAMINGINFO = 67, // 0x43
        IW19_ASSETTYPE_LASER = 68, // 0x44
        IW19_ASSETTYPE_TTF = 69, // 0x45
        IW19_ASSETTYPE_SUIT = 70, // 0x46
        IW19_ASSETTYPE_SUITANIMPACKAGE = 71, // 0x47
        IW19_ASSETTYPE_CAMERA = 72, // 0x48
        IW19_ASSETTYPE_HUDOUTLINE = 73, // 0x49
        IW19_ASSETTYPE_SPACESHIPTARGET = 74, // 0x4a
        IW19_ASSETTYPE_RUMBLE = 75, // 0x4b
        IW19_ASSETTYPE_RUMBLEGRAPH = 76, // 0x4c
        IW19_ASSETTYPE_ANIMPKG = 77, // 0x4d
        IW19_ASSETTYPE_SFXPKG = 78, // 0x4e
        IW19_ASSETTYPE_VFXPKG = 79, // 0x4f
        IW19_ASSETTYPE_FOOTSTEPVFX = 80, // 0x50
        IW19_ASSETTYPE_BEHAVIORTREE = 81, // 0x51
        IW19_ASSETTYPE_AIANIMSET = 82, // 0x52
        IW19_ASSETTYPE_AIASM = 83, // 0x53
        IW19_ASSETTYPE_PROCEDURALBONES = 84, // 0x54
        IW19_ASSETTYPE_DYNAMICBONES = 85, // 0x55
        IW19_ASSETTYPE_RETICLE = 86, // 0x56
        IW19_ASSETTYPE_XANIMCURVE = 87, // 0x57
        IW19_ASSETTYPE_COVERSELECTOR = 88, // 0x58
        IW19_ASSETTYPE_ENEMYSELECTOR = 89, // 0x59
        IW19_ASSETTYPE_CLIENTCHARACTER = 90, // 0x5a
        IW19_ASSETTYPE_CLOTHASSET = 91, // 0x5b
        IW19_ASSETTYPE_CINEMATICMOTION = 92, // 0x5c
        IW19_ASSETTYPE_ACCESSORY = 93, // 0x5d
        IW19_ASSETTYPE_LOCDMGTABLE = 94, // 0x5e
        IW19_ASSETTYPE_BULLETPENETRATION = 95, // 0x5f
        IW19_ASSETTYPE_SCRIPTBUNDLE = 96, // 0x60
        IW19_ASSETTYPE_BLENDSPACE2D = 97, // 0x61
        IW19_ASSETTYPE_XCAM = 98, // 0x62
        IW19_ASSETTYPE_CAMO = 99, // 0x63
        IW19_ASSETTYPE_XCOMPOSITEMODEL = 100, // 0x64
        IW19_ASSETTYPE_XMODELDETAILCOLLISION = 101, // 0x65
        IW19_ASSETTYPE_STREAMKEY = 102, // 0x66
        IW19_ASSETTYPE_STREAMTREEOVERRIDE = 103, // 0x67
        IW19_ASSETTYPE_KEYVALUEPAIRS = 104, // 0x68
        IW19_ASSETTYPE_STTERRAIN = 105, // 0x69
        IW19_ASSETTYPE_NATIVESCRIPTPATCH = 106, // 0x6a
        IW19_ASSETTYPE_COLLISIONTILE = 107, // 0x6b
        IW19_ASSETTYPE_EXECUTION = 108, // 0x6c
        IW19_ASSETTYPE_CARRYOBJECT = 109, // 0x6d
        IW19_ASSETTYPE_SOUNDBANKLIST = 110, // 0x6e
        IW19_ASSETTYPE_DECALVOLUMEMATERIAL = 111, // 0x6f
        IW19_ASSETTYPE_DECALVOLUMEMASK = 112, // 0x70
        IW19_ASSETTYPE_DYNENTITYLIST = 113, // 0x71
        IW19_ASSETTYPE_FX_MAP_TRZONE = 114, // 0x72
        IW19_ASSETTYPE_DLOGSCHEMA = 115, // 0x73
        IW19_ASSETTYPE_EDGELIST = 116, // 0x74
        IW19_ASSETTYPE_TRIGGEREFFECT = 117, // 0x75
        IW19_ASSETTYPE_WEAPONTRIGGER = 118, // 0x76
        IW19_ASSETTYPE_DWIDATA = 119, // 0x77
        IW19_ASSETTYPE_COUNT = 120,
    };

    enum VariableType : byte {
        IW19_VAR_UNDEFINED = 0x0,
        IW19_VAR_POINTER = 0x1,
        IW19_VAR_STRING = 0x2,
        IW19_VAR_ISTRING = 0x3,
        IW19_VAR_VECTOR = 0x4,
        IW19_VAR_FLOAT = 0x5,
        IW19_VAR_INTEGER = 0x6,
        IW19_VAR_CODEPOS = 0x7,
        IW19_VAR_PRECODEPOS = 0x8,
        IW19_VAR_FUNCTION = 0x9,
        IW19_VAR_BUILTIN_FUNCTION = 0xA,
        IW19_VAR_BUILTIN_METHOD = 0xB,
        IW19_VAR_STACK = 0xC,
        IW19_VAR_ANIMATION = 0xD,
        IW19_VAR_PRE_ANIMATION = 0xE,
        IW19_VAR_ANIM_TREE = 0xF,
        IW19_VAR_THREAD = 0x10,
        IW19_VAR_NOTIFY_THREAD = 0x11,
        IW19_VAR_TIME_THREAD = 0x12,
        IW19_VAR_CHILD_THREAD = 0x13,
        IW19_VAR_OBJECT = 0x14,
        IW19_VAR_DEAD_ENTITY = 0x15,
        IW19_VAR_ENTITY = 0x16,
        IW19_VAR_ARRAY = 0x17,
        IW19_VAR_DEAD_THREAD = 0x18,
        IW19_VAR_COUNT = 0x19,
    };

    const char* PoolNameOld(IW19PoolType type);
    IW19PoolType PoolIdOld(const char* name);


    const char* PoolName(IW8HashAssetType type);
    IW8HashAssetType PoolId(const char* name);
}