#pragma once
#include <tools/gsc/gsc_vm.hpp>
#include <tools/gsc/gsc.hpp>
#include <tools/gsc/gsc_opcodes.hpp>

namespace tool::gsc::opcode {
	class OpCodeT1007Registry {
	public:
		static void OpCode() {
		VmInfo* t107 = RegisterVM(VMI_T10_07, "Call of Duty: Black Ops 6 (07)", "t10", "bo6_7", VmFlags::VMF_CRC_DUMP | VmFlags::VMF_FOREACH_IW | VmFlags::VMF_EXPORT_NOCHECKSUM | VmFlags::VMF_HASH64 | VmFlags::VMF_HASH_CER | VmFlags::VMF_HASH_PATH_IW | VmFlags::VMF_CALL_NO_PARAMS | VmFlags::VMF_IW_LIKE | VmFlags::VMF_ISTRING_HASHED); // VmFlags::VMF_IW_CALLS | VmFlags::VMF_NO_PARAM_FLAGS
		t107->RegisterVmName("cer7", "t10_7", "blackops6_7");
		t107->AddPlatform(PLATFORM_PC);
		t107->RegisterVMGlobalVariable("level", OPCODE_IW_GetLevel);
		t107->RegisterVMGlobalVariable("game", OPCODE_IW_GetGame);
		t107->RegisterVMGlobalVariable("anim", OPCODE_IW_GetAnim);
		t107->RegisterVMOperatorFunction("waittill", "<caller> waittill(event, var*)", OPCODE_IW_SingleWaitTill, VPFD_SELF_PARAM | VPFD_UNPACK, 1);
		t107->RegisterVMOperatorFunction("isdefined", "isdefined(object) -> bool", OPCODE_IsDefined, VPFD_RETURN_VALUE, 1, 1);
		t107->RegisterVMOperatorFunction("notify", "<caller> notify(event, param*)", OPCODE_IW_Notify, VPFD_SELF_PARAM | VPFD_USE_PRE_SCRIPT_CALL, 1);
		t107->RegisterVMOperatorFunction("endon", "<caller> endon(event+)", OPCODE_EndOn, VPFD_SELF_PARAM | VPFD_USE_COUNT, 1);
		t107->RegisterVMOperatorFunction("wait", "wait(time)", OPCODE_Wait, VPFD_NONE, 1, 1);
		t107->RegisterVMOperatorFunction("waitframe", "waitframe()", OPCODE_IW_WaitFrame, VPFD_NONE, 0, 0);
		t107->RegisterVMOperatorFunction("getthread", "getthread() -> thread", OPCODE_IW_GetThread, VPFD_RETURN_VALUE, 0, 0);
		t107->RegisterVMOperatorFunction("istrue", "istrue(object) -> bool", OPCODE_IW_IsTrue, VPFD_RETURN_VALUE, 1, 1);
		t107->RegisterVMOperatorFunction("flat_args", "flat_args(array, count) -> bool", OPCODE_T10_FlatArgs, VPFD_RETURN_VALUE, 2, 2);
		t107->RegisterVMOperatorFunction("waittillframeend", "waittillframeend()", OPCODE_WaitTillFrameEnd, VPFD_NONE, 0, 0);
		t107->RegisterVMHashOPCode('#', OPCODE_GetHash, 8, [](const char* str) { return hash::Hash64A(str); });
		t107->RegisterVMHashOPCode('@', OPCODE_IW_GetDVarHash, 8, [](const char* str) { return hash::HashIWDVar(str); });
		t107->RegisterVMHashOPCode('%', OPCODE_IW_GetResourceHash, 8, [](const char* str) { return hash::HashIWAsset(str); });
		t107->RegisterVMHashOPCode('t', OPCODE_IW_GetTagHash, 4, [](const char* str) { return hash::HashX32(str); });
		t107->RegisterVMHashOPCode('s', OPCODE_T10_GetScrHash, 8, [](const char* str) { return hash::HashT10Scr(str); });
		t107->RegisterDevCall("assert", "assertmsg", "function_79901b4637c83c86", "assertex", "println", "print");
		t107->RegisterDatatype("builtinfunction", "builtinmethod", "function", "string", "istring", "struct", "int", "float", "vector", "xhash", "xhashasset", "istring");

		t107->RegisterOpCode(PLATFORM_PC, OPCODE_Nop, 0xaa, 0xab, 0xac, 0xad, 0xae, 0xaf);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_Nop, 0xb0, 0xb1, 0xb2, 0xb3, 0xb4, 0xb5, 0xb6, 0xb7, 0xb8, 0xb9, 0xba, 0xbb, 0xbc, 0xbd, 0xbe, 0xbf);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_Nop, 0xc0, 0xc1, 0xc2, 0xc3, 0xc4, 0xc5, 0xc6, 0xc7, 0xc8, 0xc9, 0xca, 0xcb, 0xcc, 0xcd, 0xce, 0xcf);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_Nop, 0xd0, 0xd1, 0xd2, 0xd3, 0xd4, 0xd5, 0xd6, 0xd7, 0xd8, 0xd9, 0xda, 0xdb, 0xdc, 0xdd, 0xde, 0xdf);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_Nop, 0xe0, 0xe1, 0xe2, 0xe3, 0xe4, 0xe5, 0xe6, 0xe7, 0xe8, 0xe9, 0xea, 0xeb, 0xec, 0xed, 0xee, 0xef);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_Nop, 0xf0, 0xf1, 0xf2, 0xf3, 0xf4, 0xf5, 0xf6, 0xf7, 0xf8, 0xf9, 0xfa, 0xfb, 0xfc, 0xfd, 0xfe, 0xff);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_CheckClearParams, 0x4d);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_SafeCreateLocalVariables, 0x5a);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_IW_RegisterMultipleVariables, 0x53);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_Undefined, 0x26);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_Undefined, 0x27);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_Undefined, 0x30);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_Undefined, 0x40); // Get Gvar gvar_unk2c
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_Undefined, 0x42); // op?
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_Undefined, 0x4b); // op?
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_Undefined, 0x50); //SuperNotEqual + defined
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_Undefined, 0x5f);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_Undefined, 0x64);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_Undefined, 0x67);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_Undefined, 0x6a);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_Undefined, 0x6d);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_Undefined, 0x73);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_Undefined, 0x79); // hash stuff?
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_Undefined, 0x7b); // op?
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_Undefined, 0x7d);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_Undefined, 0x86);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_Undefined, 0x88);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_Undefined, 0x8e); // op comp?
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_Undefined, 0x8f);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_Undefined, 0x97);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_Undefined, 0x9b);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_Nop, 0x00);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_Nop, 0x01);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_Nop, 0x02);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_Nop, 0x03);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_Nop, 0x04);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_Nop, 0x05);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_Nop, 0x06);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_IW_GetThread, 0x07);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_Nop, 0x08);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_IW_EvalLocalVariableCached0, 0x09);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_IW_EvalLocalVariableCached1, 0x0a);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_IW_EvalLocalVariableCached2, 0x0b);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_IW_EvalLocalVariableCached3, 0x0c);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_IW_EvalLocalVariableCached4, 0x0d);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_IW_EvalLocalVariableCached5, 0x0e);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_EvalLocalVariableCached, 0x0f);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_ScriptFunctionCallPointer, 0x10);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_GetResolveFunction, 0x11);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_Inc, 0x12);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_GetNegUnsignedShort, 0x13);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_Vector, 0x14);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_IsDefined, 0x15);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_IW_SetLevelFieldVariable, 0x16);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_ProfileStart, 0x17);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_Nop, 0x18);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_GetFloat, 0x19);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_IW_GetBuiltinFunction, 0x1a);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_GetNegByte, 0x1b);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_Bit_Or, 0x1c);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_CreateStruct, 0x1d);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_ScriptThreadCallPointer, 0x1e);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_CastBool, 0x1f);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_JumpOnTrueExpr, 0x20);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_ScriptMethodThreadCallPointerEndOn, 0x21);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_IW_GetBuiltinMethod, 0x22);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_BoolNot, 0x76, 0x23);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_JumpOnDefinedExpr, 0x24);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_JumpOnFalse, 0x25);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_IW_GetLevelGRef, 0x28);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_IW_EvalArrayCachedField, 0x29);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_LessThan, 0x2a);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_GetSelf, 0x2b);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_IW_SetAnimFieldVar, 0x2c);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_JumpOnFalseExpr, 0x2d);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_GreaterThanOrEqualTo, 0x2e);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_IW_WaitFrame, 0x2f);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_GetHash, 0x31);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_IW_Switch, 0x32);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_SuperEqual, 0x33);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_ScriptMethodCallPointer, 0x34);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_IW_EvalAnimFieldVarRef, 0x35);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_Divide, 0x36);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_ScriptMethodThreadCall, 0x37);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_EvalArrayRef, 0x38);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_CastFieldObject, 0x39);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_IW_EvalLocalVariableObjectCached, 0x3a);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_GetString, 0x3b);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_EvalFieldVariableRef, 0x3c);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_GetUnsignedShort, 0x3d);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_IW_EndSwitch, 0x3e);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_EvalLocalVariableRefCached, 0x3f);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_NotEqual, 0x41);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_Nop, 0x43);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_IW_GetLevel, 0x44);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_IW_GetPositionRef, 0x45);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_LessThanOrEqualTo, 0x46);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_IW_BuiltinMethodCallPointer, 0x47);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_IW_SetSelfFieldVar, 0x48);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_Plus, 0x49);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_ScriptMethodThreadCallEndOn, 0x4a);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_GetZero, 0x4c);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_CheckClearParams, 0x4d);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_Nop, 0x4e);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_JumpOnTrue, 0x4f);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_ProfileStop, 0x51);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_ScriptThreadCallPointerEndOn, 0x52);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_IW_RegisterMultipleVariables, 0x53);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_IW_WaitTillMatch, 0x54);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_ScriptFunctionCall, 0x55);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_ScriptThreadCallEndOn, 0x56);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_IW_GetDVarHash, 0x57);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_ScriptMethodCall, 0x58);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_IW_EvalAnimFieldVar, 0x59);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_SafeCreateLocalVariables, 0x5a);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_IW_AddToStruct, 0x5b);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_Minus, 0x5c);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_ShiftRight, 0x5d);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_End, 0x5e);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_IW_GetTagHash, 0x5f);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_IW_GetResourceHash, 0x60);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_GreaterThan, 0x61);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_BoolComplement, 0x62);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_IW_GetLocalizedHash, 0x63);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_IW_IsTrue, 0x65);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_ClearArray, 0x66);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_GetUnsignedInteger, 0x68);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_IW_BuiltinFunctionCallPointer, 0x69);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_SetLocalVariableCached, 0x6b);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_PreScriptCall, 0x6c);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_GetNegUnsignedInteger, 0x6e);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_EvalArray, 0x6f);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_IW_Notify, 0x70);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_WaitTillFrameEnd, 0x71);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_IW_GetAnimation, 0x72);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_GetVector, 0x74);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_DevblockBegin, 0x75);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_JumpOnDefined, 0x77);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_Equal, 0x78);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_T10_FlatArgs, 0x7a);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_SetVariableField, 0x7c);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_EvalFieldVariable, 0x7e);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_IW_GetAnim, 0x7f);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_DecTop, 0x80);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_SafeDecTop, 0x81);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_ShiftLeft, 0x82);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_Nop, 0x83);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_GetSelfObject, 0x84);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_SizeOf, 0x85);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_Wait, 0x87);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_IW_GetGameRef, 0x89);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_Modulus, 0x8a);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_ClearFieldVariable, 0x8b);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_IW_EvalLocalArrayCached, 0x8c);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_IW_EvalSelfFieldVarRef, 0x8d);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_Return, 0x90);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_ScriptThreadCall, 0x91);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_Dec, 0x92);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_IW_SingleWaitTill, 0x93);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_IW_EvalLevelFieldVariableRef, 0x94);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_GetUndefined, 0x95);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_IW_EvalLevelFieldVariable, 0x96);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_CallBuiltinFunction, 0x98);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_ScriptMethodThreadCallPointer, 0x99);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_CreateArray, 0x9a);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_Bit_And, 0x9c);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_IW_SetWaittillVariableFieldCached, 0x9d);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_ClearParams, 0x9e);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_T10_GetScrHash, 0x9f);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_Bit_Xor, 0xa0);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_IW_GetAnimationTree, 0xa1);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_Multiply, 0xa2);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_IW_EvalSelfFieldVar, 0xa3);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_AddToArray, 0xa4);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_EndOn, 0xa5);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_IW_GetGame, 0xa6);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_CallBuiltinMethod, 0xa7);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_GetByte, 0xa8);
		t107->RegisterOpCode(PLATFORM_PC, OPCODE_Jump, 0xa9);
	}
};
}