#pragma once
#include <tools/gsc/gsc_vm.hpp>
#include <tools/gsc/gsc.hpp>
#include <tools/gsc/gsc_opcodes.hpp>

namespace tool::gsc::opcode {
	class OpCodeT100BRegistry {
	public:
		static void OpCode() {
		VmInfo* t10b = RegisterVM(VMI_T10_0B, "Call of Duty: Black Ops 6 (0B)", "t10", "bo6_b", VmFlags::VMF_CRC_DUMP | VmFlags::VMF_FOREACH_IW | VmFlags::VMF_EXPORT_CRC32 | VmFlags::VMF_HASH64 | VmFlags::VMF_HASH_CER_SP | VmFlags::VMF_HASH_PATH_IW | VmFlags::VMF_CALL_NO_PARAMS | VmFlags::VMF_IW_LIKE | VmFlags::VMF_ISTRING_HASHED); // VmFlags::VMF_IW_CALLS | VmFlags::VMF_NO_PARAM_FLAGS
		t10b->RegisterVmName("cerb", "t10_b", "blackops6_b", "t10sp", "bo6sp");
		t10b->AddPlatform(PLATFORM_PC);
		t10b->RegisterVMGlobalVariable("level", OPCODE_IW_GetLevel);
		t10b->RegisterVMGlobalVariable("game", OPCODE_IW_GetGame);
		t10b->RegisterVMGlobalVariable("anim", OPCODE_IW_GetAnim);
		t10b->RegisterVMOperatorFunction("waittill", "<caller> waittill(event, var*)", OPCODE_IW_SingleWaitTill, VPFD_SELF_PARAM | VPFD_UNPACK, 1);
		t10b->RegisterVMOperatorFunction("isdefined", "isdefined(object) -> bool", OPCODE_IsDefined, VPFD_RETURN_VALUE, 1, 1);
		t10b->RegisterVMOperatorFunction("notify", "<caller> notify(event, param*)", OPCODE_IW_Notify, VPFD_SELF_PARAM | VPFD_USE_PRE_SCRIPT_CALL, 1);
		t10b->RegisterVMOperatorFunction("endon", "<caller> endon(event+)", OPCODE_EndOn, VPFD_SELF_PARAM | VPFD_USE_COUNT, 1);
		t10b->RegisterVMOperatorFunction("wait", "wait(time)", OPCODE_Wait, VPFD_NONE, 1, 1);
		t10b->RegisterVMOperatorFunction("waitframe", "waitframe()", OPCODE_IW_WaitFrame, VPFD_NONE, 0, 0);
		t10b->RegisterVMOperatorFunction("getthread", "getthread() -> thread", OPCODE_IW_GetThread, VPFD_RETURN_VALUE, 0, 0);
		t10b->RegisterVMOperatorFunction("istrue", "istrue(object) -> bool", OPCODE_IW_IsTrue, VPFD_RETURN_VALUE, 1, 1);
		t10b->RegisterVMOperatorFunction("flat_args", "flat_args(array, count) -> bool", OPCODE_T10_FlatArgs, VPFD_RETURN_VALUE, 2, 2);
		t10b->RegisterVMOperatorFunction("waittillframeend", "waittillframeend()", OPCODE_WaitTillFrameEnd, VPFD_NONE, 0, 0);
		t10b->RegisterVMHashOPCode('#', OPCODE_GetHash, 8, [](const char* str) { return hash::Hash64A(str); });
		t10b->RegisterVMHashOPCode('@', OPCODE_IW_GetDVarHash, 8, [](const char* str) { return hash::HashIWDVar(str); });
		t10b->RegisterVMHashOPCode('%', OPCODE_IW_GetResourceHash, 8, [](const char* str) { return hash::HashIWAsset(str); });
		t10b->RegisterVMHashOPCode('t', OPCODE_IW_GetTagHash, 4, [](const char* str) { return hash::HashX32(str); });
		t10b->RegisterVMHashOPCode('s', OPCODE_T10_GetScrHash, 8, [](const char* str) { return hash::HashT10ScrSP(str); });
		t10b->RegisterDevCall("assert", "assertmsg", "assertex", "function_615be98aeb6084e0", "println", "print");
		t10b->RegisterDatatype("builtinfunction", "builtinmethod", "function", "string", "istring", "struct", "int", "float", "vector");

		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_CheckClearParams, 0x24);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_SafeCreateLocalVariables, 0x20);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_IW_RegisterMultipleVariables, 0x93);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_BoolNot, 0x64, 0x6a);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_DevOp, 0x02);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_IW_GetThread, 0x07);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_IW_EvalLocalVariableCached0, 0x09);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_IW_EvalLocalVariableCached1, 0x0a);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_IW_EvalLocalVariableCached2, 0x0b);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_IW_EvalLocalVariableCached3, 0x0c);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_IW_EvalLocalVariableCached4, 0x0d);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_IW_EvalLocalVariableCached5, 0x0e);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_EvalLocalVariableCached, 0x0f);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_IW_GetLocalizedHash, 0x12);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_ProfileStop, 0x13);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_EvalLocalVariableRefCached, 0x14);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_ScriptMethodThreadCall, 0x1f);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_T10_GetScrHash, 0x25);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_ShiftLeft, 0x33);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_GetVector, 0x35);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_Plus, 0x6e);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_GetNegByte, 0x6c);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_ProfileStart, 0x91);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_GetByte, 0x49);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_CheckClearParams, 0x24);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_SafeCreateLocalVariables, 0x20);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_PreScriptCall, 0x58);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_GetString, 0x23);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_IW_Notify, 0x50);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_End, 0x45);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_GetSelf, 0xa2);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_DevblockBegin, 0x32);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_CallBuiltinMethod, 0x38);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_IW_EvalAnimFieldVar, 0x34);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_DecTop, 0x80);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_GetSelfObject, 0x85);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_ClearFieldVariable, 0x1a);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_IsDefined, 0x4a);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_CallBuiltinFunction, 0x8c);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_EvalArray, 0x96);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_Return, 0xa0);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_GetResolveFunction, 0x5a);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_IW_EvalSelfFieldVar, 0x3b);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_JumpOnFalse, 0x41);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_ScriptMethodCallPointer, 0x9c);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_IW_RegisterMultipleVariables, 0x93);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_JumpOnTrue, 0x26);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_IW_Switch, 0x90);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_GetFloat, 0x39);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_SetLocalVariableCached, 0x78);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_ScriptFunctionCall, 0x7f);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_JumpOnFalseExpr, 0x95);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_CastFieldObject, 0x8d);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_EvalFieldVariable, 0x88);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_LessThan, 0x51);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_CastBool, 0x36);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_Jump, 0x44);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_IW_EndSwitch, 0x5c);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_GetZero, 0x40);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_GetUndefined, 0x5f);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_ScriptFunctionCallPointer, 0x59);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_GetUnsignedShort, 0x2a);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_IW_EvalAnimFieldVarRef, 0x42);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_EvalArrayRef, 0x29);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_SetVariableField, 0x2b);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_CreateArray, 0x1d);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_IW_SetAnimFieldVar, 0x67);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_IW_SetSelfFieldVar, 0x99);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_EvalFieldVariableRef, 0x7b);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_NotEqual, 0x2d);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_IW_IsTrue, 0x8a);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_Equal, 0x1c);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_JumpOnTrueExpr, 0x73);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_ClearArray, 0x2e);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_SizeOf, 0x6d);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_GetByte, 0x49);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_IW_EvalLocalArrayCached, 0x82);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_GreaterThan, 0x31);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_IW_EvalLocalVariableObjectCached, 0x8f);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_IW_EvalArrayCachedField, 0x1b);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_AddToArray, 0x89);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_EndOn, 0x37);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_ScriptThreadCall, 0x4e);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_Wait, 0x84);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_LessThanOrEqualTo, 0x3c);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_IW_SingleWaitTill, 0x3d);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_IW_SetWaittillVariableFieldCached, 0x3f);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_ClearParams, 0x28);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_ScriptThreadCallEndOn, 0x79);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_Divide, 0x70);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_IW_EvalLevelFieldVariable, 0x68);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_IW_GetDVarHash, 0x6f);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_ScriptMethodCall, 0x7e);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_Inc, 0x98);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_Dec, 0x21);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_IW_WaitFrame, 0xa3);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_Minus, 0x63);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_JumpOnDefinedExpr, 0x22);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_Vector, 0x5b);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_IW_EvalSelfFieldVarRef, 0x1e);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_Multiply, 0x3e);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_GreaterThanOrEqualTo, 0x6b);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_ScriptMethodThreadCallEndOn, 0x81);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_CreateStruct, 0x3a);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_IW_AddToStruct, 0x7d);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_JumpOnDefined, 0x57);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_Modulus, 0x16);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_IW_SetLevelFieldVariable, 0x9f);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_GetHash, 0x18);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_ScriptThreadCallPointer, 0x61);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_IW_WaitTillMatch, 0x30);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_IW_GetResourceHash, 0x43);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_IW_EvalLevelFieldVariableRef, 0x74);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_SuperEqual, 0x4d);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_WaitTillFrameEnd, 0x75);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_IW_GetAnimationTree, 0x2c);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_ScriptMethodThreadCallPointer, 0x92);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_Bit_Or, 0x52);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_ScriptThreadCallPointerEndOn, 0x4f);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_GetNegUnsignedInteger, 0x7c);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_GetUnsignedInteger, 0x69);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_IW_BuiltinMethodCallPointer, 0x9e);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_IW_BuiltinFunctionCallPointer, 0x94);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_ScriptMethodThreadCallPointerEndOn, 0x56);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_IW_GetAnimation, 0x9d);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_Bit_And, 0x47);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_GetNegUnsignedShort, 0x5d);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_IW_GetBuiltinMethod, 0x46);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_BoolComplement, 0x53);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_T10_FlatArgs, 0x86);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_IW_GetGame, 0x55);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_IW_GetGameRef, 0x76);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_IW_GetLevelGRef, 0x8e);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_IW_GetLevel, 0x8b);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_IW_GetAnim, 0x72);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_GetAnimGRef, 0x7a);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_ShiftRight, 0x4b);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_IW_GetBuiltinFunction, 0x27);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_Bit_Xor, 0x97);
		t10b->RegisterOpCode(PLATFORM_PC, OPCODE_GetWorldObject, 0x77);
	}
};
}