// autogenerated file from bo3.json, do not edit this file

// game template id
constexpr const char* GAME_ID = "bo3";
// dumped module name
constexpr const char* MODULE_NAME = "BlackOps3_dump.exe";

/*
 * Fast Files
 */

// DB_AllocStreamPos (Fast Files)
extern hook::refs::Ref<void> DB_AllocStreamPos;
// DB_ConvertOffsetToAlias (Fast Files)
extern hook::refs::Ref<void> DB_ConvertOffsetToAlias;
// DB_ConvertOffsetToPointer (Fast Files)
extern hook::refs::Ref<void> DB_ConvertOffsetToPointer;
// DB_GetXAssetName (Fast Files)
extern hook::refs::Ref<void> DB_GetXAssetName;
// DB_IncStreamPos (Fast Files)
extern hook::refs::Ref<void> DB_IncStreamPos;
// DB_InitStreams (Fast Files)
extern hook::refs::Ref<void> DB_InitStreams;
// DB_InsertPointer (Fast Files)
extern hook::refs::Ref<void> DB_InsertPointer;
// DB_LinkXAssetEntry (Fast Files)
extern hook::refs::Ref<void> DB_LinkXAssetEntry;
// DB_PopStreamPos (Fast Files)
extern hook::refs::Ref<void> DB_PopStreamPos;
// DB_PushStreamPos (Fast Files)
extern hook::refs::Ref<void> DB_PushStreamPos;
// Load_ScriptStringList (Fast Files)
extern hook::refs::Ref<void> Load_ScriptStringList;
// Load_SimpleAsset_Internal (Fast Files)
extern hook::refs::Ref<void> Load_SimpleAsset_Internal;
// Load_Stream (Fast Files)
extern hook::refs::Ref<void> Load_Stream;
// Load_XAsset (Fast Files)
extern hook::refs::Ref<void> Load_XAsset;
// Load_XStringCustom (Fast Files)
extern hook::refs::Ref<void> Load_XStringCustom;
// g_streamPosIndex (Fast Files)
extern hook::refs::Ref<void> g_streamPosIndex;
// varScriptStringList (Fast Files)
extern hook::refs::Ref<void> varScriptStringList;
// varXAsset (Fast Files)
extern hook::refs::Ref<void> varXAsset;

/*
 * Gsc
 */

// mz_zip_reader_init (Gsc)
extern hook::refs::Ref<void> mz_zip_reader_init;

/*
 * @return the common fastfile names
 */
std::span<const char*> GetCommonFastFiles();

/*
 * Load the scans for the game
 * @param scan game
 */
void LoadScans(hook::scan_container::ScanContainer& scan);
