// autogenerated file from bo3.json, do not edit this file

// common fastfiles names
std::span<const char*> GetCommonFastFiles() {
    static const char* files[] { 
        "zone/core_common.ff",
        "zone/cp_common.ff",
        "zone/cp_common_all.ff",
        "zone/mp_common.ff",
        "zone/zm_common.ff",
        "zone/zm_common_all.ff",
    };
    return files;
}

// refs

// DB_AllocStreamPos
hook::refs::Ref<> DB_AllocStreamPos{};
// DB_ConvertOffsetToAlias
hook::refs::Ref<> DB_ConvertOffsetToAlias{};
// DB_ConvertOffsetToPointer
hook::refs::Ref<> DB_ConvertOffsetToPointer{};
// DB_GetXAssetName
hook::refs::Ref<> DB_GetXAssetName{};
// DB_IncStreamPos
hook::refs::Ref<> DB_IncStreamPos{};
// DB_InitStreams
hook::refs::Ref<> DB_InitStreams{};
// DB_InsertPointer
hook::refs::Ref<> DB_InsertPointer{};
// DB_LinkXAssetEntry
hook::refs::Ref<> DB_LinkXAssetEntry{};
// DB_PopStreamPos
hook::refs::Ref<> DB_PopStreamPos{};
// DB_PushStreamPos
hook::refs::Ref<> DB_PushStreamPos{};
// Load_ScriptStringList
hook::refs::Ref<> Load_ScriptStringList{};
// Load_SimpleAsset_Internal
hook::refs::Ref<> Load_SimpleAsset_Internal{};
// Load_Stream
hook::refs::Ref<> Load_Stream{};
// Load_XAsset
hook::refs::Ref<> Load_XAsset{};
// Load_XStringCustom
hook::refs::Ref<> Load_XStringCustom{};
// g_streamPosIndex
hook::refs::Ref<> g_streamPosIndex{};
// varScriptStringList
hook::refs::Ref<> varScriptStringList{};
// varXAsset
hook::refs::Ref<> varXAsset{};

// mz_zip_reader_init
hook::refs::Ref<> mz_zip_reader_init{};

constinit static hook::generated_scan_runtime::ScanInformation scans[] { 
    {
        .id = "fastfile.DB_AllocStreamPos",
        .scan = "E8 ?? ?? ?? ?? 48 8B 0D ?? ?? ?? ?? 48 89 01 48 89 05 ?? ?? ?? ?? 48 83 FB FE 75 ",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 1,
        .postOffset = 0,
        .single = false,
        .multiple = false,
        .ref = (void**)&DB_AllocStreamPos.ptr
    },
    {
        .id = "fastfile.DB_ConvertOffsetToAlias",
        .scan = "E8 ?? ?? ?? ?? 48 8B 5C 24 20 48 83 C4 28 E9 ?? ?? ?? ?? B9 07 00 00 00",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 1,
        .postOffset = 0,
        .single = false,
        .multiple = false,
        .ref = (void**)&DB_ConvertOffsetToAlias.ptr
    },
    {
        .id = "fastfile.DB_ConvertOffsetToPointer",
        .scan = "E8 ?? ?? ?? ?? 48 8B 05 ?? ?? ?? ?? BA 03 00 00 00 33 C9 48 83 C0 58 48 89 05",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 1,
        .postOffset = 0,
        .single = true,
        .multiple = false,
        .ref = (void**)&DB_ConvertOffsetToPointer.ptr
    },
    {
        .id = "fastfile.DB_GetXAssetName",
        .scan = "E8 ?? ?? ?? ?? 33 F6 80 38 2C",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 1,
        .postOffset = 0,
        .single = true,
        .multiple = false,
        .ref = (void**)&DB_GetXAssetName.ptr
    },
    {
        .id = "fastfile.DB_IncStreamPos",
        .scan = "E8 ?? ?? ?? ?? 40 0F B6 C7 48 8B 5C 24 30 48 83 C4 20 5F C3 32 C0 48 8B 5C 24 30 48 83 C4 20 5F C3 8B 15",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 1,
        .postOffset = 0,
        .single = true,
        .multiple = false,
        .ref = (void**)&DB_IncStreamPos.ptr
    },
    {
        .id = "fastfile.DB_InitStreams",
        .scan = "E8 ?? ?? ?? ?? B9 05 00 00 00 E8 ?? ?? ?? ?? 48 8D 0D",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 1,
        .postOffset = 0,
        .single = true,
        .multiple = false,
        .ref = (void**)&DB_InitStreams.ptr
    },
    {
        .id = "fastfile.DB_InsertPointer",
        .scan = "E8 ?? ?? ?? ?? 48 8B D8 EB 02 33 DB B1 01 E8",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 1,
        .postOffset = 0,
        .single = false,
        .multiple = false,
        .ref = (void**)&DB_InsertPointer.ptr
    },
    {
        .id = "fastfile.DB_LinkXAssetEntry",
        .scan = "E8 ?? ?? ?? ?? 48 8D 2D ?? ?? ?? ?? 48 89 06",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 1,
        .postOffset = 0,
        .single = true,
        .multiple = false,
        .ref = (void**)&DB_LinkXAssetEntry.ptr
    },
    {
        .id = "fastfile.DB_PopStreamPos",
        .scan = "E9 ?? ?? ?? ?? B9 07 00 00 00 E8 ?? ?? ?? ?? 48 8B 0D ?? ?? ?? ?? 48 89 01 48 89 05",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 1,
        .postOffset = 0,
        .single = false,
        .multiple = false,
        .ref = (void**)&DB_PopStreamPos.ptr
    },
    {
        .id = "fastfile.DB_PushStreamPos",
        .scan = "E8 ?? ?? ?? ?? 48 8B 0D ?? ?? ?? ?? 48 8B 19 48 85 DB 74 70 48 83 FB FD 77 13 E8",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 1,
        .postOffset = 0,
        .single = false,
        .multiple = false,
        .ref = (void**)&DB_PushStreamPos.ptr
    },
    {
        .id = "fastfile.Load_ScriptStringList",
        .scan = "48 89 05 ?? ?? ?? ?? E8 ?? ?? ?? ?? E8 ?? ?? ?? ?? 48 8B 05 ?? ?? ?? ?? 48 39 78 18",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 8,
        .postOffset = 0,
        .single = true,
        .multiple = false,
        .ref = (void**)&Load_ScriptStringList.ptr
    },
    {
        .id = "fastfile.Load_SimpleAsset_Internal",
        .scan = "BA 26 00 00 00 E8 ?? ?? ?? ?? 48 85 DB 74 0D 48 8B 05 ?? ?? ?? ?? 48 8B 08 48 89 0B",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 6,
        .postOffset = 0,
        .single = false,
        .multiple = false,
        .ref = (void**)&Load_SimpleAsset_Internal.ptr
    },
    {
        .id = "fastfile.Load_Stream",
        .scan = "E8 ?? ?? ?? ?? 84 C0 0F 84 9E 00 00 00 33 C9 48 89 5C 24 20 E8 ?? ?? ?? ??",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 1,
        .postOffset = 0,
        .single = false,
        .multiple = false,
        .ref = (void**)&Load_Stream.ptr
    },
    {
        .id = "fastfile.Load_XAsset",
        .scan = "48 89 35 ?? ?? ?? ?? E8 ?? ?? ?? ?? 48 83 C6 10 40 38 3D ?? ?? ?? ?? 75 07",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 8,
        .postOffset = 0,
        .single = true,
        .multiple = false,
        .ref = (void**)&Load_XAsset.ptr
    },
    {
        .id = "fastfile.Load_XStringCustom",
        .scan = "E8 ?? ?? ?? ?? EB 05 E8 ?? ?? ?? ?? 48 8B 05 ?? ?? ?? ?? 48 83 78 10 00 74 3F B9",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 1,
        .postOffset = 0,
        .single = true,
        .multiple = false,
        .ref = (void**)&Load_XStringCustom.ptr
    },
    {
        .id = "fastfile.g_streamPosIndex",
        .scan = "89 05 ?? ?? ?? ?? 89 05 ?? ?? ?? ?? 48 89 05 ?? ?? ?? ?? 89 05",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 2,
        .postOffset = 0,
        .single = true,
        .multiple = false,
        .ref = (void**)&g_streamPosIndex.ptr
    },
    {
        .id = "fastfile.varScriptStringList",
        .scan = "48 89 05 ?? ?? ?? ?? E8 ?? ?? ?? ?? E8 ?? ?? ?? ?? 48 8B 05 ?? ?? ?? ?? 48 39 78 18",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 3,
        .postOffset = 0,
        .single = true,
        .multiple = false,
        .ref = (void**)&varScriptStringList.ptr
    },
    {
        .id = "fastfile.varXAsset",
        .scan = "48 89 35 ?? ?? ?? ?? E8 ?? ?? ?? ?? 48 83 C6 10 40 38 3D ?? ?? ?? ?? 75 07",
        .type = hook::generated_scan_runtime::ST_RELATIVE,
        .offset = 3,
        .postOffset = 0,
        .single = true,
        .multiple = false,
        .ref = (void**)&varXAsset.ptr
    },
    {
        .id = "gsc.mz_zip_reader_init",
        .scan = "48 89 5C 24 10 48 89 74 24 18 57 48 83 EC 20 41 8B F0 48 8B D9",
        .type = hook::generated_scan_runtime::ST_ABSOLUTE,
        .offset = 0,
        .postOffset = 0,
        .single = true,
        .multiple = false,
        .ref = (void**)&mz_zip_reader_init.ptr
    },
};

void LoadScans(hook::scan_container::ScanContainer& scan) {
    hook::generated_scan_runtime::LoadScans(scan, scans, ACTS_ARRAYSIZE(scans));
}
