name: Build

on:
  push:
    paths:
      - "src/**"
      - "premake5.lua"
      - ".github/workflows/build.yml"
  pull_request:
    paths:
      - "src/**"
  workflow_dispatch:
    inputs:
      release:
        description: "Release after build"
        required: true
        type: boolean

jobs:
  build:
    name: ACTS (Windows)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3.5.3
        with:
          submodules: true
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64
      - name: Get version
        id: get_version
        shell: pwsh
        run: "\"version=$(scripts/getversion.ps1)\" | Out-File $env:GITHUB_OUTPUT"
      - name: Version
        run: "\"version: ${{ steps.get_version.outputs.version }}\""
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: "6.11.0"
          host: "windows"
          target: "desktop"
          arch: "win64_msvc2022_64"
          cache: true
          use-official: true
          email: ${{ secrets.QT_EMAIL }}
          pw: ${{ secrets.QT_PASSWORD }}
      - name: Create project
        shell: pwsh
        run: |
          scripts/setupdater.ps1 -versionEndpoint "https://github.com/${{ github.repository }}/releases/latest/download/version" zipEndpoint https://github.com/${{ github.repository }}/releases/latest/download/acts.zip"
          scripts/setup.ps1 -ci -build "Visual Studio 17 2022"
      - name: Build project
        shell: pwsh
        run: msbuild build/AtianCodTools.sln /p:Configuration=Release /p:Platform=x64
      - name: Run tests
        run: build/bin/Release/acts.exe --noUpdater -l p -d -t utest
      - name: Package project
        shell: pwsh
        run: scripts/package.ps1 -deployQt
      - name: Upload dev release
        uses: ncipollo/release-action@v1
        if: github.ref == 'refs/heads/main'
        with:
          commit: ${{ github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "latest_build"
          artifacts: "build/package/acts.zip,build/package/acts/bin/acts-shield-plugin.dll,build/package/acts/bin/version"
          artifactErrorsFailBuild: true
          makeLatest: false
          removeArtifacts: true
          replacesArtifacts: true
          allowUpdates: true
          name: "Dev build ${{ steps.get_version.outputs.version }}"
          body: "Latest dev build, [get the latest release build here](https://github.com/${{ github.repository }}/releases/latest)."
      - name: Upload release
        if: inputs.release && github.ref == 'refs/heads/main'
        uses: ncipollo/release-action@v1
        with:
          commit: ${{ github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "build/package/acts.zip,build/package/acts/bin/acts-shield-plugin.dll,build/package/acts/bin/version"
          artifactErrorsFailBuild: true
          makeLatest: true
          tag: "${{ steps.get_version.outputs.version }}"
          name: "${{ steps.get_version.outputs.version }}"
          bodyFile: release/RELEASE.MD


